スターレベルが上がったときにもマナを全回復
GiganticMinecraft/SeichiAssist pull request #1036
Opened 2021-06-18 02:12 UTC by KisaragiEffective

close #1026

2021-06-18 03:05 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +  def apply[F[_] : OnMinecraftServerThread : Sync](implicit manaApi: ManaApi[F, F, Player]): NotifyLevelUp[F, Player] = new NotifyLevelUp[F, Player] {
```suggestion
  def apply[F[_] : OnMinecraftServerThread : Sync](implicit manaApi: ManaWriteApi[F, Player]): NotifyLevelUp[F, Player] = new NotifyLevelUp[F, Player] {
```

2021-06-18 19:55 UTC, kory33 requested changes

2021-06-18 19:55 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        .apply(manaApi.manaAmount(player).restoreCompletely)
`NotifyLevelUp` にマナ全回復のロジックを入れるのは良くなさそうですね(処理内容がNotifyではないので)

manaサブシステムのapplication/processに、`UpdataManaCaps` (レベルが上がった時にマナ上限を再計算し、格納しなおすStream) のような定義を置くのはどうでしょうか？

2021-06-18 19:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        .apply(manaApi.manaAmount(player).restoreCompletely)
```Scala
repository.lift(player)
    .traverse(_.update(_.fillToCap))
    .as(())
```
すればよさそう

2021-06-18 20:39 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        .apply(manaApi.manaAmount(player).restoreCompletely)
resolved

2021-06-18 21:18 UTC, kory33 requested changes

2021-06-18 21:18 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/System.scala
> +    G[_] : ContextCoercion[*[_], F],
unnecessary

2021-06-18 21:19 UTC, kory33 requested changes

2021-06-18 21:19 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mana/application/process/UpdateManaCaps.scala
> +        }
1. `*>` をすると何が起こるかというと、一つ目のStreamの処理走る度に二つ目のStreamが走ります。特に、この場合二つ目のStreamは終了しないStreamですから、一つ目のStreamに一つ要素が流れた後、二つ目のStreamが要素(`()`)を出力し続ける挙動をします。これは恐らく意図しているものではありません。

2. 別ファイルにStreamを書いたほうが良さそうです。`UpdateManaCaps` は「(整地レベルの更新により)マナ上限を更新する」という意図で命名していますが、この処理は上限の更新ではなく回復のみです。

2021-06-18 22:58 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/System.scala
> +    G[_] : ContextCoercion[*[_], F],
resolved in 29a87da

2021-06-18 22:58 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mana/application/process/UpdateManaCaps.scala
> +        }
resolved in 72c05a8

2021-06-19 11:22 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        .apply(manaApi.manaAmount(player).restoreCompletely)
not resolved, to be resolved

2021-06-19 11:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        .apply(manaApi.manaAmount(player).restoreCompletely)
resolved

2021-06-19 20:20 UTC, kory33 submitted a review, later dismissed
LGTM

2021-06-19 20:20 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/System.scala
> +import com.github.unchama.generic.ContextCoercion
[nits] unused import

```suggestion
```

2021-06-19 20:20 UTC, kory33 approved these changes

2021-06-19 20:20 UTC, merged