四次元ポケットを開くコマンドの作成
GiganticMinecraft/SeichiAssist pull request #1161
Opened 2021-09-12 05:42 UTC by LargoGreenTea

#1157 の一部です。
(”/fd”での使用を前提に作られていますが、
https://discord.com/channels/237758724121427969/535458227312132106/886258409488384030
のアンケート結果によって変わる可能性があります。
)

2021-09-13 10:25 UTC, LargoGreenTea commented
ありがとうございます..🙏

2021-09-15 04:50 UTC, KisaragiEffective submitted a review, later dismissed
LGTM :+1:

2021-09-21 01:21 UTC, Lucky3028 commented
`/fd`で確定しました。

2021-09-28 23:32 UTC, kory33 requested changes
ありがとうございます、実装自体は大丈夫そうです！

ひとつ、`subsystem` に直接関連するようなコマンドはその `subsystem` 内で管理されるような設計にしていますので、コマンド実装と登録の位置変更だけお願いしたいです。具体的には、 [`fourdimensionalpocket.System`内のここ](https://github.com/GiganticMinecraft/SeichiAssist/blob/19ee2c38d8f5af298a794cad609df190cf7d7e89/src/main/scala/com/github/unchama/seichiassist/subsystems/fourdimensionalpocket/System.scala#L109)で `"fd"` と `executor` を関連付けるようにしてほしいです。

2021-09-29 00:49 UTC, KisaragiEffective submitted a review, later dismissed
~~`System`の`wired`メソッドにおける`implicit`引数パラメーターで`fourDimensionPocketApi: FourDimensionPocketApi[IO, Player]`などとして`FourDimensionPocketApi[IO, Player]`を要求しないとコンパイルが通りません~~

2021-09-29 03:54 UTC, kory33 commented
> `System`の`wired`メソッドにおける`implicit`引数パラメーターで`fourDimensionPocketApi: FourDimensionPocketApi[IO, Player]`などとして`FourDimensionPocketApi[IO, Player]`を要求しないとコンパイルが通りません

にゃ、そうではないです(`fourdimensionalpocket.System` がAPIを提供する側なのにエントリポイントがAPIインスタンスを要求するのはおかしい)

この場合、[`systemApi` の宣言](https://github.com/GiganticMinecraft/SeichiAssist/blob/cd43abb90b8a3dfcc75a6fddc8098a4e1278956d/src/main/scala/com/github/unchama/seichiassist/subsystems/fourdimensionalpocket/System.scala#L63)に `implicit` 修飾子を付けて `implicit val` にするか、 `executor` メソッドの引数から `implicit` を外して `systemApi` を直接渡してあげるかのどちらかですね（どっちでもいいと思います　お任せします）

2021-09-29 15:12 UTC, KisaragiEffective commented
<!-- test comment -->

2021-10-03 02:41 UTC, kory33 approved these changes
`executor` の定義内で作用が実行できていない状態になっていましたので `executionF` を追加して修正させていただきました
実装ありがとうございます！

2021-10-03 02:41 UTC, merged

2021-10-03 03:45 UTC, LargoGreenTea commented
お手数おかけしました、ありがとうございますを🙏