所有者を「なし」にするシステムの追加
GiganticMinecraft/SeichiAssist pull request #1164
Opened 2021-09-23 09:56 UTC by LargoGreenTea

関連：#1158

2021-09-23 09:57 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (inventory.row !=4){
```suggestion
    if (inventory.row != 4){
```

2021-09-23 09:58 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (inventory.getTitle == GOLD.toString + "" + BOLD + "名義をなくしたいアイテムを投入してください"){
```suggestion
    if (inventory.getTitle == s"${GOLD}${BOLD}名義をなくしたいアイテムを投入してください") {
```

2021-09-23 10:04 UTC, LargoGreenTea commented
レビューありがとうございます。https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/bdb32b49e08f247b5117bfc0260ec1b753440e69
にて修正しました。

2021-09-23 10:04 UTC, LargoGreenTea commented
間違えました、https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/46b71bb7212d3473ab0e51a69a7bd95ae3ca72f8
です。

2021-09-23 10:11 UTC, Lucky3028 reviewed
とりあえず見た目のところだけ

2021-09-23 10:11 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +        player.sendMessage(GREEN.toString + count +"個の認識されたアイテムの名義を「なし」に変更しました")
```suggestion
        player.sendMessage(s"${GREEN}${count}個の認識されたアイテムの名義を「なし」に変更しました")
```

2021-09-23 10:11 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +        if(m !=null){
```suggestion
        if(m ! =null){
```

2021-09-23 10:11 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              val RemovedNameLore = itemLore.filterNot( n => itemLore.startsWith("所有者"))
```suggestion
              val removedNameLore = itemLore.filterNot(n => itemLore.startsWith("所有者"))
```

2021-09-23 10:11 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +  //エラー分岐
このコメントいりますか？

2021-09-23 10:11 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              val NewLore = RemovedNameLore.::("名義:なし").asInstanceOf[java.util.List[String]]
```suggestion
              val newLore = removedNameLore.::("名義:なし").asInstanceOf[java.util.List[String]]
```

2021-09-23 10:11 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            if (!Util.isPlayerInventoryFull(player)) {
ここわざわざ否定しないで、単純に
> if (isPlayer...) {

にして、括弧の中を逆に書いたほうが見やすいですよね

2021-09-23 10:46 UTC, Lucky3028 reviewed
気になった点を追加

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +          if (m.getItemMeta.hasLore){
`ItemStack`が`ItemMeta`を持っているかどうかも確認する必要があります。
```suggestion
          if (m.hasItemMeta && m.getItemMeta.hasLore) {
```

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            val itemstack: ItemStack = m.getData.toItemStack
`m`はわざわざ変換しなくても`ItemStack`ですから、この行は不要では？

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            if (!Util.isPlayerInventoryFull(player)) {
それと、アイテムをプレイヤーに渡す個々の処理ですが、`m.getItemMeta.hasLore`の分岐の外でしないと、`ItemMeta`や`Lore`を持っていない`ItemStack`を返却できないのではないでしょうか。

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (inventory.getTitle == s"${GOLD}${BOLD}名義をなくしたいアイテムを投入してください") {
最初の中括弧は不要でした。すみません。
```suggestion
    if (inventory.getTitle == s"$GOLD${BOLD}名義をなくしたいアイテムを投入してください") {
```

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +        .title(s"$YELLOW$UNDERLINE${BOLD}名義削除システム")
```suggestion
        .title(s"$YELLOW$UNDERLINE${BOLD}所有者表記削除システム")
```

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +          s"$RESET${GREEN}所有者表記を取り除きたいアイテムの所有者を",
```suggestion
          s"$RESET${GREEN}所有者表記のあるアイテムの所有者を",
```

2021-09-23 10:46 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +          s"$RESET${GREEN}名義を削除したいアイテムを入れて",
```suggestion
          s"$RESET${GREEN}表記を削除したいアイテムを入れて",
```

2021-09-23 10:47 UTC, KisaragiEffective requested changes
少なくともコレクションの変換については修正しないとコンパイルが通りません

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    val player = event.getPlayer.asInstanceOf[Player]
```suggestion
    val player = event.getPlayer match {
      case p: Player => p
      case _ => return
    }
```

こちらのほうが型安全性の面で良いです

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            if (Util.itemStackContainsOwnerName(itemstack:ItemStack, player.getName)){
```suggestion
            if (Util.itemStackContainsOwnerName(itemstack, player.getName)){
```

`itemstack:ItemStack`における`ItemStack`は「[みなし型](http://yanana.github.io/scala-style/types/ascription.html)」ですが、639行目の宣言から自明であるため不必要です。

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      val item = inventory.getContents
```suggestion
      val items = inventory.getContents
```
他の出現箇所も同様

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      for(m <- item){
```suggestion
      for(item <- items){
```

他の出現箇所も同様

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            val itemstack: ItemStack = m.getData.toItemStack
```suggestion
            val itemstack = m
```
冗長な変数ではないでしょうか。もし冗長な変数であれば、削除することが可能です。

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              val itemLore = m.getItemMeta.getLore.asInstanceOf[List[String]]
`java.util.List` (`m.getItemMeta.getLore` が返すコレクションのクラス) と`scala.collections.List` (`filter` などができるクラス) は相異なるクラスであるため、このキャストは常に失敗します。代わりに、[コレクションの変換](https://docs.scala-lang.org/ja/overviews/collections/conversions-between-java-and-scala-collections.html) を用いてください。

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              val NewLore = RemovedNameLore.::("名義:なし").asInstanceOf[java.util.List[String]]
この行も641行目と同様、常に失敗します。

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            }
```suggestion
            Util.grantItemStacksEffect[IO]
```

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +        ))
```suggestion
        .lore(
          s"$RESET${GREEN}所有者表記を取り除きたいアイテムの所有者を",
          s"$RESET${GOLD}「所有者：なし」RESET${GREEN}に変更します",
          s"$RESET${GREEN}出てきたインベントリに",
          s"$RESET${GREEN}名義を削除したいアイテムを入れて",
          s"$RESET${GREEN}escキーを押してください",
          s"$RESET${DARK_GRAY}たまにアイテムが消失しますが",
          s"$RESET${DARK_GRAY}補償はしていません(ごめんなさい)",
          s"$RESET${DARK_GRAY}神に祈りながら交換しよう",
          s"$RESET$DARK_RED${UNDERLINE}クリックで開く"
        )
```

nits: `lore`は可変長引数も受け付けるため、こちらでも良いと思われます

2021-09-23 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +  def onItemNameRemoveEvent(event: InventoryCloseEvent): Unit = {
```suggestion
  /**
  * 名義除去システム
  */
  def onItemOwnerReferenceRemove(event: InventoryCloseEvent): Unit = {
```

2021-09-23 10:53 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +          s"$RESET${GOLD}「所有者：なし」RESET${GREEN}に変更します",
```suggestion
          s"$RESET${GOLD}「所有者: なし」RESET${GREEN}に変更します",
```

2021-09-23 11:59 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +          s"$RESET${GOLD}「所有者：なし」RESET${GREEN}に変更します",
ありがとうございます、https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/ac18dc04694b8c3fde7efd3ff52e80b5162eeeee
にて修正いたしました。

2021-09-23 12:02 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              val itemLore = m.getItemMeta.getLore.asInstanceOf[List[String]]
ありがとうございます、
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/be45babfa9b2aa85acb980e967e8eb1ee8c2d0ac と https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/30af3dccb24f1ffdaab56a09b41b5c13fc65438d で変更しました

2021-09-23 12:07 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +  def onItemNameRemoveEvent(event: InventoryCloseEvent): Unit = {
ありがとうございます、おそらくhttps://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/3a63dd4bf79838e00f5e5445829c6c8dae6f0c03 で追加しました。

2021-09-23 12:08 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +        ))
ありがとうございます、おそらくhttps://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/63434ef294ba1e4719a8ff5a628a49d908013291 にて変更しました。(コミットを大きくしてしまい、わかりにくくなっていると思います。申し訳ございません...)

2021-09-23 12:09 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            }
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/2943dcfbe143951bc7228fd6bc8fa1341d5f068b で変更しました、ありがとうございます

2021-09-23 12:11 UTC, KisaragiEffective commented
@LargoGreenTea
:bulb: 直した箇所は"Resolve conversation"というところを押すと折りたたむことができます

2021-09-23 12:27 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      for(m <- item){
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/2ad9c29534a58abcb6fa3b57d7dc40b234bfb7e9 にて変数名を変更しました。ありがとうございます。

2021-09-23 12:32 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +         Util.grantItemStacksEffect[IO]()
ここで括弧の中に何も指定しないと、何のアイテムも付与されません
```suggestion
         Util.grantItemStacksEffect[IO](item)
```

2021-09-23 12:35 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +          if (m.getItemMeta.hasLore){
これ治ってないっぽいですよ

2021-09-23 12:36 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +          if (m.getItemMeta.hasLore){
`item.getItemMeta.hasLore`を2回確認しているようです

2021-09-23 12:38 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +          if (m.getItemMeta.hasLore){
あれ… 本当ですね

2021-09-23 12:38 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            if (Util.itemStackContainsOwnerName(itemstack:ItemStack, player.getName)){
これも治っていません

2021-09-23 12:39 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            val itemstack= item
この変数代入は不要です

2021-09-23 12:41 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (inventory.getTitle == s"$GOLD${BOLD}名義をなくしたいアイテムを投入してください") {
それと、細かい話ですが、この条件分岐はl.635の条件分岐と`||`でつないで早期リターンしてもよいかと思われます。

2021-09-23 12:50 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              item.getItemMeta.setLore(newLore)
というかここってちゃんと新しいLoreの生成や`setLore`できていますか？
おそらくこのままだと、loreが「所有者: なし」の1行だけになると思われますが...

2021-09-23 13:00 UTC, Lucky3028 reviewed
また細かいもので申し訳ないです。
それと、ifの条件を指定した後の丸括弧と中括弧の間であったり、ifやforと丸括弧の間には半角スペースを入れると見やすいです。（プログラミング用のエディタを使用している場合は、ワンクリックで自動でそういうのもろもろをやってくれますのでおすすめです。）

例
```
for {...

if (aaa > 1) {...
```

2021-09-23 13:10 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              item.getItemMeta.setLore(newLore)
少しおかしそうです、修正します

2021-09-23 13:55 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +  def onItemNameRemoveEvent(event: InventoryCloseEvent): Unit = {
「アイテム名の削除」ではない
```suggestion
  def onItemOwnerRemoveEvent(event: InventoryCloseEvent): Unit = {
```

2021-09-23 13:56 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (inventory.row != 4 ||  inventory.getTitle != s"$GOLD${BOLD}名義をなくしたいアイテムを投入してください") {
表記ゆれがめちゃ気になってしまうので...すみません...
```suggestion
    if (inventory.row != 4 ||  inventory.getTitle != s"$GOLD${BOLD}所有者表記を削除したいアイテムを投入してください") {
```

2021-09-23 13:58 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +    val ItemNameRemoveButton:Button = {
```suggestion
    val removeItemOwnerNameButton = {
```

2021-09-23 13:58 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/414f3bdb611bd72f7e7e344d95fa319d9311e61b で修正しました、ありがとうございます

2021-09-23 13:59 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    }
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/bbf6c3d7353ae2ba7a0b843f5dbad6b5c51c2948 にて修正しました、

2021-09-23 14:00 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +import scala.util.chaining.scalaUtilChainingOps
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/6c3a4158fb7608f30d0d2f5ac8ca7cc61bd88e61 にて修正しました、ありがとうございます！

2021-09-23 14:01 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +import scala.jdk.CollectionConverters.{CollectionHasAsScala, SeqHasAsJava}
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/d6504fe8a5b3633af04e5a310f70eb89a05a87f8 で修正しました

2021-09-23 14:15 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (inventory.row != 4 ||  inventory.getTitle != s"$GOLD${BOLD}名義をなくしたいアイテムを投入してください") {
本当にありがとうございます..
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/0e32772faf7b1a1ffde49a2cf18eaf8c90e34167 にて修正しました

2021-09-23 14:16 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +    val ItemNameRemoveButton:Button = {
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/cb4eec8b6b46ee67be4794f2f4b7b3be9823d201

2021-09-23 14:27 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              item.getItemMeta.setLore(newLore)
```
val itemLore = item.getItemMeta.getLore.asScala.toList
val newItemLore = itemLore.map(lore => if (lore.startsWith("所有者")) "所有者: なし" else lore)
item.getItemMeta.setLore(newItemLore)
```
みたいな感じでよいのでは？

2021-09-23 14:27 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              item.getItemMeta.setLore(newLore)
あとよく考えたら所有者の表記ってカラーコードが適用されているので、`startsWith("所有者")`だとヒットしなさそうです

2021-09-23 14:54 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              item.getItemMeta.setLore(newLore)
すみません、遅くなりました

確かに、そっちの方が見やすそうですね...適用してみます

2021-09-23 15:46 UTC, KisaragiEffective requested changes

2021-09-23 15:46 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    }
`count`が一度も使われていないため、メッセージが常に一定になります。

2021-09-23 22:49 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    }
ありがとうございます、https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/86892a6b6abc4d0f8f8ca884841496e446430a62
にて解決しました

2021-09-24 06:59 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              item.getItemMeta.setLore(newLore)
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/d9a2f1109924faddb90a00ad9e20bfdd5c3cfcb4

2021-09-24 12:57 UTC, Lucky3028 reviewed
表記部分のみ

2021-09-24 12:57 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            itemLore.map(loreElement => Nil).foldLeft(Nil: List[Int])(_ ++ _)
ここはもういらないですよね

2021-09-24 12:57 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +		  count += 1
インデント
```suggestion
            count += 1
```

2021-09-24 12:57 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    }
不要な改行と括弧
```suggestion
    if (inventory.row != 4 || inventory.getTitle != s"$GOLD${BOLD}所有者名義を削除したいアイテムを投入してください") return
```

2021-09-24 12:57 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      player.sendMessage(s"{GREEN} ${count}個のアイテムのを認識し、所有者表記「なし」に変更しました")
```suggestion
      player.sendMessage(s"{GREEN} ${count}個のアイテムのを認識し、所有者表記を「なし」に変更しました")
```

2021-09-24 13:11 UTC, Lucky3028 commented
それとふと気づいたんですが、`setLore`してるところって、新しいloreを設定した`ItemMeta`を`ItemStack`にセットして、さらにその新しく`ItemMeta`がセットされた`ItemStack`を返さないといけないのでは？

例:
https://github.com/GiganticMinecraft/SeichiAssist/blob/995107865cb7f44bca20b328aa84f5c29a95ce41/src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/anniversary/AnniversaryItemData.scala#L44-L51

2021-09-24 13:35 UTC, KisaragiEffective requested changes

2021-09-24 13:35 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +            itemLore.map(loreElement => Nil).foldLeft(Nil: List[Int])(_ ++ _)
```suggestion
```
この文の実行結果は常に捨てられます。加えて何らかの変数を書き換えるなどの副作用がないため、この文は完全に削除することができます。

2021-09-24 14:43 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      player.sendMessage(s"{GREEN} ${count}個のアイテムのを認識し、所有者表記「なし」に変更しました")
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/1156b1eac7e093c7a9abfaa867e0a8d7b7c52ebc にて修正しました、ありがとうございます

2021-09-24 14:45 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    }
https://github.com/GiganticMinecraft/SeichiAssist/pull/1164/commits/32e91a4973ebfb2acad8db536b9ad65adf4a33b6 にて変更しました、ありがとうございます!

2021-09-27 05:59 UTC, KisaragiEffective commented
(dropped merge commit.)

2021-10-04 03:19 UTC, Lucky3028 approved these changes
`var count`がまだちょっと嫌ですけど、解決策が思いつかないのでapproveにしておきます。

2021-10-04 03:44 UTC, KisaragiEffective requested changes
otherwise LGTM

2021-10-04 03:44 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              getLore.clear()
611行目で`setLore`しているのでそんなことはないと思いますが…
念を入れるのであれば `setLore(null)`するとLoreが消えるようですが、やはり不要だと思います。

2021-10-04 03:44 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      player.sendMessage(s"{GREEN} ${count}個のアイテムのを認識し、所有者表記を「なし」に変更しました")
```suggestion
      player.sendMessage(s"{GREEN} ${count}個のアイテムを認識し、所有者表記を「なし」に変更しました")
```

please fix this potential typo

2021-10-04 03:44 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +            // TODO メニューインベントリに差し替える
```suggestion
```

invalid
これはメニューでは表現できません ( by @kory33 )

2021-10-05 14:09 UTC, LargoGreenTea commented
すみません、確認遅れました

2021-10-05 14:14 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +            // TODO メニューインベントリに差し替える
ありがとうございます、 c078edf にて修正しました

2021-10-05 14:15 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +      player.sendMessage(s"{GREEN} ${count}個のアイテムのを認識し、所有者表記を「なし」に変更しました")
見落としてました...ありがとうございます 901cbf3 にて修正しました

2021-10-05 14:17 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +              getLore.clear()
そういう感じなんですね... 
ありがとうございます、 a24e71a のように変更しました

2021-10-06 11:24 UTC, KisaragiEffective approved these changes
otherwise LGTM, 開発お疲れ様でした！

2021-10-06 11:24 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (count < 1) {
nits: 条件を`count > 0`として処理内容を入れ替えたほうが良さそう

2021-10-06 12:06 UTC, LargoGreenTea commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerInventoryListener.scala
> +    if (count < 1) {
ありがとうございます、
1ea5450 にて変更しました!

2021-11-24 02:47 UTC, merged