[update] use enum for BreakUtil.getCardinalDirection
GiganticMinecraft/SeichiAssist pull request #1340
Opened 2022-02-01 15:33 UTC by KisaragiEffective

2022-02-01 17:40 UTC, kory33 requested changes

2022-02-01 17:40 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  def getCardinalDirection(entity: Entity): Option[CardinalDirection] = {
```suggestion
  def getCardinalDirection(entity: Entity): CardinalDirection = {
```

どうせならこうしちゃった方がいいかも

2022-02-02 04:24 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  def getCardinalDirection(entity: Entity): Option[CardinalDirection] = {
resolved in f6a245b

2022-02-02 05:21 UTC, kory33 approved these changes
LGTM

2022-02-02 05:22 UTC, merged