建築量のレートリミッターをシリアライゼーション
GiganticMinecraft/SeichiAssist pull request #1345
Opened 2022-02-12 12:22 UTC by KisaragiEffective

2022-02-12 15:01 UTC, kory33 requested changes
ありがとうございます！
マイグレーションスクリプトは良さそうで、`overwriteWithDatabaseValue` は不要で、Definitionはもう少し簡潔に書けるかなという気持ちです

2022-02-12 15:01 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +      wrs => BuildExpAmount(wrs.bigDecimal("buildcount"))
一つ前のコメントにあるように、二度値を用意するようなことをしない方がすっきりしそう

UuidがKeyに入った[RefDict](https://github.com/GiganticMinecraft/SeichiAssist/blob/4f1079f2af1bfb2e069673e261007ccdc73fe65a/src/main/scala/com/github/unchama/generic/RefDict.scala#L12)にデータを読み書きするようなDefinitionを生成する[usingUuidRefDict](https://github.com/GiganticMinecraft/SeichiAssist/blob/e1c4682bf7a2841e506fc5b782996555b1879d64/src/main/scala/com/github/unchama/datarepository/definitions/RefDictBackedRepositoryDefinition.scala#L34)が実装されているので、これを使えば永続化層の読み書きと、書き込み前の前処理に関する処理を統合できそう？

2022-02-19 09:45 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +        }
fixed

2022-02-19 09:45 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +      wrs => BuildExpAmount(wrs.bigDecimal("buildcount"))
fixed

2022-02-19 09:45 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/datarepository/template/initialization/RepositoryInitializationExt.scala
> +    def overwriteWithDatabaseValue(key: String, upperLimit: R, reset: FiniteDuration)
fixed

2022-02-19 10:18 UTC, kory33 commented on src/main/resources/db/migration/V1.7.5__Create_player_rate_limit_table.sql
> +    current_value CHAR(32) NOT NULL,
これ `current_value` の情報量が少なすぎるかも
フィールド名もう少し詳しい方が嬉しそう(あとchar(32)は渋いので数値型にした方がいいです)

2022-02-19 10:18 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +      rateLimiter.peekAvailablePermission.flatMap(a => persistence.write(HasUuid[Player].of(p), a))
write時にavailablePermissionを書いているのに、read時には(上限値-書き込んだ値)を読み込んでそう

2022-02-19 10:18 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/domain/BuildAmountPermission.scala
> +object BuildAmountPermission {
どちらかというと、 `BuildAmountRateLimitPersistence` を `RefDict[UUID, BuildAmountPermission]` にしたいだけで、`RateLimiter` はBuildExpAmountのものでいいかも

2022-02-19 11:15 UTC, KisaragiEffective commented
TODO: 残りのリクエスト上限が取得された日時を用いたハンドルをしないと正しいシリアライゼーションにならない

2022-02-19 13:39 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/domain/BuildAmountPermission.scala
> +object BuildAmountPermission {
c6361c4

2022-02-19 13:39 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +      rateLimiter.peekAvailablePermission.flatMap(a => persistence.write(HasUuid[Player].of(p), a))
85bb1d8

2022-02-19 13:39 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.7.5__Create_player_rate_limit_table.sql
> +    current_value CHAR(32) NOT NULL,
78c058e

2022-02-19 14:03 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +        val scalaDuration = FiniteDuration.apply(duration.toNanos, TimeUnit.NANOSECONDS)
```suggestion
        val duration = FiniteDuration(
          java.time.Duration
            .between(loadedRecord.recordTime, maxValueWithCurrentTime.recordTime)
            .toNanos,
          TimeUnit.NANOSECONDS
        )
```

2022-02-19 14:32 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/domain/BuildAmountPersistenceRecord.scala
> +case class BuildAmountPersistenceRecord(raw: BuildExpAmount, recordTime: LocalDateTime)
d9a6379 c87237e

2022-02-19 14:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +    val maxValueWithCurrentTime = BuildAmountPersistenceRecord.now[G](max).coerceTo[F].toIO.unsafeRunSync()
32900d2

2022-02-19 18:39 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/domain/BuildAmountRateLimiterSnapshot.scala
> + * `RateLimiter[F, BuildExpAmount]`がどの程度のリクエストをタイムスライスの中で受け付けたかについて日時付きで保存するクラス
総受付量ではなくて残量っぽい

2022-02-19 18:39 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +    val rateLimiter = BuildAmountRateLimiterSnapshot.now(max).flatMap { bapr =>
Snapshot作らずに直接RateLimiter作成して良さそう

2022-02-19 18:39 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +    RefDictBackedRepositoryDefinition.usingUuidRefDictWithEffectfulDefault(persistence)(maxValueWithCurrentTimeG)
これ、デフォルト値を使わずにOptionを返してくるようなusingUuidRefDictWithoutDefaultメソッドを生やして、それを使った方がいいかも(スナップショットが存在しないプレーヤーに対してもデフォルト値として現在時刻と最大値が入ったスナップショットがあったものとするのは不自然さを感じる)

2022-02-19 18:39 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +    RefDictBackedRepositoryDefinition.usingUuidRefDictWithEffectfulDefault(persistence)(maxValueWithCurrentTimeG)
その上で、各プレーヤーについて「残量」をOption[BARLSnapshot]のパターンマッチで計算して、残量をもとにRateLimiterのインスタンスを作るのが自然な流れぽい？

2022-02-19 18:39 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +      val program = for {
二つのプロセスを並列で走らせて、それぞれRateLimiterを用意して、
 - 一方は一度peekして
 - もう一方はpeekせずに

(数秒間待った後)getAvailablePermissionをして、最後に値が等しいかを確かめる

と言った内容のテストの方がより仕様を捉えてそうです。

ちなみに、時計が止まってる時にpeekが冪等、というのは仕様とは言えなさそう。なぜなら普通時計は動いているので、これが成り立っていてもあまり嬉しくなさそうなので。

2022-02-19 18:46 UTC, kory33 requested changes

2022-02-19 18:46 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/ratelimiting/RateLimiter.scala
> +  def peekAvailablePermission: F[A]
peekAvailablePermissions

2022-02-20 00:28 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +          // イニシャライゼーションで作成されるレートリミッターの 時刻起点が
起点の差分がスパンの整数倍とは限らない、ということを言うべき

2022-02-20 11:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +    RefDictBackedRepositoryDefinition.usingUuidRefDictWithEffectfulDefault(persistence)(maxValueWithCurrentTimeG)
3022f66

2022-02-20 11:40 UTC, KisaragiEffective commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +      val program = for {
51734f2

2022-02-20 11:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +          // イニシャライゼーションで作成されるレートリミッターの 時刻起点が
3eb8c65

2022-02-20 11:41 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/generic/ratelimiting/RateLimiter.scala
> +  def peekAvailablePermission: F[A]
0e8c0b5

2022-02-20 11:41 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +    val rateLimiter = BuildAmountRateLimiterSnapshot.now(max).flatMap { bapr =>
6807192

2022-02-20 11:41 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/domain/BuildAmountRateLimiterSnapshot.scala
> + * `RateLimiter[F, BuildExpAmount]`がどの程度のリクエストをタイムスライスの中で受け付けたかについて日時付きで保存するクラス
46c8948

2022-02-20 12:11 UTC, kory33 reviewed
otherwise LGTM

2022-02-20 12:11 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/RateLimiterRepositoryDefinitions.scala
> +              }
RateLimiterの初期値(`: BuildExpAmount`)の量を `loadedRecordOpt.fold` で取って、その量だけpermitを持ってるRateLimiterを作る、という風にした方がすっきりしそう

なので、
 - `RateLimiter` 側に、初期値を(maxとは別に)取るファクトリを用意する
 - それを使うようにする

の二点をすると良さそう

2022-02-20 12:11 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +        rateLimiterA <- FixedWindowRateLimiter.in[Task, SyncIO, Natural](maxPermits, period).coerceTo[Task]
```suggestion
        rateLimiterA <- FixedWindowRateLimiter.in[Task, Task, Natural](maxPermits, period)
```

2022-02-20 12:11 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +      }
これは一つ前のコメントの通り仕様では無さそう。実際 `period` を `1.second` にしたら落ちてしまうはず

2022-02-20 12:11 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +      awaitForProgram(runConcurrent(program)(100), 5.seconds)
並列数10000とか100000に上げても良さそう(テストが極度に重くならない範囲で上げてしまいましょう)

2022-02-20 12:15 UTC, KisaragiEffective commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +        rateLimiterA <- FixedWindowRateLimiter.in[Task, SyncIO, Natural](maxPermits, period).coerceTo[Task]
実はcoerceTo側が意図せず混入した

2022-02-20 14:36 UTC, KisaragiEffective commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +      }
62266ca

2022-02-20 14:36 UTC, KisaragiEffective commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +        rateLimiterA <- FixedWindowRateLimiter.in[Task, SyncIO, Natural](maxPermits, period).coerceTo[Task]
62266ca

2022-02-20 14:52 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +      }
言葉足らずですみません、そもそもこの性質(`"not decrease permits after peek"`)は`FixedWindowRateLimiter`の実装詳細に依存したもので、一般のRateLimiterに対してテストするものではないと思っているので、テストケースとして適切ではないのではないでしょうか、という意見でした。

https://github.com/GiganticMinecraft/SeichiAssist/pull/1345#discussion_r810524053

> ちなみに、時計が止まってる時にpeekが冪等、というのは仕様とは言えなさそう。なぜなら普通時計は動いているので、これが成り立っていてもあまり嬉しくなさそうなので。

2022-02-23 14:09 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +        peekB <- rateLimiterB.peekAvailablePermissions.coerceTo[Task]
```suggestion
        _ <- rateLimiterA.peekAvailablePermissions
        _ <- monixTimer.sleep(sleepPeriod)
        peekA <- rateLimiterA.peekAvailablePermissions
        peekB <- rateLimiterB.peekAvailablePermissions
```

2022-02-23 14:09 UTC, kory33 commented on src/test/scala/com/github/unchama/generic/ratelimiting/RateLimiterPermissionPeekSpec.scala
> +
```suggestion
```

2022-02-23 14:35 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/ratelimiting/FixedWindowRateLimiter.scala
> +      }
```suggestion
    val initialCount = maxPermits |-| firstPermits.getOrElse(maxPermits)

    for {
      countRef <- Ref.of[G, A](initialCount)

      rateLimiter = RateLimiter.fromCountRef(countRef)(maxPermits)
```

2022-02-23 15:11 UTC, merged