lastquit周りの変更をバレンタインイベント以外にも行う
GiganticMinecraft/SeichiAssist pull request #1400
Opened 2022-02-27 05:11 UTC by Lucky3028

close #1369

2022-02-27 05:38 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDuration.scala
>    def isInDuration(base: LocalDateTime): Boolean = {
これ今気づいたんですけど、逆かも(メソッドの意味的にcontainsみたいな名前の方が良さそう)

2022-02-27 05:38 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDuration.scala
> +  def isBeforeDuration(base: LocalDateTime): Boolean = base.isBefore(from) || base.isEqual(from)
同様の理由で、isEntirelyAfterみたいな名前になりそう

2022-02-27 05:43 UTC, Lucky3028 commented
レビューありがとうございます、直しました

2022-02-27 06:22 UTC, kory33 requested changes

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +      assert(duration.to.isEqual(to.minusYears(1)))
```suggestion
      val localDateTime = from
      val duration = DateTimeDuration(localDateTime, localDateTime)
      assert(duration.from.isEqual(localDateTime))
      assert(duration.to.isEqual(localDateTime))
```

テストの説明の通り書いて良さそう

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +    "be generated unsuccessfully with illegal LocalDateTime" in {
```suggestion
    "not be generated with illegal LocalDateTime" in {
```

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +  private val to = LocalDateTime.of(2023, 1, 1, 4, 10)
```suggestion
  private val t = LocalDateTime.of(2022, 1, 1, 4, 10)
  private val tPlusOneYear = t.plusYears(1)
```

とかにしてしまってもいいかも

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +      assert(duration.to.isEqual(to))
この `assert` は普通の `from` / `to` の組に成り立つ条件ではないので、
 - `duration.from` / `duration.to` から `LocalDate` を取って `dateFrom` / `dateTo` と等しいかを見る
 - `require(dateFrom.localTime.isEqual(...))` みたいな事前条件を書いておく

のどちらかをした方が良さそうです(個人的には後者が分かりやすいと思います)。

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +      assert(duration.to.isEqual(to.minusYears(1)))
一つ前のコメントと同じことが当てはまります

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +    "be generated unsuccessfully with illegal LocalDate" in {
```suggestion
    "not be generated with illegal LocalDate" in {
```

2022-02-27 06:22 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +    "after from and before to" should {
```suggestion
    "shortly after from" should {
```

になりそう

2022-02-27 06:48 UTC, Lucky3028 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +      assert(duration.to.isEqual(to))
（`dateFrom`は`LocalDate`なので`LocalTime`をもっていません...）

2022-02-27 22:02 UTC, kory33 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +      assert(duration.to.isEqual(to))
あー、すみません…とすると、

```
      require(/* t の時刻が4:10になっている */)
      require(/* tPlusOneYear の時刻が4:10になっている */)
      val duration = DateTimeDuration.fromLocalDate(t.toLocalDate, tPlusOneYear.toLocalDate)
      assert(duration.from.isEqual(t))
      assert(duration.to.isEqual(tPlusOneYear))
```

みたいになりそう…？ここでの問題点は、この `assert` が適当に持ってきた `t` / `tPlusOneYear` では成り立たないことにあるので、これら変数に関する事前条件が明確に書かれていれば大丈夫です

2022-02-28 00:14 UTC, Lucky3028 commented on src/test/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/domain/DateTimeDurationSpec.scala
> +      assert(duration.to.isEqual(to))
なるほど、ありがとうございます！

2022-02-28 03:32 UTC, Lucky3028 commented
直しました

2022-02-28 05:49 UTC, kory33 approved these changes
LGTM。ありがとうございます～

2022-02-28 05:49 UTC, merged