fix: avoid NPE when WorldConfiguration#useRegions is false
GiganticMinecraft/SeichiAssist pull request #1429
Opened 2022-03-21 03:58 UTC by KisaragiEffective

2022-03-21 04:01 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
> +        // this variable is nullable: WorldConfiguration#useRegions is false => null
この非自明な挙動はラッパーみたいなのに `Option` に解決させるべきではないかなと思います　常にnonnullをチェックすべきなものですし

2022-03-21 04:31 UTC, kory33 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.java
> +        return Option.apply(plugin.getRegionManager(world));
このファイルScalaにした方が良さそう…

2023-01-10 23:29 UTC, rito528 requested changes
コンパイルを通してください。

2023-01-10 23:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
> +            LeftClickButtonEffect.apply(TargetedEffect.emptyEffect)
`emptyEffect`をimportした上で、
```suggestion
            LeftClickButtonEffect(emptyEffect)
```
とすることができます。

2023-01-11 04:46 UTC, Lucky3028 commented
developブランチをリベース。

2023-01-11 05:36 UTC, rito528 requested changes

2023-01-11 05:36 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
> +            regionManager.getRegionCountOfPlayer(worldGuardPlugin.wrapPlayer(player))
270行目で直接プラグインを呼ばないようにしているので、これも同じように直接呼び出さないようにしたほうが良いと思います。

2023-01-11 05:36 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/SpawnRegionProjectileInterceptor.scala
> +      && getRegions(player.getLocation).map(_.getId).exists(spawnRegionNames.contains)
この条件はややこしいので、変数に切り出したほうが良いと思います。

2023-01-11 05:36 UTC, rito528 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.scala
> +    regions.headOption.filter(_ => regions.size == 1)
```suggestion
    if (regions.size == 1) Some(regions.headOption)
    else None
```
のほうが直感的だと思います。

2023-01-11 06:12 UTC, rito528 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.scala
> +  def wrapPlayer(player: Player): LocalPlayer = plugin.wrapPlayer(player)
ここの`wrapPlayer`関数は`private`になるようにして、`WorldGuardWrapper.scala`内の関数ではbukkitの`Player`を引数として受け取り処理をしたほうが良いと思います。

2023-01-11 06:19 UTC, rito528 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.scala
> +    getRegions(location).take(2).headOption
```suggestion
    val regions = getRegions(location)
    
    Option.when(regions.size == 1)(region.head)
```

2023-01-11 06:29 UTC, rito528 requested changes
otherwise LGTM.

2023-01-11 06:29 UTC, rito528 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.scala
> +      .getRegionCountOfPlayer(WorldGuardPlugin.inst().wrapPlayer(who))
```suggestion
      .getRegionCountOfPlayer(wrapPlayer(who))
```

2023-01-11 06:29 UTC, rito528 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.scala
> +    getOneRegion(location).exists(_.isOwner(plugin.wrapPlayer(player)))
```suggestion
    getOneRegion(location).exists(_.isOwner(wrapPlayer(player)))
```

2023-01-11 06:29 UTC, rito528 commented on src/main/scala/com/github/unchama/util/external/WorldGuardWrapper.scala
> +    getOneRegion(location).exists(_.isMember(plugin.wrapPlayer(player)))
```suggestion
    getOneRegion(location).exists(_.isMember(wrapPlayer(player)))
```

2023-01-11 06:35 UTC, rito528 commented
formatが通ればOK.

2023-01-11 15:09 UTC, Lucky3028 commented
@rito528 通りました

2023-01-11 15:12 UTC, rito528 approved these changes

2023-01-11 15:12 UTC, merged