Minestack内、色があるブロック（羊毛・テラコッタなど）について1種類だけを表示しておき、トグル等で全色を表示させるようにする(再)
GiganticMinecraft/SeichiAssist pull request #1450
Opened 2022-03-24 10:37 UTC by rito528

間違ってブランチを削除してしまい、Reopenできなくなってしまったので再度pull requestを出します。
issue #1228

2022-03-24 10:59 UTC, Lucky3028 commented
（close #... で自動的にissueを閉じられます）

2022-03-24 11:04 UTC, rito528 commented
なるほど、知りませんでした。
次から付けます。
ありがとうございます。

2022-03-24 11:21 UTC, KisaragiEffective requested changes
Pull Requestありがとうございます！以下レビューとなります。

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
nit:
MineStackのエントリなのにメニューの都合が出ているので改善の余地があります。具体的には
* まとめた変更を戻し、
* かつこれらのグルーピングを`MineStackButtons.scala`に持たせる
べきだと思います。

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +    canOpen: CanOpen[IO, CategorizedMineStackMenu]
nit:
```suggestion
    canOpenCategorizedMineStackMenu: IO CanOpen CategorizedMineStackMenu
```

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +                if (MineStackObjectList.minestacklisttoggle.keys.toList.contains(mineStackObj))
nit: この実装についてですが、もともとのアイデアは、「まとめられたボタンをクリックすると、各色が改めて表示されて、そこから取り出すことができる」というUIを意図していたように思いました。

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +      environment.canOpenCategorizedMineStackMenu
```suggestion
    import environment.canOpenCategorizedMineStackMenu
```

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +    }
IOの値を`unsafeRunSync`で得てから加工するよりも、`map`や`flatMap`を使用して加工してください。[`unsafeRunSync`は、理想的にはプログラムの最後尾で一度だけ呼ばれることが想定されています](https://github.com/typelevel/cats-effect/blob/series/2.1.x/core/shared/src/main/scala/cats/effect/IO.scala#L227-L244)が、このコードはそれに沿っていません。

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackMainMenu.scala
> +      canOpen: CanOpen[IO, CategorizedMineStackMenu]
nit:
```suggestion
      canOpenCategorizedMineStackMenu: IO CanOpen CategorizedMineStackMenu
```

2022-03-24 11:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +      emptyEffect
```suggestion
      TargetedEffect.emptyEffect
```

2022-03-24 11:27 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +                if (MineStackObjectList.minestacklisttoggle.keys.toList.contains(mineStackObj))
> まとめられたボタンをクリックすると、各色が改めて表示されて、そこから取り出すことができる

これですとUIが普通に崩れそうですし、下段にあったものを展開すると次のページに溢れる可能性があるため、メニューに「何が展開されているか」を持ち続ける必要があり実装が普通に複雑化する懸念があります

一段メニューが開いてもそんなにUX変わらないと思う（むしろ良い？）と思うので、このような方式で良いと思っているのですがいかがでしょうか？

2022-03-24 11:51 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
> まとめた変更を戻し、
これに関してですが、もともと格納されていたminestacklistbuildにブロックの内容を格納してしまうと、常にMineStackのMenu中に表示されてしまうので戻すべきではないような気がしますがどうでしょうか？(MineStackのGUIを実装し直す必要が出てきそうです)

2022-03-24 12:15 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
> MineStackのエントリなのにメニューの都合が出ている

「カテゴリ分け」というのが既にプラグインの仕様によるものですし、そのような情報が表(`MineStackObjectList.scala`)に出ているのは本質的に仕様によるものだとの認識があります。（つまり、そこまでUIの都合によるものかというとそうではないと思っています）

なので、そもそもここのMineStackのリストを `List[Either[MineStackObj, GroupedMineStackObj]]` にするで良いかなとは思いますね

2022-03-24 12:37 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
なるほど。
`List[Either[MineStackObj, GroupedMineStackObj]]`にすると毎回`Either[MineStackObj,MineStackObj]`と書き、Leftが同じものを大量に書くことになってしまいそうなんですが、なにか別の書き方があったりしますか....?
それとも解釈が間違っていますか...?

2022-03-24 12:40 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
あ、私の解釈が間違っていますね、GroupedMineStackObjを見落としていました。
GroupedMineStackObjはList[GruopedMineStackObj]という解釈で大丈夫でしょうか？

2022-03-24 12:43 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
> それとも解釈が間違っていますか...?
それで合ってます！

```Scala
private def leftElems[A](elems: A*): List[Either[A, Nothing]] = elems.toList.map(Left.apply)
private def rightElems[B](elems: B*): List[Either[Nothing, B]] = elems.toList.map(Right.apply)
```

としたうえで、

```Scala
val minestacklistbuild: List[Either[MineStackObj, GroupedMineStackObj]] = leftElems(
  ... // 普通のMineStackObj
) ++ rightElems(
  ... // GroupedMineStackObj達
) ++ leftElems(
  ...
) ...
```

みたいにすれば `Left` や `Right` をたくさん書かずに済みます。(MineStackオブジェクトたちの順番はあんまり変えたくないので、 `rightElems` と `leftElems` が交互に `++` を挟んで並ぶようになると思います)

2022-03-24 12:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
`Either`ではなく

```scala
sealed trait MineStackEntry

case class MineStackObj(/* 従前からあるパラメーター */) extends MineStackEntry

case class GroupedMineStackObj(topEntries: MineStackObj, subentries: Seq[MineStackObj]) extends MineStackEntry
```

のようにして、MineStackEntryに対する操作に切り替えるのがスマートではないでしょうか？

2022-03-24 12:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
> > それとも解釈が間違っていますか...?
> 
> それで合ってます！
> 
> ```scala
> private def leftElems[A](elems: A*): List[Either[A, Nothing]] = elems.toList.map(Left.apply)
> private def rightElems[B](elems: B*): List[Either[Nothing, B]] = elems.toList.map(Right.apply)
> ```
> 
> としたうえで、
> 
> ```scala
> val minestacklistbuild: List[Either[MineStackObj, GroupedMineStackObj]] = leftElems(
>   ... // 普通のMineStackObj
> ) ++ rightElems(
>   ... // GroupedMineStackObj達
> ) ++ leftElems(
>   ...
> ) ...
> ```
> 
> みたいにすれば `Left` や `Right` をたくさん書かずに済みます。(MineStackオブジェクトたちの順番はあんまり変えたくないので、 `rightElems` と `leftElems` が交互に `++` を挟んで並ぶようになると思います)

なるほど。
その方法で実装してみます。
ありがとうございます！

2022-03-24 13:15 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val minestacklisttoggle: Map[MineStackObj,List[MineStackObj]] = Map(
実装していて気がついたのですが、

> > それとも解釈が間違っていますか...?
> 
> それで合ってます！
> 
> ```scala
> private def leftElems[A](elems: A*): List[Either[A, Nothing]] = elems.toList.map(Left.apply)
> private def rightElems[B](elems: B*): List[Either[Nothing, B]] = elems.toList.map(Right.apply)
> ```
> 
> としたうえで、
> 
> ```scala
> val minestacklistbuild: List[Either[MineStackObj, GroupedMineStackObj]] = leftElems(
>   ... // 普通のMineStackObj
> ) ++ rightElems(
>   ... // GroupedMineStackObj達
> ) ++ leftElems(
>   ...
> ) ...
> ```
> 
> みたいにすれば `Left` や `Right` をたくさん書かずに済みます。(MineStackオブジェクトたちの順番はあんまり変えたくないので、 `rightElems` と `leftElems` が交互に `++` を挟んで並ぶようになると思います)

を使うと、どのアイテムでメニュー開くというのが埋め込めないような気がするのですがなにか対処法はあるのでしょうか...?

2022-03-24 13:45 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +    canOpen: CanOpen[IO, CategorizedMineStackMenu]
cc1b69855fb95f7742c6aae92a5e57cd4f3723f1にて修正を行いました！

2022-03-24 13:46 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +      environment.canOpenCategorizedMineStackMenu
1d482f0fc8bc6c58b15f1b0f1e346142163304e3 にて修正を行いました！

2022-03-24 13:46 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +    }
e1b4afd20ca824ff486529a3c1ec6c7e1ce60c57 にて修正を行いました！

2022-03-24 13:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackMainMenu.scala
> +      canOpen: CanOpen[IO, CategorizedMineStackMenu]
28e4c5224613fd099570aa3a122d9f6d76c4bfd7 にて修正を行いました！

2022-03-24 13:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +      emptyEffect
dc955e54ea67301aafd733d16ce77222053e0cf2 にて修正を行いました！

2022-03-24 14:24 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +                if (MineStackObjectList.minestacklisttoggle.keys.toList.contains(mineStackObj))
OKとのこと

2022-03-24 16:10 UTC, rito528 commented
Koryさんに見てもらった結果様々な箇所でリファクタリングが必要なことが判明しました。

2022-03-25 10:25 UTC, rito528 commented
修正を行いました。
再度レビューお願いいたしますm(_ _)m

2022-03-25 10:47 UTC, KisaragiEffective requested changes

2022-03-25 10:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +    }
いい方法を思いつかないんですが、とにかくここでは`unsafeRunSync`は必要ありません

2022-03-25 10:49 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +    }
レビューありがとうございます。
他のコードを読んでみて、他の方法を模索してみます...

2022-03-25 11:08 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +    }
修正を行いました。
こちらでいかがでしょうか...?

8a7cecc4051189970ca4ad90c1a903b1df19d59e

2022-03-25 11:26 UTC, KisaragiEffective reviewed
otherwise LGTM

2022-03-25 11:26 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +      mapping <- buttonMapping.map(_.sequence).sequence
`map(f).sequence == traverse(f)`です
```suggestion
      mapping <- buttonMapping.traverse(_.sequence)
```

2022-03-25 11:26 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +      mapping <- buttonMapping.map(_.sequence).sequence
:+1:

2022-03-25 11:26 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +    }
👍🏻

2022-03-25 11:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +      mapping <- buttonMapping.map(_.sequence).sequence
ありがとうございます！
修正しました！
6ff2959127a7a8c7387b225ae3f76a59792df398

2022-03-25 11:54 UTC, KisaragiEffective approved these changes
LGTM

2022-03-25 12:23 UTC, KisaragiEffective commented
ビルドが詰まっているので一度閉じて開き直します

2022-03-25 12:29 UTC, merged