ビルド時のwarnigの改善
GiganticMinecraft/SeichiAssist pull request #1456
Opened 2022-03-26 10:03 UTC by rito528

ビルド時のwarningの改善を行いました。
ただし、以下の部分は原因不明のため改善を行っていません。(もしかしたら抜けがあるかもしれませんが)
・BlockData(byte)取得時のwarn
・case classのデフォルト値が利用されていないというwarn
・実際には使われているが、使われていないと出るwarn
原因が分かる場合はアドバイスしていただけると大変助かります。

2022-04-20 18:30 UTC, kory33 requested changes

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/fs2/workaround/fs3/Fs3Topic.scala
>    // noinspection ScalaUnusedSymbol
```suggestion
```

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/buildassist/MenuInventoryData.scala
> +    skullmeta.setOwningPlayer(
https://github.com/GiganticMinecraft/SeichiAssist/blob/fdd279a33d11cc5d0d7f3e03ef3790f4117beef7/src/main/scala/com/github/unchama/itemstackbuilder/SkullItemStackBuilder.scala#L43-L45
のような事情があるので、コメント書いてもらってrevertする感じになりそうです

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/data/GachaSkullData.scala
> +          setOwningPlayer(
https://github.com/GiganticMinecraft/SeichiAssist/blob/fdd279a33d11cc5d0d7f3e03ef3790f4117beef7/src/main/scala/com/github/unchama/itemstackbuilder/SkullItemStackBuilder.scala#L43-L45
のような事情があるので、コメントと共にwarningを抑制してもらったほうがいいかも

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/fourdimensionalpocket/bukkit/commands/OpenPocketCommand.scala
> +                    .apply[SyncIO]
これは `OpenPocketCommand` が implicit 等で要求するのが望ましいです！(毎回DBの全レコードを読みに行くので)

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
> +          if (ManagedWorld.fromBukkitWorld(player.getWorld).exists(_.isSeichiSkillAllowed))
```Scala
import ManagedWorld._
```

したうえで

```suggestion
          if (player.getWorld.isSeichiSkillAllowed)
```

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerClickListener.scala
> +    if (!ManagedWorld.fromBukkitWorld(player.getWorld).exists(_.isSeichiSkillAllowed)) return
```Scala
import ManagedWorld._
```
したうえで

```suggestion
    if (!player.getWorld.isSeichiSkillAllowed) return
```

2022-04-20 18:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerClickListener.scala
> +    if (!ManagedWorld.fromBukkitWorld(player.getWorld).exists(_.isSeichiSkillAllowed)) return
```Scala
import ManagedWorld._
```
したうえで

```suggestion
    if (!player.getWorld.isSeichiSkillAllowed) return
```

2022-04-21 04:20 UTC, rito528 commented
修正しました。
レビューお願いします。

2022-04-21 05:15 UTC, kory33 approved these changes
ありがとうございます！！！

2022-04-21 05:15 UTC, merged