MineStackのリファクタリング
GiganticMinecraft/SeichiAssist pull request #1465
Opened 2022-03-30 08:31 UTC by rito528

2022-03-30 09:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
>      }
nit:
```suggestion
    MineStackObjectList.findByItemStack(itemstack, player.getName)
      .map(addToMineStackAfterLevelCheck)
      .getOrElse(false)
```

2022-03-30 09:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackUsageHistory.scala
> +  private var usageHistory: List[MineStackObj] = Nil
nit: これはVectorのほうが[よい](https://docs.scala-lang.org/ja/overviews/collections/concrete-immutable-collection-classes.html)です

2022-03-30 09:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +    player.getOpenInventory.getTopInventory.getName == s"§1§lMineStack(アイテム色選択)"
§直書きではなく`ChatColor`を使用してください

2022-03-30 11:07 UTC, rito528 commented
上記レビューについて、修正を行いました。

2022-04-16 12:24 UTC, rito528 commented
こちらのpull requestですが、#967 が含まれています。

2022-04-17 15:09 UTC, kory33 commented on docker/spigot/serverfiles/server.properties
> +server-ip=0.0.0.0
これは…？

2022-04-17 15:22 UTC, kory33 requested changes

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackObject.scala
> +  def getDurability: Short = itemStack.getDurability
```suggestion
  def material: Material = itemStack.getType

  def durability: Short = itemStack.getDurability
```

`get` は不要そう(uniform access principleによる)

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerClickListener.scala
>            // アイテムがスタックでき、かつ整地Lvがマインスタックの開放レベルに足りているとき...
コメントが古いです(コメント消してもいいかも)

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerPickupItemListener.scala
> +  SeichiAssist.seichiAssistConfig
```suggestion
```

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerClickListener.scala
> +    SeichiAssist
ここから193行目まで消して良いです

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackUsageHistory.scala
> +  private var usageHistory: Vector[MineStackObject] = Vector.empty
```suggestion
  private var _usageHistory: Vector[MineStackObject] = Vector.empty
```

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackUsageHistory.scala
> +  def getHistory: Vector[MineStackObject] = usageHistory
```suggestion
  def usageHistory: Vector[MineStackObject] = _usageHistory
```

(uniform access principleによる)

2022-04-17 15:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackObjectCategory.scala
> +    def category(): MineStackObjectCategory = mineStackObj.category
```suggestion
    def category: MineStackObjectCategory = mineStackObj.category
```

2022-04-18 12:00 UTC, rito528 commented
@kory33 
修正しました。
再レビューお願いします。

2022-04-18 12:30 UTC, kory33 commented
- `src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala`
 - `src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala`
 - `src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala`

だけちょっとレビュー時間かかりそうです～　それ以外はとりあえず大丈夫そう

2022-04-20 18:37 UTC, kory33 commented
`FirstPage.scala` も良さそう

2022-04-27 18:34 UTC, kory33 commented
@rito528 conflict修正お願いします！

2022-04-27 19:34 UTC, kory33 requested changes

2022-04-27 19:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +      case Right(_)           => Nil
これ捨てないで良さそう

2022-04-27 19:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
>    }
- `getAllMineStackObjects`
- `getAllRepresentativeMineStackObjects`
- `isRepresentativeMainStackObject`
- `getColoredVariantsMineStackObjectsByRepresentative`
- `getMineStackObjectExceptColoredVariants`

引き出しメニューを表示するために必要な情報は `List[Either[MineStackObject, GroupedMineStackObj]]` しかないので、この辺は全部一つのメソッドだけで済むと思います

2022-04-28 06:41 UTC, rito528 commented
修正しました。
レビューお願いします！

2022-07-09 12:56 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
>        .zipWithIndex
index を使っていないので `zipWithIndex` をしなくてもよい。

変更としては、

 - `.zipWithIndex` を削除
 - `.filter` の中の `_._1` を `_` に変更
 - `.map` の引数を `case (g, _) =>` から `g =>` に変更

2022-07-09 13:13 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackObject.scala
> +}
```suggestion
class MineStackObject(
  val mineStackObjectName: String,
  val uiName: Option[String],
  private val _itemStack: ItemStack,
  val hasNameLore: Boolean, // 多分記名があるかどうか
  val category: MineStackObjectCategory
) {

  def itemStack: ItemStack = _itemStack.clone()

  def material: Material = itemStack.getType

  def durability: Short = itemStack.getDurability

}
```

Bukkit の `ItemStack` は可変オブジェクトなので、クローンして返すべき

2022-07-09 13:14 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/MineStackObject.scala
> +  hasNameLore: Boolean, // 多分記名があるかどうか
```suggestion
  hasNameLore: Boolean, // 記名があるかどうか
```

2022-07-09 13:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/GroupedMineStackObj.scala
>  )
ドメイン制約として、「`coloredVariants` の中のオブジェクトのカテゴリーがすべて `representative` のそれと一致している」というのを設けてもいいと思います（ついでに `category` メソッドが well-defined になるのでこれも追加しちゃいましょう)

```Scala
) {
  require(coloredVariants.forall(_.category == representative.category))
  
  def category = representative.category
}
```

2022-07-09 13:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/minestack/GroupedMineStackObj.scala
>  case class GroupedMineStackObj(
```suggestion
case class GroupedMineStackObjects(
```

2022-07-09 13:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  def getAllMineStackObjects: List[MineStackObject] = {
ドキュメントに、「可変であるガチャ景品リストに依存しているため、定数ではない」旨を追記したほうが良い

2022-07-09 13:31 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
>    def getColoredVariantsMineStackObjectsByRepresentative(
このメソッドは要らない「はず」

2022-07-09 13:42 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  val allMineStackObjects: List[Either[MineStackObject, GroupedMineStackObj]] = List(
```suggestion
  val allMineStackGroups: List[Either[MineStackObject, GroupedMineStackObj]] = List(
```

2022-07-09 13:55 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
```suggestion

  type MineStackObjectGroup = Either[MineStackObject, GroupedMineStackObjects]

```
これ名前つけちゃいましょう

2022-07-09 14:04 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
>    override def computeMenuLayout(
```suggestion
  // FIXME: MineStackObjectList にこれがあってもいいかも
  private def getAllObjectGroupsInCategory: List[MineStackObjectGroup] = {
    def categoryOf(group: MineStackObjectGroup): MineStackObjectCategory = {
      group match {
        case Left(mineStackObject) => mineStackObject.category
        case Right(groupedObjects) => groupedObjects.category
      }
    }

    MineStackObjectList
      .getAllMineStackGroups
      .filter { group => categoryOf(group) == category }
  }

  override def computeMenuLayout(
```

2022-07-09 14:11 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
> +        } ++ getGachaPrizesList
```Scala
categoryGroupNumer <- IO {
  getAllObjectGroupsInCategory.length
}
```

2022-07-09 14:11 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
>        val totalNumberOfPages = Math.ceil(categoryItemList.size / 45.0).toInt
```suggestion
      val totalNumberOfPages = Math.ceil(categoryGroupCount / 45.0).toInt
```

2022-07-09 14:12 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
> +      } ++ getGachaPrizesList).filter(_.category == category)
```Scala
val categoryGroups = getAllObjectGroupsInCategory
```

2022-07-09 14:18 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +      ) && !isMineStackSelectItemColorMenu && !isMineStackMainMenu
この関数は要らなくなる「はず」。なぜなら、`CategorizedMineStackMenu` が表示するのは `MineStackObjectGroup` = `Either[MineStackObject, GroupedMineStackObjects]` なので、各 `CategorizedMineStackMenu` のボタンが `MineStackObject` に対応するのか `GroupedMineStackObjects` に対応するのかは最初から分かっているはずであり、もし `GroupedMineStackObjects` だった場合、どのようなアイテムが代表元(例えば白羊毛)でどのようなアイテム達がグルーピングされたもの(例えば黒羊毛や青羊毛)なのかという情報が `case class GroupedMineStackObjects` にすでに入っているはずなので。

2022-07-09 14:20 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +case class MineStackSelectItemColorMenu(mineStackObj: MineStackObject) extends Menu {
ここで
```suggestion
case class MineStackSelectItemColorMenu(group: GroupedMineStackObjects) extends Menu {
```
を受け取ってしまえば、 37行目から46行目までの検索はそもそも行う必要が無い。

2022-07-09 14:22 UTC, kory33 reviewed
Otherwise LGTM.

2022-07-17 16:46 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
>      val totalNumberOfPages = Math.ceil(categoryItemList.size / 45.0).toInt
`categoryItemList` ここでしか使ってないので、上と同じように `getAllObjectGroupsInCategory(category).length` を `IO` の中で取ってきていいかも

2022-07-17 16:49 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +  def getMineStackObjectItemStack(
```suggestion
  def getMineStackObjectIconItemStack(
```

2022-07-17 16:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +    isColorSelectMenu: Boolean
`Boolean` で関数の動作を変えるのは結構危ないかも(`getMineStackObjectItemStack` は何をする関数ですか、と聞かれた時に、 `isColorSelectMenu` が `true` の時と `false` の時で説明が変わると思うので、受け取るデータを変えるか、関数を分けるかのどちらかをした方が良いと思います)。

2022-07-17 16:52 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackSelectItemColorMenu.scala
> +          CategorizedMineStackMenu(group.category)
nits: これ元居たページに戻ったほうが使いやすかったりしませんか？

2022-07-17 16:54 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +    SequentialEffect(
```suggestion
    canOpenMineStackSelectItemColorMenu: IO CanOpen MineStackSelectItemColorMenu
  ): Kleisli[IO, Player, Unit] = {
    val playerData = SeichiAssist.playermap(getUniqueId)
    SequentialEffect(
```

2022-07-17 17:55 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
>    }
これって使われてますか？

2022-07-17 17:55 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/MineStackObjectList.scala
> +  }
`allMineStackGroups` を `.map(_.flatMap { ... })` すると手に入りそう

2022-07-17 17:55 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
> +    val categoryGroups = getAllObjectGroupsInCategory(category).unsafeRunSync()
これ `IO` を返す関数内なので `unsafeRunSync()` をしないでも良さそうです

2022-07-17 18:40 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
> +      categorizedItemSectionComputation <-
```suggestion
      categorizedItemSection <-
```

2022-07-17 18:40 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/CategorizedMineStackMenu.scala
> +          .++(categorizedItemSectionComputation)
```suggestion
          .++(categorizedItemSection)
```

2022-07-17 18:43 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +
```suggestion
```

2022-07-17 18:52 UTC, kory33 approved these changes

2022-07-17 18:57 UTC, merged