建築Lv100に到達した際に全体通知する
GiganticMinecraft/SeichiAssist pull request #1472
Opened 2022-04-17 01:09 UTC by rito528

close #1069

2022-04-17 15:32 UTC, kory33 requested changes

2022-04-17 15:32 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
>        SendMinecraftMessage[F, Player].string(player, s"${GOLD}最大Lvに到達したよ(`･ω･´)")
`SequentialEffect` 等を利用しないと最後のeffect以外実行されません

2022-04-18 12:16 UTC, rito528 commented
こちらも修正が完了しています（コメントを書くのを忘れていました）
お時間あるときにレビューお願いします。

2022-04-18 12:31 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +      )
ここが実行されてなさそうです

2022-04-19 13:27 UTC, rito528 commented
@kory33 
修正しました。
再レビューお願いします。

一応動くことは確認できましたが、SequentialEffectの実行方法があまり良くない気がするのでアドバイスしていただけると大変助かります。

2022-04-19 13:32 UTC, KisaragiEffective requested changes

2022-04-19 13:32 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +      F.pure {
```suggestion
      F.delay {
```

`sendMessageToEveryoneIgnoringPreference`は純粋ではありません

2022-04-19 13:38 UTC, kory33 requested changes

2022-04-19 13:38 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +      val bukkitPlayer = player.asInstanceOf[org.bukkit.entity.Player]
このレイヤ(`application` パッケージに置いていますが、より一般的にはApplication-logicやuse-caseの層とか言われます)では、「プレーヤーに対してどのような操作ができるかを仮定した上で、実際にどのような操作をどのような順番で行うかを制御する」ということを表現したいです。

そのような前提の下でいえば、実はここで `Player` が `org.bukkit.entity.Player` であると仮定するのは強すぎる仮定です(もうちょっと踏み込んだことを言えば、parametricityと呼ばれる、「多相関数はどのような型についても同じように動作する」という性質が `asInstanceOf` キャストをすることで失われてしまいます)。ところが、(お気づきかと思いますが)何も仮定が無い `Player` に対しては本当に何の操作もできないので、何かを仮定してあげる必要があります。

19行目の

```Scala
send: SendMinecraftMessage[F, Player]
```

はまさにこのためにあります。この宣言は「Playerという型に対しては、我々は `F` の文脈においてMinecraftのチャットメッセージを送ることができる」という、 `Player` 型と `F` 型に対して我々が置きたい仮定を記述しているのです。

ですから、「どのような操作を求めているか」をまずインターフェースに切り出して、それを呼び出すのみとするような実装にトライしてもらっても大丈夫でしょうか？（具体的にどうやればいいかわからない、という感じでしたら、もちろんもう少し踏み込んだ実装に関してもお話しできます！）

2022-04-19 13:38 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +        )
`pure` の中で副作用を発生させるべきではないです。

2022-04-19 13:45 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +      F.pure {
これはちょっと cats / cats-effect のレイヤの知識が要りますね
18行目で `F` に対して `Applicative` しか仮定していないのですが、 `Applicative` 型クラスのインスタンスは「任意の同期的な副作用である `() => A` を内包している」という仮定は置かれていない、より一般的なものですので、 `Sync` 型クラスまで要求してやる必要があります。

2022-04-19 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +      F.pure {
なるほど。
やってみます！

2022-04-19 13:52 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/LevelUpNotifier.scala
> +      val bukkitPlayer = player.asInstanceOf[org.bukkit.entity.Player]
とりあえずやってみて、ダメそうであればもう一度コメントで質問します。
レビューありがとうございます！

2022-04-20 17:04 UTC, kory33 requested changes

2022-04-20 17:04 UTC, kory33 commented on src/main/scala/com/github/unchama/minecraft/bukkit/actions/BroadcastBukkitSound.scala
> +    }
```suggestion
    BroadcastSoundEffect(sound, volume, pitch).run(())
```

2022-04-20 17:26 UTC, kory33 commented on src/main/scala/com/github/unchama/minecraft/bukkit/actions/BroadcastBukkitSound.scala
> +    }
```suggestion
    // FIXME: これでは何も実行されない。
    // 本来 `F` には `OnMinecraftServerThread` が必要で、
    // この関数は BroadcastBukkitMessage と同じように実装すべき。
    // ref. https://github.com/GiganticMinecraft/SeichiAssist/blob/fdd279a33d11cc5d0d7f3e03ef3790f4117beef7/src/main/scala/com/github/unchama/minecraft/bukkit/actions/BroadcastBukkitMessage.scala#L13-L16
    // 現在、これを利用しているbuildcountシステムの設計が微妙(incrementとnotifyが同時に行われてしまっている)なので、
    // そこを改善してからでないとこの書き換えができない。
    Sync[F].delay {
      BroadcastSoundEffect(sound, volume, pitch)
    }
```

2022-04-20 17:29 UTC, kory33 approved these changes
FIXMEが一個あるけど問題の根が深いのでとりあえずヨシ！ありがとうございます！

2022-04-20 18:00 UTC, kory33 approved these changes

2022-04-20 18:03 UTC, merged