整地量10億の倍数(10億、20億、30億、...)を突破した際に全体通知をする
GiganticMinecraft/SeichiAssist pull request #1473
Opened 2022-04-17 09:15 UTC by rito528

close #1070

2022-04-17 15:33 UTC, kory33 requested changes

2022-04-17 15:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +      BroadcastSoundEffect(Sound.ENTITY_ENDERDRAGON_DEATH, 1.0f, 1.2f)
実行されていないeffectです

2022-04-18 12:15 UTC, rito528 commented
こちらも修正が完了しています（コメントを書くのを忘れていました）
お時間あるときにレビューお願いします。

2022-04-18 12:34 UTC, kory33 requested changes

2022-04-18 12:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +    }
このイベントハンドラは整地量調整にのみ使いたい感じがあるので、
できれば(breakcountシステムに依存した)サブシステムにこの機能は切りたいところですね

2022-04-19 07:24 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +    }
なるほど...
できるかわかりませんがやってみます。

2022-04-22 20:35 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +            )(PlayerSendable.forString[IO])
どこかで `import PlayerSendable.forString` した方が良さそう

2022-04-22 21:16 UTC, kory33 requested changes

2022-04-22 21:16 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        Applicative[F].unit
```suggestion
```

2022-04-22 21:16 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        println(newBreakAmount.expAmount.amount)
```suggestion
```

2022-04-22 21:16 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/System.scala
> +      }
```suggestion
```
値が利用されてない純粋式です

2022-04-22 21:16 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notification/System.scala
> +            }
```suggestion
          case Left(Left((player, seichiAmountDiff))) =>
            action.ofSeichiAmountTo(player)(seichiAmountDiff)
          case Left(Right((player, seichiLevelDiff))) =>
            action.ofSeichiLevelTo(player)(seichiLevelDiff)
```

一つのパターンマッチにまとめられます

2022-04-22 21:17 UTC, kory33 commented
> (結果的にBukkitNotifyLevelUp.scalaというファイルに、10億の倍数到達時の通知を実装することになってしまいましたが、そうなるとファイル名とやってることが違うようになってしまう気がするのは気の所為でしょうか...?
※10億到達はレベルアップではないため)

正しそうですね　そしてBukkitNotifyLevelUpなのにdiffの展開とか、いつメッセージを出すかみたいなビジネスロジックも扱っちゃってるのは改善の余地もありそう(既存のコード含めて)

2022-04-22 23:44 UTC, rito528 commented
> > (結果的にBukkitNotifyLevelUp.scalaというファイルに、10億の倍数到達時の通知を実装することになってしまいましたが、そうなるとファイル名とやってることが違うようになってしまう気がするのは気の所為でしょうか...?
> > ※10億到達はレベルアップではないため)
> 
> ファイル名とやってることが違うというのは正しそうですね　そしてBukkitNotifyLevelUpなのにdiffの展開とか、いつメッセージを出すかみたいなビジネスロジックも扱っちゃってるのは改善の余地もありそう(既存のコード含めて)

なるほど、ただ既存のコードも含めて改善を行ってしまうとこのpull requestの手指からずれてしまうような気がするので、FIXMEコメントを残して置くこととします。

2022-04-23 05:16 UTC, rito528 commented
修正しました。
レビューお願いします。

2022-04-23 10:22 UTC, kory33 approved these changes
良さそう～～ 👍👍👍👍👍
ありがとうございます！

2022-04-23 10:22 UTC, merged

2022-04-23 10:23 UTC, kory33 commented
あ、マージした後に気付いたんですけどこれ10億の倍数じゃなくて10億での通知になってますね

2022-04-23 10:25 UTC, rito528 commented
> あ、マージした後に気付いたんですけどこれ10億の倍数じゃなくて10億での通知になってますね

気が付きませんでした....
修正します！