手掘りで掘ったアイテムもMinestackに収納されるようにする
GiganticMinecraft/SeichiAssist pull request #1474
Opened 2022-04-17 10:53 UTC by rito528

close #1440

2022-04-17 15:34 UTC, kory33 approved these changes

2022-04-17 15:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +      })
Minecraft詳しくないんですが、一つのBlockBreakEventから複数の種類のアイテムが出てきたりはしないんですか？(もししない場合それをコメントに明記するべきだと思います)

2022-04-17 20:55 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +      })
そうですね、チェストのようにインベントリスロットがあるアイテムに関しても、BlockBreakEventではチェストのみが判定の対象となる(中身のアイテムは必ずドロップする)のでコメントをつけるように修正します

2022-04-18 08:49 UTC, kory33 requested changes
となるとこんな感じですかね？

2022-04-18 08:49 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +     * チェスト等のインベントリスロットがあるアイテムに関しては、チェストのみが判定の対象となる。
```suggestion
     * チェスト等のインベントリスロットがあるブロック `b` を破壊したときは、
     * 破壊された `b` のみが `BlockBreakEvent` のドロップ対象となるため、
     * 中身のドロップがキャンセルされることは無い。
```

2022-04-18 12:02 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +     * チェスト等のインベントリスロットがあるアイテムに関しては、チェストのみが判定の対象となる。
なるほど....
修正します。

2022-04-18 12:05 UTC, rito528 commented
@kory33 
修正しました。
レビューお願いします。

2022-04-18 12:06 UTC, kory33 approved these changes
良さそうです～～～👍

2022-04-18 12:12 UTC, merged