buildcountシステムのincrementとnotifyを分離する
GiganticMinecraft/SeichiAssist pull request #1479
Opened 2022-04-21 18:04 UTC by rito528

close #1478

2022-04-27 23:20 UTC, kory33 commented
@rito528 conflict解消お願いします

2022-04-27 23:26 UTC, kory33 requested changes
Fs3Topicの中に入る型から `Option` を剥がしたいです

2022-04-27 23:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/IncrementBuildExpWhenBuiltByHand.scala
> +            dataTopic.publish1(Some((player, newData))).void
```suggestion
            dataTopic.publish1((player, newData)).void
```

2022-04-27 23:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/actions/IncrementBuildExpWhenBuiltByHand.scala
> +    dataTopic: Fs3Topic[G, Option[(Player, BuildAmountData)]]
```suggestion
    dataTopic: Fs3Topic[G, (Player, BuildAmountData)]
```

2022-04-27 23:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/System.scala
> +      buildCountTopic <- Fs3Topic[F, Option[(Player, BuildAmountData)]](None)
```suggestion
      buildCountTopic <- Fs3Topic[F, (Player, BuildAmountData)]
```

2022-04-27 23:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/System.scala
> +      buildCountTopic <- Fs3Topic[F, Option[(Player, BuildAmountData)]](None)
Fs3Topicの `apply` の引数を消す必要がありそう

2022-04-27 23:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/BuildAmountDataRepositoryDefinition.scala
> +    topic: Fs3Topic[F, Option[(Player, BuildAmountData)]],
```suggestion
    topic: Fs3Topic[F, (Player, BuildAmountData)],
```

2022-04-27 23:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/application/application/BuildAmountDataRepositoryDefinition.scala
> +          topic.publish1(Some(player, data)).void
```suggestion
          topic.publish1(player, data).void
```

2022-04-28 01:39 UTC, kory33 submitted a review, later dismissed

2022-04-28 01:48 UTC, rito528 commented
Salafmt等実行しました。

2022-04-28 02:34 UTC, kory33 approved these changes

2022-04-28 02:34 UTC, merged