レベルアップ報酬の配布通知をレベルごとに1回にする
GiganticMinecraft/SeichiAssist pull request #1482
Opened 2022-04-23 08:46 UTC by rito528

close #1048

2022-04-23 08:47 UTC, rito528 commented
これについてなんですが、レベルアップ記念としてガチャを回しました。というメッセージも連続で表示されるようになっているんですが、それも一緒に直しちゃいますか....?

2022-04-23 08:51 UTC, Lucky3028 commented
お願いします！

2022-04-23 08:52 UTC, rito528 commented
了解しました。

2022-04-23 10:20 UTC, kory33 requested changes

2022-04-23 10:20 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/System.scala
> +          player.sendMessage("レベルアップ記念としてガチャを回しました。")
- delayされていない副作用です
 - これ本当にガチャが回ってなくても表示されてしまうので、 `interpreter` のレイヤで制御するのが良さそうです

2022-04-23 10:20 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/GiftItemInterpreter.scala
> +    SequentialEffect(grantItemStacksEffect[F](itemStack))
```suggestion
    grantItemStacksEffect[F](itemStack)
```

2022-04-23 14:15 UTC, rito528 commented
修正しました。
レビューお願いします。
interpreterのレイヤで制御する方法が思いつかず、別の方法で実装することになってしまいましたが....

2022-04-23 15:26 UTC, kory33 commented
うーんこれどうするのがいいんでしょうねぇ

 - 複数の `GiftBundle` を纏められるようにして
 - `onLevelDiff` が各レベルでの `bundleAt` をそれぞれ `onBundle` に渡すように、ではなく、diffから一つの `GiftBundle` を纏めるようにして、それを一回だけ `onBundle` に渡すようにする
 - `onBundle` でメッセージを送ったりする

にするとかどうでしょうか？

2022-04-23 15:36 UTC, rito528 commented
これ難しいですね....
私自身がこのGiftシステムをうまく理解できていないような気がするので、Koryさんがおっしゃっていることをやろうとするとまずしっかり理解するところから始まりそうな気持ちですね

あとそもそもonBundle内でメッセージを送信するのはどうなんでしょう...?
そもそもGiftInsterpreter内で直接プレイヤー対する動作を行っていないので実装するべきではないのかなというふうに思ってしまいましたが....

2022-04-23 15:45 UTC, kory33 commented
> あとそもそもonBundle内でメッセージを送信するのはどうなんでしょう...?
GiftInsterpreter内で直接プレイヤー対する動作を行っていないので実装するべきではないのかなというふうに思ってしまいましたが....

この指摘は結構妥当だと思います。`GiftInterpreter` は今のところ「すべてが押し付けられている」use-caseなので、もっと何をやるのかを細分化してしまったほうがいいのではという気はします

2022-04-23 18:43 UTC, kory33 requested changes
とりあえずこの三つは修正が必要そうです

2022-04-23 18:43 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +import org.bukkit.entity.Player
`usecases` 層では `org.bukkit.Player` に言及したくないです

2022-04-23 18:43 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +    val giftItemInterpreter = new GiftItemInterpreter[F]
`GiftItemInterpreter` はbukkit特有の実装なので `usecases` で言及したくないです

2022-04-23 18:43 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +              action(gift).replicateA(i)
これは実行されてないです

2022-04-24 09:26 UTC, rito528 commented
修正しました。
レビューお願いします。

2022-04-27 00:57 UTC, kory33 requested changes

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/BukkitGiftItemInterpreter.scala
> +    }
```suggestion
    val itemStack = item match {
      case Item.GachaTicket  => GachaSkullData.gachaSkull
      case Item.SuperPickaxe => ItemData.getSuperPickaxe(1)
      case Item.GachaApple   => ItemData.getGachaApple(1)
      case Item.Elsa         => ItemData.getElsa(1)
    }

    grantItemStacksEffect[F](itemStack)
```

`Kleisli { x => k.run(x) }` は `k` と同じです

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/BukkitGiftItemInterpreter.scala
> +    }
```suggestion
    val itemStack = item match {
      case Item.GachaTicket  => GachaSkullData.gachaSkull
      case Item.SuperPickaxe => ItemData.getSuperPickaxe(1)
      case Item.GachaApple   => ItemData.getGachaApple(1)
      case Item.Elsa         => ItemData.getElsa(1)
    }

    grantItemStacksEffect[F](itemStack)
```

`Kleisli { x => k.run(x) }` は `k` と同じです

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +abstract class GiftItemInterpreter[F[_]: OnMinecraftServerThread: Sync]
```suggestion
abstract class GiftItemInterpreter[F[_]]
```
ここでは不要な仮定かも (実装する時に仮定すればいいので)

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +abstract class GiftItemInterpreter[F[_]: OnMinecraftServerThread: Sync]
```suggestion
abstract class GiftItemInterpreter[F[_]]
```
ここでは不要な仮定かも (実装する時に仮定すればいいので)

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +  override def apply(item: Gift.Item): Kleisli[F, Player, Unit]
この `override` 指定は不要そう

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +  override def apply(item: Gift.Item): Kleisli[F, Player, Unit]
この `override` 指定は不要そう

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftInterpreter.scala
> +    .toSet
```suggestion
```
未使用かも

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftInterpreter.scala
> +    .toSet
```suggestion
```
未使用かも

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +  def onGift(gift: Gift): Kleisli[F, Player, Unit]
domain 内で「プレーヤーにはGiftを付与できる」という制約を

```Scala
trait GrantLevelUpGift[F[_], Player] {
  def grant(gift: Gift): Kleisli[F, Player, Unit]
}
```

のように表現して、この usecase は

```Scala
class GrantGiftOnSeichiLevelDiff[F[_]: Sync, Player: SendMinecraftMessage[F, *]: GrantLevelUpGift[F, *]] {
  final def grantGiftTo(player: Player, onDiff: Diff[SeichiLevel]): F[Unit] = ...
}
```

のように定義した方が綺麗かも？(usecaseは単にclassであって欲しい気持ちがあります　どこまでが「Player に対する仮定」で、どこからが「その仮定とドメイン概念を使ったロジック」なのかを分けたいので)

2022-04-27 00:57 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +  def onGift(gift: Gift): Kleisli[F, Player, Unit]
usecase に trait を置くよりも、 domain 内で「プレーヤーにはGiftを付与できる」という制約を

```Scala
trait GrantLevelUpGift[F[_], Player] {
  def grant(gift: Gift): Kleisli[F, Player, Unit]
}
```

のように表現してあげて、この usecase は

```Scala
class GrantGiftOnSeichiLevelDiff[F[_]: Sync, Player: SendMinecraftMessage[F, *]: GrantLevelUpGift[F, *]] {
  final def grantGiftTo(player: Player, onDiff: Diff[SeichiLevel]): F[Unit] = ...
}
```

のように定義した方が綺麗かも？(usecaseは単にclassであって欲しい気持ちがあります　どこまでが「Player に対する仮定」で、どこからが「その仮定とドメイン概念を使ったロジック」なのかを分けたいので)

2022-04-27 00:58 UTC, kory33 commented
なんかGitHubが狂って二重にコメントついてしまった

2022-04-27 12:37 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +abstract class GiftItemInterpreter[F[_]: OnMinecraftServerThread: Sync]
その仮定を削除してしまうと、返り値が`Kleisli[Nothing, Player, Unit]`になってしまうので必要な気がするのですがどうでしょう？

2022-04-27 14:40 UTC, rito528 commented
https://github.com/GiganticMinecraft/SeichiAssist/pull/1482#discussion_r859283340
これ以外をとりあえず直しました。
上記件について対処法があれば教えていただけると大変助かります。

2022-04-27 16:44 UTC, kory33 requested changes

2022-04-27 16:44 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +abstract class GiftItemInterpreter[F[_]: OnMinecraftServerThread: Sync]
> その仮定を削除してしまうと、返り値が`Kleisli[Nothing, Player, Unit]`になってしまう

これよくわからなかったです、 `abstract class` のレイヤでは `F` が `: Sync` だったりする仮定は要らないはずです (これを実装する子クラスの方で `F[_]: OneMinecraftServerThread: Sync` 等とすれば良いはず)

2022-04-27 16:44 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/domain/GiftItemInterpreter.scala
> +
```suggestion
```

これがそもそも不要そうです、 関数を `extends` してるので

2022-04-27 16:44 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +  final def grantGiftTo(levelDiff: Diff[SeichiLevel], player: Player)(
```suggestion
object GrantGiftOnSeichiLevelDiff {

  import cats.implicits._

  def grantGiftTo[F[_], Player](levelDiff: Diff[SeichiLevel], player: Player)(
```

としてよさそう、わざわざ `new` する意味があんまり無さそう

2022-04-27 16:44 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/System.scala
> +    grant: GrantLevelUpGift[F, Player]
```suggestion
```

これを `System` が要求する必要は無さそう、 `GrantLevelUpGift` の実装はこの `System` が内部的に提供すべきです

2022-04-27 16:44 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
> +import com.github.unchama.seichiassist.subsystems.seichilevelupgift.bukkit.BukkitGrantLevelUpGift.apply
これ要らなさそう…？

2022-04-27 16:45 UTC, kory33 commented
(あと、GiftItemInterpreterがconflictしてます)

2022-04-27 22:47 UTC, rito528 commented
>>その仮定を削除してしまうと、返り値がKleisli[Nothing, Player, Unit]になってしまう

> これよくわからなかったです、 abstract class のレイヤでは F が : Sync だったりする仮定は要らないはずです (これを実装す る子クラスの方で F[_]: OneMinecraftServerThread: Sync 等とすれば良いはず)

あ～～～なるほど、理解できました！
ありがとうございます！！！

2022-04-27 23:02 UTC, rito528 commented
修正しました！
レビューお願いします！

2022-04-27 23:09 UTC, kory33 requested changes

2022-04-27 23:09 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/BukkitGiftItemInterpreter.scala
> +class BukkitGiftItemInterpreter[F[_]: OnMinecraftServerThread: Sync]
```suggestion
class BukkitGiftItemInterpreter[F[_]: OnMinecraftServerThread]
```

2022-04-27 23:09 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/BukkitGrantLevelUpGift.scala
> +class BukkitGrantLevelUpGift[F[_]: Async: OnMinecraftServerThread]
```suggestion
class BukkitGrantLevelUpGift[F[_]: Sync: OnMinecraftServerThread]
```

2022-04-27 23:09 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/usecases/GrantGiftOnSeichiLevelDiff.scala
> +      .map { level => GiftBundleTable.bundleAt(level) }
```suggestion
    val giftBundles = HasSuccessor[SeichiLevel]
      .leftOpenRightClosedRange(levelDiff.left, levelDiff.right)
      .toList
      .map { level => GiftBundleTable.bundleAt(level) }

    val giftBundle = giftBundles.fold(GiftBundle.empty)(_ combine _)
```

として、 `GiftBundle` に `traverseGifts` みたいなのを追加して `.map.toList.traverse` をここに書かないでいいようにしたいですね

2022-04-28 01:01 UTC, kory33 approved these changes
LGTM👍 

ありがとうございます！！！

2022-04-28 01:05 UTC, merged