SeichiAssistリリース時にReleasesにjarを吐き出すように
GiganticMinecraft/SeichiAssist pull request #1518
Opened 2022-06-11 17:10 UTC by rito528

2022-06-12 11:54 UTC, Lucky3028 requested changes

2022-06-12 11:54 UTC, Lucky3028 commented on .github/workflows/create_new_release.yml
> +      - uses: actions/setup-java@v2
これ[v3](https://github.com/actions/setup-java/releases/tag/v3.3.0)ではないのにはなにか理由があります？

2022-06-12 11:54 UTC, Lucky3028 commented on .github/workflows/create_new_release.yml
> +          prerelease: false
これを`false`にした理由はなにかありますか？（別にどっちでもいいといえばいいんですけど一応）

2022-06-12 13:14 UTC, rito528 commented on .github/workflows/create_new_release.yml
> +      - uses: actions/setup-java@v2
これは単純に最新バージョンを見てなかっただけです。
修正します。

2022-06-12 13:15 UTC, rito528 commented on .github/workflows/create_new_release.yml
> +          prerelease: false
これは
https://discord.com/channels/237758724121427969/959299646725951580/984046089193807872
というのがあったのでfalseにしました

2022-06-12 13:16 UTC, Lucky3028 commented on .github/workflows/create_new_release.yml
> +          prerelease: false
了解です！

2022-06-12 13:17 UTC, Lucky3028 commented
そういやこれキャッシュ効かせなくていいんですか？

2022-06-12 13:19 UTC, rito528 commented
どうなんでしょう...?
頻繁にリリースされるわけじゃないのでなくてもいい気がしますが...

2022-06-12 13:21 UTC, Lucky3028 commented
あーまあ確かにそうですね

2022-06-12 13:21 UTC, Lucky3028 approved these changes

2022-07-09 12:49 UTC, kory33 approved these changes

2022-07-09 12:49 UTC, merged