ShareInventoryの再実装
GiganticMinecraft/SeichiAssist pull request #1574
Opened 2022-07-21 14:27 UTC by rito528

ShareInventoryを再実装しました。

2022-07-21 15:43 UTC, KisaragiEffective requested changes

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/ShareInventoryPersistence.scala
> +  def loadSerializedShareInventory(targetUuid: UUID): F[InventoryContents]
```suggestion
  def loadSerializedShareInventory(targetUuid: UUID): F[Option[InventoryContents]]
```

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/bukkit/command/ShareInventoryCommand.scala
> +  }
```suggestion
    itemStackOption.foreach(InventoryOperations.dropItem(to, _))
  }
```

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/bukkit/command/ShareInventoryCommand.scala
> +        .foreach(itemStack => dropIfNotEmpty(Some(itemStack), player))
nit
```suggestion
        .foreach(dropIfNotEmpty(Some(_), player))
```

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/ShareInventoryAPI.scala
> +trait ShareInventoryWriteAPI[F[_]] {
```suggestion
trait SharedInventoryWriteAPI[F[_]] {
```

「共有インベントリ」なので、「共有された」→ `Shared...`のほうが適切です。以下同様。

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/bukkit/command/ShareInventoryCommand.scala
> +      playerData.contentsPresentInSharedInventory = false
タスクを増やすようで申し訳ありませんが、せっかくsubsystemを切るならばこのフラグもサブシステム側に役割を移譲したほうが良いと思います。

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/ShareInventoryPersistence.scala
> +  def saveSerializedShareInventory(
```suggestion
  def save(
```

`Serialized`...メモリ上にデータが存在しているので矛盾しています
`ShareInventory`...nit: 自明なので省略してもよいのでは？ (以下、このファイル内では同様)

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcShareInventoryPersistence.scala
> +        sql"UPDATE playerdata SET shareinv = '$serializedInventory' WHERE uuid = '${targetUuid.toString}'"
```suggestion
        sql"UPDATE playerdata SET shareinv = '$serializedInventory' WHERE uuid = ${targetUuid.toString}"
```

クォートは要りません

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcShareInventoryPersistence.scala
> +      sql"UPDATE playerdata SET shareinv = '' WHERE uuid = '${targetUuid.toString}'"
これは完全に削除したことになっていません。すなわち、次に同じUUIDの取得がリクエストされたとき、空の文字列がbase64として空文字列へデコードされたあと、BukkitObjectInputStreamがデシリアライズできずに例外を吐きます。
SQLの`DELETE`文を発行することを検討してください。そうすることで、完全に削除されることが担保されます。

2022-07-21 15:43 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/bukkit/command/ShareInventoryCommand.scala
> +    if (inventoryContents.isEmpty) return IO(MessageEffect(s"$RESET$RED${BOLD}収納アイテムが存在しません。"))
```suggestion
    if (inventoryContents.isEmpty) return IO.pure(MessageEffect(s"$RESET$RED${BOLD}収納アイテムが存在しません。"))
```

ここで返されるIOはその計算結果の中に副作用を一切含まないのでpureメソッドを使うことができます。これによってパフォーマンスが向上することが期待されます。

2022-07-21 15:44 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcShareInventoryPersistence.scala
> +            .head
```suggestion
            .single
            .apply()
```

これは複数存在するべきではないのでsingleメソッドを使っても安全な場面です
http://scalikejdbc.org/documentation/operations.html

2022-07-22 00:21 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/bukkit/command/ShareInventoryCommand.scala
> +        .foreach(itemStack => dropIfNotEmpty(Some(itemStack), player))
https://gyazo.com/f5de4bf2da1f7f14928f3825d06cb3ec
画像のように型が違うと言われるのでこれはできないような気がします?(なぜなんでしょう...)

2022-07-22 00:37 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcShareInventoryPersistence.scala
> +      sql"UPDATE playerdata SET shareinv = '' WHERE uuid = '${targetUuid.toString}'"
DELETE文を使用すると最低でもカラムごと消えるはずです。
なのでこれは正しいような気がします。(NULLにしてもいい気がしますが)

2022-07-22 08:59 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +  override def write(key: UUID, value: SharedFlag): F[Unit] = Sync[F].pure(())
ここの処理なんですが、いい感じの処理が思いつかないのでアドバイスいただけると大変助かります...
`read`、`write`はどこでも呼び出されません(DB上にフラグを管理しないので)が、`SharedInventoryPersistence`をoverrideしている影響で`read`、`write`を定義しないといけなくなっています。

2022-07-22 09:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcShareInventoryPersistence.scala
> +      sql"UPDATE playerdata SET shareinv = '' WHERE uuid = '${targetUuid.toString}'"
カラムが消えるのはDROP COLUMNです。DELETEはレコードを消します。

2022-07-22 09:42 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/bukkit/command/ShareInventoryCommand.scala
> +        .foreach(itemStack => dropIfNotEmpty(Some(itemStack), player))
すみません、どうもeta-expansionとして扱われているようです。どういうことかというと、
```scala
.foreach(dropIfNotEmpty(a => Some(a), player))
```

として扱われているようです。したがって、このsuggestionについては見なかったことにしていただけると幸いです。

2022-07-22 09:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
> +import com.github.unchama.seichiassist.subsystems.shareinventory.SharedInventoryAPI
```suggestion
import com.github.unchama.seichiassist.subsystems.sharedinventory.SharedInventoryAPI
```


以下同様

2022-07-22 09:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
>      import environment._
```suggestion
    import environment._
    val computations = ButtonComputations(player)
    import computations._
```

`import environment`で変数の型のメンバーを現在のスコープに持ち込めるので、明示的な`implicit`への引数渡しは必要なくなります

2022-07-22 09:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/SharedInventoryAPI.scala
> +  def setNotSharing(player: Player): F[Unit]
```suggestion
```

現在共有インベントリになにか入っているかどうかというのは、`save`と`clear`が内部的に触っているDBのレコードの値によって自動的に決まります。つまり、APIとしてこれらの内部的なステートの更新を露出するべきではありません。

2022-07-22 09:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +          case None => None
```suggestion
        serializedInventoryOpt.map(serializedInventory => {
          InventoryContents(
            ItemListSerialization.deserializeFromBase64(serializedInventory).asScala.toList
          )
        })

```

2022-07-22 09:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +  override def write(key: UUID, value: SharedFlag): F[Unit] = Sync[F].pure(())
これSharedFlagに関するRepositoryではなく、InventoryContentsに関するRepositoryではないでしょうか？InventoryContentsにRepositoryの型を変えたあと、`getFlag: F[SharedFlag]`を生やすべきだと思います。

2022-07-22 09:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/SharedInventoryPersistence.scala
> +trait SharedInventoryPersistence[F[_]] extends RefDict[F, UUID, SharedFlag] {
```suggestion
trait SharedInventoryPersistence[F[_]] extends RefDict[F, UUID, InventoryContents] {
```

2022-07-22 12:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +  override def write(key: UUID, value: SharedFlag): F[Unit] = Sync[F].pure(())
なるほど、ありがとうございます！

2022-07-23 04:43 UTC, rito528 commented
修正しました。再レビューお願いします。

2022-07-23 05:13 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/sharedinventory/domain/bukkit/InventoryContents.scala
> +}
catsのNomEmptyListを使うべきです

2022-07-23 05:13 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/sharedinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +      sql"UPDATE playerdata SET shareinv = NULL WHERE uuid = '${targetUuid.toString}'"
```suggestion
      sql"UPDATE playerdata SET shareinv = NULL WHERE uuid = ${targetUuid.toString}"
```

scalikejdbcが自動で処理するのでクォートは要りません (以下同様)

2022-07-23 05:13 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/sharedinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +        sql"SELECT shareinv FROM playerdata WHERE uuid = '${targetUuid.toString}'"
```suggestion
        sql"SELECT shareinv FROM playerdata WHERE uuid = ${targetUuid.toString}"
```

2022-07-23 05:13 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/sharedinventory/infrastracture/JdbcSharedInventoryPersistence.scala
> +        sql"UPDATE playerdata SET shareinv = $serializedInventory WHERE uuid = '${targetUuid.toString}'"
```suggestion
        sql"UPDATE playerdata SET shareinv = $serializedInventory WHERE uuid = ${targetUuid.toString}"
```

2022-07-23 05:13 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/SharedInventoryPersistence.scala
> -package com.github.unchama.seichiassist.subsystems.shareinventory.domain
nit: `git mv`で履歴を保持したまま移動することができます

2022-07-23 05:27 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/SharedInventoryPersistence.scala
> -package com.github.unchama.seichiassist.subsystems.shareinventory.domain
なるほど
IDEでパッケージ名を変更すると、パッケージ名が書かれているコードすべてを自動で変更してくれますが、`git mv`でも同じように変更されるということですか...?

2022-07-23 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/SharedInventoryPersistence.scala
> -package com.github.unchama.seichiassist.subsystems.shareinventory.domain
`git mv`は履歴を保ったまま移動するだけで、各言語のモジュール参照の書き換えは行いません

2022-07-23 05:32 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/shareinventory/domain/SharedInventoryPersistence.scala
> -package com.github.unchama.seichiassist.subsystems.shareinventory.domain
なるほど、もう少し詳しく調べてみます。

2022-07-23 05:32 UTC, rito528 commented
修正しました。再レビューお願いします。

2022-07-23 05:50 UTC, KisaragiEffective reviewed
見た

2022-07-23 05:50 UTC, KisaragiEffective approved these changes
LGTM

2022-07-23 06:00 UTC, merged