投票機能/投票妖精 機能の再実装
GiganticMinecraft/SeichiAssist pull request #1582
Opened 2022-07-29 05:31 UTC by rito528

投票機能/投票妖精の機能を再実装しました。

2022-07-29 14:09 UTC, KisaragiEffective requested changes

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/FairySpeech.scala
> +    }).toIO.unsafeRunSync()
純粋性が失われているので作用について操作することを検討してください。

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairyEndTime.scala
> +case class FairyEndTime(endTimeOpt: Option[LocalDateTime])
```suggestion
case class FairyEndTime(endTimeOpt: LocalDateTime)
```

妖精を召喚した時点で終わりの時間は自ずと確定するのでOptionである必要性はありません

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/infrastructure/JdbcFairyPersistence.scala
> +      dateOpt.map { date => FairyEndTime(Some(date)) }
```suggestion
      dateOpt.map { FairyEndTime(Some(_)) }
```

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/infrastructure/JdbcFairyPersistence.scala
> +      AppleAmount(appleAmountOpt.get)
例外が発生する危険性があり危険です。

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/infrastructure/JdbcFairyPersistence.scala
> +  override def appleAteByFairy(uuid: UUID): F[AppleAmount] = Sync[F].delay {
```suggestion
  override def appleAteByFairy(uuid: UUID): F[Option[AppleAmount]] = Sync[F].delay {
```

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/infrastructure/JdbcFairyPersistence.scala
> +        .get
```suggestion
```

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/infrastructure/JdbcFairyPersistence.scala
> +  override def appleAteByFairyMyRanking(uuid: UUID): F[AppleAteByFairyRank] = Sync[F].delay {
```suggestion
  override def appleAteByFairyMyRanking(uuid: UUID): F[Option[AppleAteByFairyRank]] = Sync[F].delay {
```

2022-07-29 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/service/FairySpeechService.scala
> +      gateway.sendMessage(fairyMessage)
```suggestion
    gateway.sendMessage(fairyMessage) >> Sync[F].whenA(fairyPlaySound == FairyPlaySound.on)(gateway.playSpeechSound)
```

2022-07-30 06:49 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/infrastructure/JdbcVotePersistence.scala
> +           | CASE WHEN DATEDIFF(last_vote, NOW()) <= ${-chainVoteAllowableWidth - 1}
SQLの`DATEDIFF()`で最終投票時間から今の時間を差し引いた日数分が返ってくるので、`DATEDIFF()`から帰ってくる数字は負の数字になります。
参考: https://dev.mysql.com/doc/refman/5.6/ja/date-and-time-functions.html#function_datediff

2022-07-30 07:06 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +trait VoteWriteAPI[F[_]] {
Repositoryごとに分けるとはどのようにですか...?

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +class BukkitRecoveryMana[F[_]: ConcurrentEffect: Applicative, G[_]: ContextCoercion[*[_], F]](
```suggestion
class BukkitRecoveryMana[F[_]: ConcurrentEffect, G[_]: ContextCoercion[*[_], F]](
```

`ConcurrentEffect`は`MonadError`を満たすので`Applicative`は冗長です

参考:
[![cats typeclass hierarchy](https://cdn.jsdelivr.net/gh/tpolecat/cats-infographic@master/cats.svg)](https://typelevel.org/cats/typeclasses.html)

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +  private lazy val playerdata = SeichiAssist.playermap(uuid)
```suggestion
  private val uuid: UUID = player.getUniqueId
  private val playerdata = SeichiAssist.playermap(uuid)
```

遅延しなくても良いと思います。

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +            ).apply(player)
`MessageEffect`の代わりに`MessageEffectF`を使うことで作用の型が`IO`から`F`になり、`LiftIO`が不要になります。

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +    val isManaExistsSeventyFivePercent = oldManaAmount.ratioToCap.exists(_ >= 0.75)
```suggestion
    val isEnoughMana = oldManaAmount.ratioToCap.exists(_ >= 0.75)
```

ローカル変数なので実装詳細を説明するほどの具象的な名前をつける必要はありません

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +    }
```suggestion
    } else if (mineStackedGachaRingoAmount > appleConsumptionAmount)
        appleConsumptionAmount
    else mineStackedGachaRingoAmount
```

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +    }
scalafmtによって追加されたカッコでなければ外して良いと思います

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +          }
202-206行目と同様

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +        }
ここも`if-elseif-else`にできます

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +       else 0)
```suggestion
    val randomizedAdd = if (reflectedMineStackedAmount >= 50)
      Random.nextInt(reflectedMineStackedAmount / 50)
    else 0
    
    (reflectedMineStackedAmount - reflectedMineStackedAmount / 100) + randomizedAdd
```

2022-07-30 16:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +    val reflectedMineStackedAmount =
```suggestion
    val mineStackBasedRegenValue =
```

nit: `MineStacked`は疑問の余地がある一般的ではない命名です

2022-07-31 06:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairyPlaySound.scala
> +object FairyPlaySound {
なぜですか...?

2022-07-31 06:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairyEndTime.scala
> +case class FairyEndTime(endTimeOpt: Option[LocalDateTime])
これ、そうなんですが、もともとの実装でSQL上に`VARCHAR`型で時間を文字列保存していたので、今回の再実装で`DATETIME`型に変更して、もともとの値をNULLに置き換えたのでOptionじゃないとエラーになると思います。

2022-07-31 06:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/infrastructure/JdbcFairyPersistence.scala
> +      dateOpt.map { date => FairyEndTime(Some(date)) }
これ、なぜかわかりませんがエラーになるのでできませんね....

2022-07-31 08:02 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairySummonCost.scala
> +case class FairySummonCost(value: Int) {
これもなぜですか...?

2022-07-31 08:05 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairyPlaySound.scala
> +object FairyPlaySound {
現在は再生する・しないの二択しか取り得ないためです。私はDo (not) ならBooleanで良いと考えています。

2022-07-31 08:07 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairyPlaySound.scala
> +object FairyPlaySound {
なるほど、納得しました。
ありがとうございます。

2022-07-31 08:26 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +trait VoteWriteAPI[F[_]] {
自己解決しました。

2022-07-31 09:07 UTC, rito528 commented
コメントを書いたところ以外はすべて修正しました。

2022-08-19 15:03 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/infrastructure/JdbcVotePersistence.scala
> +           | CASE WHEN DATEDIFF(last_vote, NOW()) <= ${-chainVoteAllowableWidth - 1}
了解しました。

2022-10-20 12:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/player/PlayerData.scala
> +  // TODO: Achievementシステムが再実装させたら速攻でこれを消すべき
typo?
```suggestion
  // TODO: Achievementシステムが再実装されたら速攻でこれを消すべき
```

2022-10-20 12:21 UTC, KisaragiEffective commented
@rito528 コンフリクトを解消してください

2022-10-21 14:03 UTC, rito528 reviewed
セルフレビュー

2022-10-23 10:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/FairySpeech.scala
> +    }
無理っぽい

2022-11-11 10:28 UTC, KisaragiEffective requested changes

2022-11-11 10:28 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> +	vote_number INT,
TABとSPACEを混ぜないでください

2022-11-11 10:28 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> +	last_vote DATETIME
`NOT NULL`

2022-11-11 10:28 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> +CREATE TABLE vote(
`IF NOT EXISTS`

2022-11-11 10:28 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> +	DROP lastvote;
`IF EXISTS`

2022-11-11 10:28 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> +	CONVERT(lastvote, DATE)
このカラムはカンマ区切りだったはずなので`CONVERT`はおそらく成功しません

2022-12-06 07:18 UTC, rito528 commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> +	CONVERT(lastvote, DATE)
https://github.com/GiganticMinecraft/SeichiAssist/blob/d705e1b5f090ba9dbe143e4675e977a5d00d4188/src/main/scala/com/github/unchama/seichiassist/database/manipulators/PlayerDataManipulator.scala#L103-L112

を見るとカンマ区切りではないようなので問題なさそうですね

2022-12-06 08:04 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Move_vote_column.sql
> + DROP IF EXISTS lastvote;
nit:
```suggestion
 DROP IF EXISTS lastvote;

```

2022-12-06 08:10 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/VoteMenu.scala
> +      val playSoundOffLore = List(s"$RESET${RED}現在音が鳴らない設定になっています。") ++ description
```suggestion
      val playSoundOnLore = s"$RESET${GREEN}現在音が鳴る設定になっています。" +: description
      val playSoundOffLore = s"$RESET${RED}現在音が鳴らない設定になっています。" +: description
```

2022-12-06 08:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +   * effectPointを返す作用
```suggestion
   * @return effectPointを返す作用
```

2022-12-06 08:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +   * 連続投票日数を返す作用
```suggestion
   * @return 連続投票日数を返す作用
```

2022-12-06 08:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +   * 投票回数を返す作用
```suggestion
   * @return 投票回数を返す作用
```

2022-12-06 08:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +   * effectPointを減少させる作用
```suggestion
   * @return effectPointを減少させる作用
```

2022-12-06 08:15 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/bukkit/actions/BukkitReceiveVoteBenefits.scala
> +      ) // 受け取ってない分を受け取ったことにする
nit:
```suggestion
      // 受け取ってない分を受け取ったことにする
      _ <- votePersistence.increaseVoteBenefits(
        uuid,
        notReceivedBenefits
      )
```

2022-12-06 08:16 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/bukkit/actions/BukkitReceiveVoteBenefits.scala
> +      notReceivedBenefits = VoteBenefit(voteCounter.value - receivedVote.value)
```suggestion
      pendingCount = VoteBenefit(voteCounter.value - receivedVote.value)
```

2022-12-06 08:16 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/bukkit/actions/BukkitReceiveVoteBenefits.scala
> +      voteCounter <- votePersistence.voteCounter(uuid)
```suggestion
      totalVote <- votePersistence.voteCounter(uuid)
```

2022-12-06 08:17 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +  def voteCounter(uuid: UUID): F[VoteCounter]
```suggestion
  def count(uuid: UUID): F[VoteCounter]
```

2022-12-06 08:18 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/VoteAPI.scala
> +  def chainVoteDayNumber(uuid: UUID): F[ChainVoteDayNumber]
```suggestion
  def currentConsecutiveVoteStreakDays(uuid: UUID): F[ChainVoteDayNumber]
```

2022-12-06 08:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/bukkit/actions/BukkitReceiveVoteBenefits.scala
> +      gachaSkulls = Seq.fill(10 * notReceivedBenefits.value)(
```suggestion
      gachaTicketAmount = Seq.fill(10 * notReceivedBenefits.value)(
```

2022-12-06 08:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/bukkit/actions/BukkitReceiveVoteBenefits.scala
> +      elseVoteBenefits = Seq.fill(notReceivedBenefits.value)(
```suggestion
      additionalVoteBenefit = Seq.fill(notReceivedBenefits.value)(
```

2022-12-06 08:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VotePersistence.scala
> +  def voteCounterIncrement(playerName: PlayerName): F[Unit]
```suggestion
  def incrementVoteCount(playerName: PlayerName): F[Unit]
```

2022-12-06 08:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VotePersistence.scala
> +  def voteCounter(uuid: UUID): F[VoteCounter]
```suggestion
  def currentVoteCount(uuid: UUID): F[VoteCounter]
```

2022-12-06 08:22 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VotePersistence.scala
> +  def updateChainVote(playerName: PlayerName): F[Unit]
```suggestion
  def updateConsecutiveVoteStreak(playerName: PlayerName): F[Unit]
```

2022-12-06 08:23 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VotePersistence.scala
> +  def chainVoteDays(uuid: UUID): F[ChainVoteDayNumber]
```suggestion
  def currentConsecutiveVoteStreakDay(uuid: UUID): F[ChainVoteDayNumber]
```

2022-12-06 08:24 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VoteCounter.scala
> +case class VoteCounter(value: Int) {
```suggestion
case class VoteCount(value: Int) {
```

カウンターは意味が異なります (参考: [weblio](https://ejje.weblio.jp/content/counter))

2022-12-06 08:27 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VotePersistence.scala
> +   */
```suggestion
  /**
   * プレイヤーの投票データを初期化します。この作用はプレイヤーがサーバーに参加するたびに呼ばれるため、作用が冪等でなければなりません。
   * @return プレイヤーデータを作成する作用
   */
```

ドキュメントに加筆するならこうですが、これはSQLマイグレーションでやればいいのでは？

2022-12-06 08:31 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/infrastructure/JdbcVotePersistence.scala
> +  private val chainVoteAllowableWidth = 4
```suggestion
  private val consecutiveVoteStreakDaysThreshold = 4
```

2022-12-06 08:31 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/infrastructure/JdbcVotePersistence.scala
> +  private val chainVoteAllowableWidth = 4
ところで、これ4だとまずいのでは？1であるべきだと思います。

2022-12-06 08:32 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def appleOpenState(uuid: UUID): F[FairyAppleConsumeStrategy]
```suggestion
  def consomeStrategy(uuid: UUID): F[FairyAppleConsumeStrategy]
```

2022-12-06 08:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def isFairyUsing(player: Player): F[Boolean]
```suggestion
  def isFairyAppearing(player: Player): F[Boolean]
```

2022-12-06 08:34 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def appleAteByFairyMyRanking(player: Player): F[Option[AppleAteByFairyRank]]
```suggestion
  def rankByMostConsumedApple(player: Player): F[Option[AppleAteByFairyRank]]
```

2022-12-06 08:35 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def allEatenAppleAmount: F[AppleAmount]
```suggestion
  def totalConsumedApple: F[AppleAmount]
```

2022-12-06 08:35 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def appleAteByFairyRanking(number: Int): F[Vector[Option[AppleAteByFairyRank]]]
```suggestion
  def rankingByMostConsumedApple(top: Int): F[Vector[Option[AppleAteByFairyRank]]]
```

2022-12-06 08:36 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def toggleFairySpeechSound(uuid: UUID): F[Unit]
```suggestion
  def toggleSoundOnSpeak(uuid: UUID): F[Unit]
```

2022-12-06 08:37 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def isPlayFairySpeechSound(uuid: UUID): F[Boolean]
```suggestion
  def doPlaySoundOnSpeak(uuid: UUID): F[Boolean]
```

2022-12-06 08:37 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +  def speechEndTime(player: Player): F[Unit]
```suggestion
  def sendDisappearTimeToChat(player: Player): F[Unit]
```

2022-12-29 15:30 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/domain/VotePersistence.scala
> +   */
このプレイヤーデータの作成は初めて参加したプレイヤーに対して行うことが目的なので、SQLマイグレーションだとちょっと違う気がします。

2022-12-29 17:17 UTC, rito528 commented
再レビューお願いします。

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/FairyPersistence.scala
> +   * 妖精に食べさせたりんごの量の順位上位`top`件を返す
```suggestion
   * 妖精に食べさせたりんごの量が多いプレイヤーを上位とし、そのランキングの上から指定した件数を返す
   * @param number 最上位から何番目まで取得するか件数を指定する。0以下であってはならない。
   * @return 指定した件数が要素数となり、その並びが消費量の降順になっているような順序つきのコレクションを返す作用。
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/FairyPersistence.scala
> +  def toggleFairySpeechSound(uuid: UUID, fairyPlaySound: Boolean): F[Unit]
```suggestion
  def setPlaySoundOnSpeech(player: UUID, playOnSpeech: Boolean): F[Unit]
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/FairyPersistence.scala
> +  def fairySpeechSound(uuid: UUID): F[Boolean]
```suggestion
  def playSoundOnFairySpeech(player: UUID): F[Boolean]
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/FairyPersistence.scala
> +   * 妖精が喋ったときに音を再生するか取得する
```suggestion
   * @return 妖精が喋ったときに音を再生するか取得する作用
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/AppleAteByFairyRank.scala
> +case class AppleAteByFairyRank(name: String, rank: Int, appleAmount: AppleAmount) {
```suggestion
case class AppleConsumeAmountRank(playerName: String, rank: Int, consumed: AppleAmount) {
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/AppleOpenStateDependency.scala
> +object AppleOpenStateDependency {
これはMenuのボタンの切り替えの都合なので、メニューに統合してしまって良いです

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/FairyMessages.scala
> +case class FairyMessages(messages: NonEmptyVector[FairyMessage])
```suggestion
case class FairyMessageChoice(messages: NonEmptyVector[FairyMessage])
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/property/NameCalledByFairy.scala
> +case class NameCalledByFairy(value: String)
```suggestion
case class ScreenNameForFairy(name: String)
```

2023-01-01 12:14 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/domain/resources/bukkit/FairyLoreTable.scala
> +object FairyLoreTable {
これもやはりMenuの都合なのでMenuに組み込んでしまって良いです

2023-02-18 12:28 UTC, KisaragiEffective reviewed
otherwise LGTM

2023-02-18 12:28 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +   * @return 妖精に食べさせたりんごの量の順位上`top`件を返す作用
```suggestion
   * @return 妖精に食べさせたりんごの量の上位`top`件を返す作用
```

2023-02-18 12:28 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/FairyAPI.scala
> +   * @return 妖精が喋るときに音をだすかをトグルする作用
```suggestion
   * @return 妖精が喋るときに音を再生するかをトグルする作用
```

2023-02-18 12:28 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/BukkitFairySpeech.scala
> +      startHour <- Sync[F].delay(LocalTime.now().getHour)
JavaTimeをFの上界として要求して、JavaTimeに定義されているメソッドを使うようにしてください。

2023-02-18 12:28 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/vote/subsystems/fairy/bukkit/actions/BukkitRecoveryMana.scala
> +        .delay(LocalDateTime.now())
同上

2023-02-20 08:47 UTC, rito528 commented
修正しました。

2023-02-21 00:49 UTC, KisaragiEffective approved these changes

2023-02-21 00:49 UTC, KisaragiEffective commented
LGTM!!

2023-02-21 00:49 UTC, merged