最終ログイン記録機能の再実装
GiganticMinecraft/SeichiAssist pull request #1588
Opened 2022-07-31 12:23 UTC by rito528

2022-09-30 14:09 UTC, KisaragiEffective requested changes

2022-09-30 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
> -      "lastquit" -> LastQuitCommand.executor,
LastQuitCommandです、コミットログを修正してください

2022-09-30 14:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/lastquit/domain/LastQuitPersistence.scala
> +  def lastQuitDateTime(playerName: PlayerName): F[Option[LastQuitDateTime]]
異なるUUIDを持つプレイヤーが同じプレイヤー名をかぶらないタイムスライスで持ち、彼らがそのタイムスライスでログインしたとすると、結果がSQLサーバーの実装依存 (どのプレイヤーが一番先頭に来るのか？その実装詳細に依存したくはない) になるのでこのインターフェースは不適切です。

```suggestion
  /**
  * 指定した[[UUID]]を持つプレイヤーの最終ログアウト日時を取得します。
  */
  def get(uuid: UUID): F[Option[LastQuitDateTime]]
```

2022-12-29 08:23 UTC, KisaragiEffective reviewed
otherwise LGTM

2022-12-29 08:23 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/domain/actions/LastSeenNameToUuid.scala
> +   * この時のプレイヤーの名前は、そのプレイヤーの名前の集合の内、 最も新しく、かつその名前がサーバーにとって既知であるという性質を持つ。
nit:
```suggestion
   * この時のプレイヤーの名前は、そのプレイヤーの名前の変更履歴の内、最も新しく、かつその名前がサーバーにとって既知であるという性質を持つ。
```

2022-12-29 08:57 UTC, rito528 commented
再レビューお願いします。

2022-12-29 08:59 UTC, KisaragiEffective approved these changes

2022-12-29 08:59 UTC, merged