feat: 建築量100万毎に全体通知を行う
GiganticMinecraft/SeichiAssist pull request #1669
Opened 2022-10-13 14:09 UTC by haruyan-hopemucci

close #1641

2022-10-13 14:47 UTC, Lucky3028 requested changes
[84903c3](https://github.com/GiganticMinecraft/SeichiAssist/pull/1669/commits/84903c370bf354ace6624a4cf1d90957775cbd55) : スタイルの修正（fmtをかけたなど）は「style: 」を使用してください

2022-10-13 14:53 UTC, rito528 requested changes

2022-10-13 14:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/application/actions/NotifyLevelUp.scala
>    def ofBuildLevelTo(player: Player)(diff: Diff[BuildLevel]): F[Unit]
`ofBuildLevelTo`と`ofBuildAmountTo`の間に改行を入れたほうが良いと思います

2022-10-13 14:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        val oldBuildAmount1MUnit = (oldBuildAmount.expAmount.amount / million).toLong
```suggestion
        val oldBuildOneMillionAmountUnit = (oldBuildAmount.expAmount.amount / million).toLong
```

2022-10-13 14:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +        val newBuildAmount1MUnit = (newBuildAmount.expAmount.amount / million).toLong
```suggestion
        val newBuildAmountOneMillionUnit = (newBuildAmount.expAmount.amount / million).toLong
```

2022-10-13 14:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +                                               })
2つの変数に分けてください。

2022-10-13 14:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +            val newBuildAmountDisplay100MUnit = newBuildAmount1MUnit / 100
```suggestion
            val newBuildAmountDisplayOneHundredMillionUnit = newBuildAmount1MUnit / 100
```

2022-10-13 14:53 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +            val newBuildAmountDisplay1MUnit = newBuildAmount1MUnit % 100
```suggestion
            val newBuildAmountDisplayOneMillionUnit = newBuildAmount1MUnit % 100
```

2022-10-13 15:08 UTC, Lucky3028 requested changes
ac9ed17 のコミットメッセージはConventionalCommitsに沿っていません。

2022-10-13 15:28 UTC, rito528 requested changes

2022-10-13 15:28 UTC, rito528 commented on docker/spigot/eula.txt
> +eula=true
```suggestion
eula=false
```

2022-10-13 18:31 UTC, haruyan-hopemucci commented
> [ac9ed17](https://github.com/GiganticMinecraft/SeichiAssist/commit/ac9ed174c7ee214728cf415c5877d90e38d8ec31) のコミットメッセージはConventionalCommitsに沿っていません。

コミットメッセージを修正したいのですが、当該コミットの直前にrebaseした際にエラーが発生しメッセージの変更まで手順が進めません。

error: could not apply ac9ed174c... Update src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala?
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply ac9ed174c... Update src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
Auto-merging src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
CONFLICT (content): Merge conflict in src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala

このコミットで発生する競合が原因のようですが、競合を解消しても --amend でコミットメッセージを変更することができませでした。正しい手順が分かりません。どうすればよいでしょうか？

2022-10-13 18:43 UTC, kory33 commented
> コミットメッセージを修正したいのですが、当該コミットの直前にrebaseした際にエラーが発生しメッセージの変更まで手順が進めません。
> ...
> このコミットで発生する競合が原因のようですが、競合を解消しても --amend でコミットメッセージを変更することができませでした。正しい手順が分かりません。どうすればよいでしょうか？

これって `git rebase -i ~7` しようとした感じですか？

2022-10-13 18:51 UTC, haruyan-hopemucci commented
> これって git rebase -i HEAD~7 しようとした感じですか？

仰る通りです。具体的には以下の記事を参考にコミットメッセージを変更しようとしました。
https://docs.github.com/ja/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message
https://web-engineer-wiki.com/git/commit-message-fix/#i-2

2022-10-13 18:53 UTC, kory33 commented
> > これって git rebase -i HEAD~7 しようとした感じですか？
> 
> 仰る通りです。具体的には以下の記事を参考にコミットメッセージを変更しようとしました。 https://docs.github.com/ja/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message https://web-engineer-wiki.com/git/commit-message-fix/#i-2

`pick` を `reword` に変えて編集を終えましたか？

2022-10-13 19:40 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/application/actions/NotifyLevelUp.scala
> +
```suggestion
```

ここに追加するのではなく、

```Scala
trait NotifyBuildAmountThreshold[F[_], Player] {

  def ofBuildAmountTo(player: Player)(diff: Diff[BuildAmountData]): F[Unit]

}
```

のような別の `trait` に切るとよいと思います

2022-10-13 20:11 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +            )(forString[IO])
これは作用が実行されません

2022-10-13 20:12 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +            )(forString[IO])
あ、そんなことなかった！忘れてください 🙇

2022-10-13 20:20 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
> +        }
`Stream` を `either` で混ぜなくとも、最後に合流させれば綺麗そうです（そうしたほうが複数の `Stream` に対して一般化しやすい）

```suggestion
      val levelNotification =
        buildCountReadAPI.buildLevelUpdates.evalMap {
          case (player, levelDiff) =>
            action.ofBuildLevelTo(player)(levelDiff)
        }

      val amountThresholdNotification =
        buildCountReadAPI.buildLevelUpdates.evalMap {
          case (player, amountDiff) =>
            actionAmount.ofBuildAmountTo(player)(amountDiff)
        }

      levelNotification.merge(amountThresholdNotification)
```

2022-10-13 20:29 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +          OnMinecraftServerThread[F].runAction(SyncIO {
`OnMinecraftServerThread` の中で行わないといけない処理はなさそうなんで、普通に `Sync[F].delay` とかに `SendMessageEffect` / `SendSoundEffect` を包んで、 `DiscordNotificationAPI` は `unsafeRunAsyncAndForget` しないように変更できます

@rito528 これアシストお願いします。もしわからなかったらメンションください！

2022-10-14 01:36 UTC, Lucky3028 commented
> > [ac9ed17](https://github.com/GiganticMinecraft/SeichiAssist/commit/ac9ed174c7ee214728cf415c5877d90e38d8ec31) のコミットメッセージはConventionalCommitsに沿っていません。
> 
> コミットメッセージを修正したいのですが、当該コミットの直前にrebaseした際にエラーが発生しメッセージの変更まで手順が進めません。
> 
> ```
> error: could not apply ac9ed174c... Update src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala?
> Resolve all conflicts manually, mark them as resolved with
> "git add/rm <conflicted_files>", then run "git rebase --continue".
> You can instead skip this commit: run "git rebase --skip".
> To abort and get back to the state before "git rebase", run "git rebase --abort".
> Could not apply ac9ed174c... Update src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> Auto-merging src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> CONFLICT (content): Merge conflict in src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> ```
> 
> このコミットで発生する競合が原因のようですが、競合を解消しても --amend でコミットメッセージを変更することができませでした。正しい手順が分かりません。どうすればよいでしょうか？

e388549 で達成されているのでOKです！

2022-10-14 04:58 UTC, haruyan-hopemucci commented
コミットメッセージの件は@kory33さんの多大なアドバイスにより無事解決できました。本当にありがとうございます。

2022-10-14 05:48 UTC, rito528 requested changes
概ねいい感じです！
命名などの細かい部分や、可読性にかかわる部分が多くなりますが、修正お願いします！

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +        val newBuildAmountOneMillionUnit = (newBuildAmount.expAmount.amount / million).toLong
```suggestion
        val oldBuildAmountOneMillionUnit = oldBuildAmount.expAmount.amount / million
        val newBuildAmountOneMillionUnit = newBuildAmount.expAmount.amount / million
```

現状の総建築量の最大値は約560万程で、取りうる値の範囲が近いうちに約21億を超えるということは考えにくいので`.toLong`せずとも`Int`型で十分です。

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +  // see also: https://github.com/GiganticMinecraft/SeichiAssist/blob/8ce9df9e4fc2da8f84d8aed4e2b74bbe95a61a02/src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notifica
```suggestion
```

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
>      val action: NotifyLevelUp[F, Player] = BukkitNotifyLevelUp[F]
```suggestion
    val notifyLevelUp: NotifyLevelUp[F, Player] = BukkitNotifyLevelUp[F]
```

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
> +            action.ofBuildLevelTo(player)(levelDiff)
```suggestion
            notifyLevelUp.ofBuildLevelTo(player)(levelDiff)
```

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
> +    val actionAmount: NotifyBuildAmountThreshold[F, Player] =
```suggestion
    val notifyBuildAmountThreshold: NotifyBuildAmountThreshold[F, Player] =
```

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
> +            actionAmount.ofBuildAmountTo(player)(amountDiff)
```suggestion
            notifyBuildAmountThreshold.ofBuildAmountTo(player)(amountDiff)
```

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +  // see also: https://github.com/GiganticMinecraft/SeichiAssist/blob/8ce9df9e4fc2da8f84d8aed4e2b74bbe95a61a02/src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notifica
```suggestion
```

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +            }
ここの処理なんですが、
```scala
Option(s"${newBuildAmountDisplayOneHundredMillionUnit}億")
        .whenA(newBuildAmountDisplayOneHundredMillionUnit > 0)
        .getOrElse("")
```
のように書くことでより見やすいコードにすることができます。

しかし、今回の場合は2つの文章を組み立てるために同じような処理を利用している(さらに、`BukkitNotifyBuildAmountThreshold.scala`以外のコードでも同じものが見られている)ので関数に切り出すと良いです。

関数の追加場所は`src/main/scala/com/github/unchama/generic`の中に、`OptionExtra.scala`というオブジェクトを追加すると良いと思います。
実装に関してですが
```scala
def unwarpOrDefault[F[_]: Applicative, A](condition: Boolean)(value: A, default: A): A = {
    Option(value).whenA(condition).getOrElse(default)
}
```
のような形になると思います。

これを実装した後、現在if文で行っている条件分岐を関数を利用したものに置き換えてください。

2022-10-14 05:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/application/actions/NotifyBuildAmountThreshold.scala
> +  def ofBuildAmountTo(player: Player)(diff: Diff[BuildAmountData]): F[Unit]
ドキュメントを追加すると良いと思います。

2022-10-14 08:54 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +            }
(そして、Stringに対してそのような関数を定義するということは、使用する側から見れば`Option`ではないものに対して`get(unwrap)`することになり、文脈として変なことになりませんか？)

2022-10-14 09:28 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +            }
> （getOrElseがあるんですから、getOrDefaultのほうがScala的ではありませんか？）
> (そして、Stringに対してそのような関数を定義するということは、使用する側から見ればOptionではないものに対してget(unwrap)することになり、文脈として変なことになりませんか？)

たしかにそうですね、これは`String`というよりも`Option`の関数と言う方が適切そうなので、ファイル名、関数名共に変更します

2022-10-14 11:54 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +  // see also: https://github.com/GiganticMinecraft/SeichiAssist/blob/8ce9df9e4fc2da8f84d8aed4e2b74bbe95a61a02/src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notifica
Todoは残してsee also以下のコメントは削除します。

2022-10-14 11:54 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
> +  // see also: https://github.com/GiganticMinecraft/SeichiAssist/blob/8ce9df9e4fc2da8f84d8aed4e2b74bbe95a61a02/src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/subsystems/notifica
Todoは残してそれ以下のコメントは削除します。

2022-10-14 13:03 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +          OnMinecraftServerThread[F].runAction(SyncIO {
コメント通り実装できました。

2022-10-14 13:50 UTC, rito528 requested changes

2022-10-14 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +  def apply[F[_]: OnMinecraftServerThread: ConcurrentEffect: DiscordNotificationAPI]
```suggestion
  def apply[F[_]: Sync: DiscordNotificationAPI]
```

2022-10-14 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +        } else Applicative[F].unit
```suggestion
        } else Sync[F].unit
```

2022-10-14 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +        val newBuildAmountOneMillionUnit = (newBuildAmount.expAmount.amount / million).toInt
これ`toInt`つけないとダメそうですか？

2022-10-14 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +  def apply[F[_]: OnMinecraftServerThread: ConcurrentEffect: DiscordNotificationAPI]
呼び出し元の型引数も修正してください。

2022-10-14 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
>    def apply[F[_]: OnMinecraftServerThread: ConcurrentEffect: DiscordNotificationAPI]
```suggestion
  def apply[F[_]: Sync: DiscordNotificationAPI]
```
呼び出し元の方引数も修正してください。

2022-10-14 13:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyLevelUp.scala
>            Applicative[F].unit
```suggestion
        } else 
           Sync[F].unit
```

2022-10-14 14:54 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +        val newBuildAmountOneMillionUnit = (newBuildAmount.expAmount.amount / million).toInt
`expAmount.amount` がBigDecimalなので除算結果の型もBigDecimalになってしまいます。
toIntが必要でした。

2022-10-14 14:55 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/bukkit/actions/BukkitNotifyBuildAmountThreshold.scala
> +        val newBuildAmountOneMillionUnit = (newBuildAmount.expAmount.amount / million).toInt
なるほど、わかりました！

2022-10-14 16:10 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
>    ]: ConcurrentEffect: OnMinecraftServerThread: ErrorLogger: DiscordNotificationAPI, G[_], A](
```suggestion
  ]: Sync: ErrorLogger: DiscordNotificationAPI, G[_], A](
```

2022-10-14 16:33 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
>    ]: ConcurrentEffect: OnMinecraftServerThread: ErrorLogger: DiscordNotificationAPI, G[_], A](
`ConcurrentEffect` は最後の`merge`が暗黙に利用しているため、型引数からは除外できませんでした。`OnMinecraftServerThread` は除外できたので、そちらだけ対処してコミットします。

2022-10-15 01:34 UTC, rito528 requested changes

2022-10-15 01:34 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
>    ]: ConcurrentEffect: OnMinecraftServerThread: ErrorLogger: DiscordNotificationAPI, G[_], A](
なるほど、であれば`merge`が`Concurrent`を要求しているので`Concurrent`で要件を満たせそうですね。

2022-10-15 01:34 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
> +  def backgroundProcess[F[_]: Sync: ConcurrentEffect: ErrorLogger: DiscordNotificationAPI, G[
```suggestion
  def backgroundProcess[F[_]: Concurrent: ErrorLogger: DiscordNotificationAPI, G[
```
・`ConcurrentEffect`は`Sync`を満たすので`ConcurrentEffect`と`Sync`を2つ並べることはできません。
・今回必要なのがnotification類で要求される`Sync`と`merge`で要求される`Concurrent`なので、`Concurrent`を利用すれば要求を満たすことができます。

Type classes in Cats: https://cdn.rawgit.com/tpolecat/cats-infographic/master/cats.svg

2022-10-15 04:08 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/buildcount/subsystems/notification/System.scala
> +  def backgroundProcess[F[_]: Sync: ConcurrentEffect: ErrorLogger: DiscordNotificationAPI, G[
詳細なクラス図のご紹介ありがとうございました。指摘通り`Concurrent`で対処いたします。

2022-10-15 04:27 UTC, rito528 approved these changes
LGTM👍👍
開発ありがとうございます！！！

2022-10-15 04:27 UTC, merged