feat:スキルで流体の水を消せるようにする
GiganticMinecraft/SeichiAssist pull request #1694
Opened 2022-10-23 04:57 UTC by haruyan-hopemucci

close #1643 

レビューをお願いいたします。

## Note

通常スキル（破壊系、遠距離系）で水を破壊できるようにする変更。
水を破壊する仕様は溶岩を破壊する仕様に準ずる。

- 破壊によるマナ消費なし
- 破壊による整地量の増加なし
- ツール耐久値の消費量は通常ブロックの10倍

2022-10-23 05:02 UTC, Lucky3028 requested changes
9764c05 : コミットメッセージのタイトルに「。」は不要です

2022-10-23 05:07 UTC, rito528 requested changes
開発ありがとうございます！
以下レビューです。

2022-10-23 05:07 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +            .zip(multiWaterList)
ここは`zipped`が使えそうです

```suggestion
          (((blocks, lavas), waters), chunkIndex) <- (
              multiBreakList, 
              multiLavaList,
              multiWaterList
          ).zipped
```

2022-10-23 05:07 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +                  waters.foreach(_.setType(Material.AIR))
ここは`lavas`と`waters`に対して同様の`foreach`を回しているので一つにまとめることができそうです

2022-10-23 05:07 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/EntityListener.scala
> +    waterBlocks.foreach(_.setType(Material.AIR))
ここはlavasとwatersに対して同様のforeachを回しているので一つにまとめることができそうです

2022-10-23 05:51 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +          (((blocks, lavas), waters), chunkIndex) <- multiBreakList
```suggestion
          ((blocks, lavas, waters), chunkIndex) <- multiBreakList
```

2022-10-23 16:11 UTC, KisaragiEffective reviewed
nits, otherwise (except commented in the past) LGTM

2022-10-23 16:11 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +          // 減る耐久値の計算(１マス溶岩、水を破壊するのにはブロック１０個分の耐久が必要)
nit:
```suggestion
          // 減る耐久値の計算(溶岩及び水を破壊するとブロック１０個分の耐久値減少判定を行う)
```

2022-10-23 16:11 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +            breakBlocks.size + 10 * lavaBlocks.size + 10 * waterBlocks.size
nit:
```suggestion
            breakBlocks.size + 10 * (lavaBlocks.size + waterBlocks.size)
```

2022-10-23 17:06 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +            .zip(multiWaterList)
`zipped`はscala2.13でdeprecatedになっていました。
その代わり`lazyZip`を使用するようにアナウンスがあるのですが、`lazyZip`で作成したView（名前の通り遅延評価する）はfor式のジェネレータを通しても評価されずイテレートが回りませんでした。
なので仕方なく`zip`をネストしています。

とコメントする前に再調査した結果、viewに対し`toMap`すれば評価だけ行われることが分かったので`lazyZip`で実装しなおします。検証では期待通りイテレートが回りました。

2022-10-23 17:18 UTC, haruyan-hopemucci commented
> [9764c05](https://github.com/GiganticMinecraft/SeichiAssist/commit/9764c053914ba4cad0cacb80062e85c31baea089) : コミットメッセージのタイトルに「。」は不要です

コメントから"。"を除去しました。（今回は正規の手順でコメントの修正ができました！）

2022-10-23 17:26 UTC, haruyan-hopemucci commented
@rito528 @KisaragiEffective 
溶岩と水の破壊処理でblockのsetが纏められる部分は纏めます（アサルトの処理では纏めていました）
ツール消費の計算も纏めます

2022-10-23 18:22 UTC, haruyan-hopemucci commented
指摘点の改修が終了したので再レビューをお願いします。

2022-10-23 22:05 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +              multiWaterList).zipWithIndex.toMap
```suggestion
              multiWaterList).zipWithIndex.toList
```
でも良いと思います

2022-10-24 02:14 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +              multiWaterList).zipWithIndex.toMap
最終的にはListになるのでそちらでも良さそうですね

2022-10-24 03:34 UTC, KisaragiEffective commented
間違えた

2022-10-24 03:35 UTC, KisaragiEffective approved these changes
LGTM

2022-10-24 03:52 UTC, rito528 approved these changes
LGTM
ありがとうございます！

2022-10-24 03:54 UTC, merged