feat: プレイヤーレベルに応じたホームポイントの追加
GiganticMinecraft/SeichiAssist pull request #1707
Opened 2022-11-01 03:49 UTC by haruyan-hopemucci

close #1006 

- `/home` コマンドを追加ホームポイントに対応
- 棒メニューのホームメニューを追加ホームポイントに対応
  - ページネーションを実装し、合計2ページにする　ついでに棒メニューに戻るボタンも追加
  - GUIにはレベル不足でまだ使用できないホームポイントも表示されるが、使用することはできない

2022-11-01 08:56 UTC, rito528 requested changes

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/TopLevelRouter.scala
> +import com.github.unchama.seichiassist.menus.home.{HomeMenu}
```suggestion
import com.github.unchama.seichiassist.menus.home.HomeMenu
```

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxNumberByPlayerOf(seichiAmount: SeichiAmountData, buildAmount: BuildAmountData): Int = {
`maxNumberByPlayerOf`関数は「プレイヤーが現在扱える`HomeId`の最大値を返す」ので、返り値は`Int`ではなく`HomeId`であるべきです。

また、「「プレイヤーが」現在扱える`HomeId`の最大値」なので、引数として受け取るのは`Player`のほうが良さそうです。
もしくはドキュメントを修正してください。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +   * - 無条件で全員に1つ
無条件で全員に1つ付与するなら「追加ホームポイント」ではなく「常設ホームポイント」になりませんか？

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  val maxNumberExtra: 9 = 9
`maxNumberExtra`は`HomeId.scala`でしか使っていなさそうなので`private`にしてよさそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +   * @return そのプレイヤーが現在扱えるHomeIdの最大値
```suggestion
   * @return そのプレイヤーが現在扱える[[HomeId]]の最大値
```

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +   * Fの文脈で返される（Gの文脈でないことに注意）
このコメントは自明なのでいらないと思います。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +  private def maxHomeIdCanBeUsedF(player: Player): F[Int] = {
この関数はコマンドを組み立てるために必要な関数ではなく、Home機能が利用できる個数を表す関数なので、ドメイン層で定義されていたほうが良さそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
これは解釈の仕方の問題かもしれませんが、「`HomeId`が使える」とより「`HomeId`のHomeが利用できる」ということを表している方が正しそうなので変数名を改めたほうが良さそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
これは解釈の仕方の問題かもしれませんが、「`HomeId`が使える」とより「`HomeId`のHomeが利用できる」ということを表している方が正しそうなので変数名を改めたほうが良さそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
これは解釈の仕方の問題かもしれませんが、「`HomeId`が使える」とより「`HomeId`のHomeが利用できる」ということを表している方が正しそうなので変数名を改めたほうが良さそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
これは解釈の仕方の問題かもしれませんが、「`HomeId`が使える」とより「`HomeId`のHomeが利用できる」ということを表している方が正しそうなので変数名を改めたほうが良さそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> + */
```suggestion
/**
 * ホームメニュー
 *
 * Created by karayuu on 2019/12/14
 */
```

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    val ioCanReadHome: HomeReadAPI[IO]
```suggestion
    val homeReadAPI: HomeReadAPI[IO]
```

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import eu.timepit.refined.numeric._
これ`import eu.timepit.refined._`だけだとだめですか...？

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map()
```suggestion
        else Map.empty
```
のほうが良さそうです。

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      implicit val ioCanReadHome: HomeReadAPI[IO] = environment.ioCanReadHome
Environmentのほうで`HomeReadAPI`を`implicit`で定義すれば、この変数はいらなくなりそうです

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +          }
```suggestion
          val worldName = 
            ManagedWorld
              .fromName(location.worldName)
              .map(_.japaneseName)
              .getOrElse(location.worldName)
```
Scalafmtで入ったものでなければいらないと思います

2022-11-01 08:56 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
これは`NonServerThreadContextShift`をEnvironmentから要求していいと思います

2022-11-01 09:06 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/TopLevelRouter.scala
> +import com.github.unchama.seichiassist.menus.home.{HomeMenu}
他にもこのような記載があるかもしれないので別途import整理を行います。

2022-11-01 09:14 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> + */
このsuggestは特に何もなし、ということで良いですか？

2022-11-01 09:14 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      Seq(50, 100, 200).foldLeft(0)((acm, elem) => if (seichiLevel >= elem) acm + 1 else acm)
・この`Seq`は別途変数に切り出して良さそう
・`Seq`ではなく`Set`のほうが良さそう

2022-11-01 09:16 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> + */
いいえ、ドキュメントを削除していいのでは？というsuggestです。

2022-11-01 09:21 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import eu.timepit.refined.numeric._
単純にそれだけだとダメっぽいです。
`auto._`や`numeric._`以下のクラスを使用している箇所に適切にパッケージ名を修飾すれば問題なさそうですが...
個人的には現在の記載で進めたいです。

2022-11-01 09:24 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import eu.timepit.refined.numeric._
なるほど、わかりました。
であればこれで問題ないです。

2022-11-01 09:30 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +          }
ここは変更していない箇所で、scalafmtでもこのブレースは取れていませんでした。
ブレースを消しておきます。

2022-11-01 09:34 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +  private def maxHomeIdCanBeUsedF(player: Player): F[Int] = {
定義先は`HomeId`が適切でしょうか。
移設します。

2022-11-01 09:38 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
意図としては指摘通りなので、`availableThisHomeId`などとした方が適切でしょうか？
単語として意味が通るか全く自信なしですが...

2022-11-01 09:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +  private def maxHomeIdCanBeUsedF(player: Player): F[Int] = {
`HomeId`に移設して良さそうです。

2022-11-01 09:46 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +   * - 無条件で全員に1つ
その通りですね。
初期状態でのホームポイント使用可能数を10にして、追加で8個、というように変更します。

2022-11-01 09:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
「指定したホームが使えるか」を表しているので、単に`canUseHome`とかでいいと思います

2022-11-01 09:50 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxNumberByPlayerOf(seichiAmount: SeichiAmountData, buildAmount: BuildAmountData): Int = {
`player`を渡すとこの関数で副作用が発生するので、各amountを渡しています。
ドキュメント、関数名を適切に修正して対応します。

2022-11-01 09:58 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxNumberByPlayerOf(seichiAmount: SeichiAmountData, buildAmount: BuildAmountData): Int = {
また、この関数はホームポイントそのものではなく量を表すものなので、単位は`Int`で良いのではないでしょうか。この関数の戻り値と常設ホームポイントの数などを加算して最終的な閾値を求めています。

2022-11-01 10:08 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxNumberByPlayerOf(seichiAmount: SeichiAmountData, buildAmount: BuildAmountData): Int = {
なるほど。であればこれで良さそうです。

2022-11-01 10:47 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
コメントからどのようなことをしなければいけないのかが分からないので別途実装の相談をさせてくださいm(_ _)m
申し訳ないです。

2022-11-01 10:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
OKです。

2022-11-01 11:25 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> + */
承知しました。消しておきます。
（-と同じコードが+されててアッレーになった）

2022-11-01 11:41 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
あ、なんとなくやらなければいけないことは分かりました。
ただ、`TopLevelRouter`に`NonServerThreadContextShift`がimplicitされていないのでEnvironmentに入れることができませんでした。
これはこのままの方が良いかも..？

2022-11-01 11:46 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
>ただ、TopLevelRouterにNonServerThreadContextShiftがimplicitされていないのでEnvironmentに入れることができませんでした。

`TopLevelRouter`に`NonServerThreadContextShift`を要求すればいいだけでは...?

> これはこのままの方が良いかも..？
それはなぜですか...?

2022-11-01 11:54 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
申し訳ありません。`TopLevelRouter`に単純に当該オブジェクトを要求すれば解決しました。
`SeichiAssist`が`NonServerThreadContextShift`を持っていないと勘違いしていました。(`asyncShift`がimplicitされました）

2022-11-01 11:55 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import com.github.unchama.seichiassist.concurrent.PluginExecutionContexts.asyncShift
解決できたようでよかったです👍

2022-11-01 14:20 UTC, KisaragiEffective requested changes

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> + */
unresolved
理由: 解消されていない・このコメントは正しくない

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        if (pageIndex - 1 >= 0)
nit:
```suggestion
        if (pageIndex >= 1)
```

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      }
nit: `Option.fold`を使ってください

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +  private def maxHomeIdCanBeUsedF(player: Player): F[Int] = {
```suggestion
  private def maxAvailableHomeCountF(player: Player): F[Int] = {
```

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          }.whenA(canUseHomeId)
nit: ここは中括弧必要ありません

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +        } yield TargetedEffect.emptyEffect
これ型があっていないような気がしますが…

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
```suggestion
          isHomeAvailable = maxHomeIdCanBeUsed >= homeId.value
```

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +                }
Option.foldを使ってください

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      Seq(50, 100, 200).foldLeft(0)((acm, elem) => if (seichiLevel >= elem) acm + 1 else acm)
```suggestion
      Seq(50, 100, 200).count(rawLevel => seichiLevel >= rawLevel)
```

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      Seq(20, 40, 60, 100).foldLeft(0)((acm, elem) => if (buildLevel >= elem) acm + 1 else acm)
```suggestion
      Seq(20, 40, 60, 100).count(rawLevel => buildLevel >= rawLevel)
```

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +   * プレイヤーの現在レベル（整地レベル、建築レベル）で利用可能なホームポイントIDの最大値を取得する作用
理想的には`HomeID`自体は比較可能であるべきではないので、

* 利用可能なホーム数を取得する作用
* 利用可能な`HomeID`のうち、内部的なIDが最大の`HomeID`を取得する作用

のどちらかにするべきです

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +          }
`Option.fold`

2022-11-01 14:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      }
`Either.fold`

2022-11-01 15:30 UTC, haruyan-hopemucci commented
ローカル上で修正した分を一旦pushしました。

2022-11-01 15:32 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> + */
コメントを削除したものをpush済みです。
（なおこのファイルはディレクトリを移動したものです）

2022-11-01 15:40 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +  private def maxHomeIdCanBeUsedF(player: Player): F[Int] = {
メソッドの戻り値を受ける変数名も合わせて名称変更します。

2022-11-01 17:18 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +                }
ここを`Option.fold`に書き換えると、Some側の型が合わなくなってしまいます。何故なのでしょうか...
![image](https://user-images.githubusercontent.com/68041476/199295711-63867964-bde8-4b94-af6e-1a15dadbd079.png)

2022-11-01 17:28 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          canUseHomeId = maxHomeIdCanBeUsed >= homeId.value
[1ec07c6](https://github.com/GiganticMinecraft/SeichiAssist/pull/1707/commits/1ec07c65b56d8bec86033abc8685ee51adf9e9c5) で解消

2022-11-01 17:29 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +   * プレイヤーの現在レベル（整地レベル、建築レベル）で利用可能なホームポイントIDの最大値を取得する作用
13790c7 で解消

2022-11-01 17:29 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +          }
92a178a で解消

2022-11-01 17:29 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      }
92a178a で解消

2022-11-01 17:31 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      Seq(50, 100, 200).foldLeft(0)((acm, elem) => if (seichiLevel >= elem) acm + 1 else acm)
001f0e1 で解消

2022-11-01 17:31 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      Seq(20, 40, 60, 100).foldLeft(0)((acm, elem) => if (buildLevel >= elem) acm + 1 else acm)
001f0e1 で解消

2022-11-01 17:32 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +          }.whenA(canUseHomeId)
2300d94 で解消

2022-11-01 17:34 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +  private def maxHomeIdCanBeUsedF(player: Player): F[Int] = {
1ec07c6 で修正しました

2022-11-01 17:35 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      }
修正しました
92a178a6

2022-11-01 18:08 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +        } yield TargetedEffect.emptyEffect
ビルドも通りますし、ゲーム内でも問題なくコマンドが機能しているのは確認できているので、問題ないとは思います

2022-11-01 18:19 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +                }
当該コードの抜粋です
```scala
          if (isHomeAvailable)
            homeLocation.fold(
              MessageEffect(s"ホームポイント${homeId}が設定されてません")
            ) { someHome =>
              val location = someHome.location
              LocationCodec.toBukkitLocation(location).fold(
                MessageEffect(
                  List(s"${RED}ホームポイントへのワープに失敗しました", s"${RED}登録先のワールドが削除された可能性があります")
                )
              )(bukkitLocation =>
                TeleportEffect.to[F](bukkitLocation).mapK(Effect.toIOK[F]) >>
                  MessageEffect(s"ホームポイント${homeId}にワープしました")   // <- ここで型の不一致が発生
              )
            }
          else
            MessageEffect(s"ホームポイント${homeId}は現在のレベルでは使用できません")
```

2022-11-02 01:58 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      Seq(50, 100, 200).foldLeft(0)((acm, elem) => if (seichiLevel >= elem) acm + 1 else acm)
`foldLeft`を`count`に変更する過程でこちらも対処しました。
d1044d6
aa3e0cb

2022-11-02 06:19 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +                }
tereportするブロックだけ`Kleisli[IO, Player, Unit]`を返し、その他のブロックは`TargetedEffect[CommandSender]`を返す。
match式の時は返ってくる値の親クラスに相当する型がmatch式自体の戻り値の型になり、それは`Kleisli[IO, Player, Unit]`と推論されている。ということは`TargetedEffect[CommandSender]`は`Kleisli[IO, Player, Unit]`にキャスト（という表現が正しいかは分からないけど）できるはずなんですよね。
その方法が分かれば解決できそうですが、さっぱり思いつきません。

2022-11-02 06:22 UTC, rito528 requested changes

2022-11-02 06:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
「条件に一致したときだけ値を持ち、それ以外は空」という処理なので、
```Scala
def when[A](cond: Boolean)(value: Map[A]): Map[A]
```
の様な型シグネチャの関数をMapの拡張関数として定義して利用できるといいですね。

その他でも同じような処理があるので、そこも書き換えられると良さそうです。

2022-11-02 06:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +//  }
```suggestion
```
コメントを消してください。

2022-11-02 08:23 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +                }
現在の`TeleportEffect.to`関数は`Kleisli[F, Player, Unit]`を返しますが、`TargetedEffect[CommandSender]`の実態は`Kleisli[F, CommandSender, Unit]`なので型エラーになります。
なので、`TeleportEffect.to`関数を`Kleisli[F, CommandSender,Unit]`を返すようにすると良いと思います。
(もしくは`TargetedEffect[CommandSender]`)

> match式の時は返ってくる値の親クラスに相当する型がmatch式自体の戻り値の型になり、それはKleisli[IO, Player, Unit]と推論されている。ということはTargetedEffect[CommandSender]はKleisli[IO, Player, Unit]にキャスト（という表現が正しいかは分からないけど）できるはず

これは`TargetedEffect`が`CommandSender`として持っている型が`org.bukkit.CommandSender`であって、`org.bukkit.Player`では無いので別物として扱われるのは自然ではないでしょうか。

別の例で示すのであれば、`def hoge[F[_]]: F[Unit]`という関数が定義されていて、`hoge[SyncIO]`から`hoge[IO]`を推論することができると言っているのと同じ意味になりそうです。
※`SyncIO`から`IO`は`ContextCoercion.scala`にも書かれているように自明な変換が可能

2022-11-02 08:47 UTC, rito528 requested changes

2022-11-02 08:47 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +              .ioCanOpenHomeRemoveConfirmationMenu
これは`ioCanOpenHomeRemoveConfirmationMenu`をEnvironmentの定義で`implicit`にしてしまえばチェーンをする必要がなくなるのではないでしょうか。

2022-11-02 08:47 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import cats.effect.implicits._
このimportは193行目でされているのでいらないと思います。

2022-11-02 08:47 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +   */
このコメントはMenuをextendsしたときにIDEが自動で補完したものだと思いますが、traitのドキュメントをミックスイン先にそのまま記載するのは、trait側のドキュメントが更新された時にデッドコメントになりやすいので消して良いと思います。

他の箇所も同様に消してください。

2022-11-02 08:47 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +  )
```suggestion
  )
  
```

2022-11-02 08:47 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  ], F]](player: Player)(
`domain`層ではBukkitに対して依存したくありません。
現在の実装だと`Player`がBukkitに依存をしているので抽象化を行ってください。

2022-11-02 09:17 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +    import cats.effect.implicits._
193行目で記載されているのは `import cats.implicits._`で、ここでは異なるパッケージをimportしています。
これは先頭（193行目の続き）に書かれていた方が見通しがよさそうですね。

2022-11-02 09:19 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +   */
`override def`で定義されるメソッドのメソッドコメントは全て不要ということで良いでしょうか。

2022-11-02 09:24 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
コメントを受けて考えてみましたが、現在ページの前後のページについて、存在しえないページ番号であれば`None`、存在するページ番号なら`Some()`とするOptionを使って`Option.fold`で戻り値を分けた方がよさそうな気がします。どうでしょうか。

2022-11-02 09:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +   */
そうです。

2022-11-02 09:32 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
`Option.fold`だとNoneとSomeに分ける必要が出てくるので、それなら上記の様な関数を定義したほうが条件を渡すだけなので簡潔にならないでしょうか？

2022-11-02 09:44 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
どちらが簡潔かどうかは私では判断つきません🤔
元コメントの関数を実装は、`cond`がtrueの場合はそのMapオブジェクト自身、'cond`がfalseの場合にvalue`側を返す、という仕様で認識あっていますでしょうか。

2022-11-02 09:46 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
`cond`が`true`のときには`value`を返し、そうでなければ`Map.empty`を返すという実装になると思います

2022-11-02 09:55 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
なるほどです。
`generic/MapExtra`が既に存在するので、このオブジェクトに実装してみます。

2022-11-02 10:54 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +              .ioCanOpenHomeRemoveConfirmationMenu
やってみましたが別のimplicitしているオブジェクトに暗黙してしまうようでうまくいきませんでした。

2022-11-02 11:51 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +                }
`TeleportEffect.to`はこのコマンド1か所でしか使っていなかったので、戻り値を`Kleisli[F, CommandSender, Unit]`で返すようにすることで解決することにしました。
eb192e7abb8677e53aa02c5bb3f6066572180394

2022-11-02 11:53 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +   */
当該コメントをすべて削除しました。
046596bf746e4d26fc9bb0ab0dd14395d02547ab

2022-11-02 11:55 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +        else Map.empty
対処しました。メソッド名を`whenOrEmply`とし、Emptyが返ることを明示しました。
d79f4292cc2bc72f4051584a3bfc917355c0086f
0152d53237b7c2786f79b65fdc7ff59e97371168

2022-11-02 12:00 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  ], F]](player: Player)(
このような方針で良いでしょうか。
- ドメイン層の`HomeId`では`Player`を扱わない。`(SeichiAmountData, BuildAmountData) => Int`となるような実装とする。
- SeichiAmountData, BuildAmountDataは呼び出し元の`HomeCommand`で取得する

2022-11-02 12:02 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  ], F]](player: Player)(
いや、引数はそのままにして単に`Player`型を抽象化するいいと思います。

2022-11-02 12:05 UTC, rito528 commented
@haruyan-hopemucci 
レビューに対して丁寧に解決したコミットIDを貼るのはとても丁寧で良いと思いますが、レビューの際はコミットで変更を見るというより変更したファイルを一気に見て確認するのでそこまでしていただかなくても大丈夫ですよ。

また、レビュー内容も自分で解決したと思ったらどんどんresolveしていきましょう！

2022-11-02 12:07 UTC, rito528 commented on src/main/scala/com/github/unchama/generic/MapExtra.scala
> +  def whenOrEmpty[K, V](cond: Boolean)(value: Map[K, V]): Map[K, V] =
`whenOrEmpty`という関数名だと意味がわかりにくいので単に`when`でいいと思います。
(`Option.when`という関数が標準ライブラリにあるので、単に`when`でも意味は伝わるはず)

2022-11-02 12:13 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +              .ioCanOpenHomeRemoveConfirmationMenu
いや、これenvironmentをimportしてないからっぽいですね。
environmentの内容はここでしか使われていないのでこれで良さそうです。

2022-11-02 12:14 UTC, haruyan-hopemucci commented
@rito528
>レビューの際はコミットで変更を見るというより変更したファイルを一気に見て確認するので、そこまでしていただかなくても大丈夫ですよ。
また、レビュー内容も自分で解決したと思ったらどんどんresolveしていきましょう！

承知しました！

2022-11-02 12:22 UTC, rito528 requested changes

2022-11-02 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/TeleportEffect.scala
>        })
```scala
Kleisli { 
    case p: Player => 
        OnMineCraftServerThread[F].runAction(SyncIO {
            p.teleport(location)
        })
    case _ =>
}
```
のような形でいいと思います。
teleport以外はメインスレッドで処理する必要がないこと、返り値がUnitなので例外を投げずに単に何もしないでいいと思います。

2022-11-02 12:47 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/command/HomeCommand.scala
> +        } yield TargetedEffect.emptyEffect
問題ないと思います。

2022-11-02 14:02 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/bukkit/TeleportEffect.scala
>        })
```scala
  def to[F[_]: OnMinecraftServerThread](location: Location): Kleisli[F, CommandSender, Unit] = {
    Kleisli { commandSender =>
      OnMinecraftServerThread[F].runAction(SyncIO {
        commandSender match {
          case player: Player => player.teleport(location)
          case _              =>
        }
        ()
      })
    }
  }
  ```
のような実装だと動くはずです

2022-11-02 15:24 UTC, haruyan-hopemucci commented
指摘事項を全て解決しました。
再レビューをお願いします。

2022-11-02 15:39 UTC, rito528 requested changes
otherwise LGTM.

2022-11-02 15:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      }
```suggestion
      val prevButtonMap = 
        MapExtra.when(pageIndex >= 1)(
          Map(
            ChestSlotRef(4, 7) -> CommonButtons.transferButton(
              new SkullItemStackBuilder(SkullOwners.MHF_ArrowLeft),
              s"${pageIndex}ページ目へ",
              HomeMenu(pageIndex - 1)
            )
          )
        )
```
カッコがいらないのと、`transferButton`を変数に切り出すとわかりやすいと思います。

2022-11-02 15:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/home/HomeMenu.scala
> +      }
`prevButtonMap`と同様

2022-11-02 15:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      seichiLevelThreshold.count(rawLevel => seichiLevel >= rawLevel)
```suggestion
      seichiLevelThreshold.count(seichiLevel >= _)
```

2022-11-02 15:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +      buildLevelThreshold.count(rawLevel => buildLevel >= rawLevel)
```suggestion
      buildLevelThreshold.count(buildLevel >= _)
```

2022-11-02 15:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxAvailableHomeCountF[F[_]: ConcurrentEffect, G[_]: SyncEffect: ContextCoercion[
この関数なんですが、「プレイヤーの現在レベル（整地レベル、建築レベル）で利用可能なホームポイント数を取得する作用」なのであれば`HomeId`の責務ではない気がします。

2022-11-02 15:57 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxAvailableHomeCountF[F[_]: ConcurrentEffect, G[_]: SyncEffect: ContextCoercion[
`Home`の方でしょうか🤔

2022-11-02 15:59 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxAvailableHomeCountF[F[_]: ConcurrentEffect, G[_]: SyncEffect: ContextCoercion[
そうですね

2022-11-02 16:01 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/home/domain/HomeId.scala
> +  def maxAvailableHomeCountF[F[_]: ConcurrentEffect, G[_]: SyncEffect: ContextCoercion[
では`Home`の方へ移動させます

2022-11-02 16:40 UTC, rito528 approved these changes
LGTM.
お疲れ様でした！！

2022-11-02 16:42 UTC, merged