マインスタックの再実装
GiganticMinecraft/SeichiAssist pull request #1714
Opened 2022-11-06 05:43 UTC by rito528

マインスタックを再実装しました。

再実装の際にやむを得ずガチャのイベント機能を実装しました。(常に通常ガチャ排出アイテムを取得する必要があるため)
マインスタックのガチャ景品リストが通常排出のガチャアイテムから一覧を取得する仕様になった影響で、**このPRが取り込まれる・リリースされる時にイベント期間ではない必要があります。**

2022-11-06 05:43 UTC, rito528 commented
まずセルフレビューをします

2022-11-06 07:18 UTC, rito528 reviewed
セルフレビュー

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[Player]]の[[MineStackObject]]を指定した量だけ増加させる作用
```suggestion
   * @return `player`の`mineStackObject`を`amount`だけさせる作用
```

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[Player]]の[[MineStackObject]]を指定された量だけ減少させ、実際に減少させた量を返す
```suggestion
   * @return `player`の`mineStackObject`を`amount`だけ減少させ、実際に減少させた量を返す
```

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[Player]]のMineStackUsageHistoryに[[MineStackObject]]を追加する
```suggestion
   * @return `player`のMineStackUsageHistoryに`mineStackObject`を追加する
```

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[Player]]が持っている[[MineStackObject]]の量を取得する
```suggestion
   * @return `player`が持っている`mineStackObject`の量を取得する
```

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[Player]]のMineStackUsageHistoryを取得する
```suggestion
   * @return `player`のMineStackUsageHistoryを取得する
```

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackUsageHistory.scala
> +  private var _usageHistory: Vector[MineStackObject[ItemStack]] = Vector.empty
`Ref`を使ったほうが良さそう？

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +                  .map(isSucceed => if (itemStack != null && isSucceed) Some(index) else None)
`collect`が使えそう

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
>                UnfocusedEffect {
`DefferedEffect`が使えそう

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/System.scala
> +        override val listeners: Seq[Listener] = Seq(new PlayerPickupItemListener[F, G]())
```suggestion
        override val listeners: Seq[Listener] = Seq(new PlayerPickupItemListener[F, G])
```

2022-11-06 07:18 UTC, rito528 commented on src/main/scala/com/github/unchama/buildassist/menu/MineStackMassCraftMenu.scala
> +                          .unsafeRunSync() >= amount
forの中に突っ込めそう

2022-11-06 12:14 UTC, rito528 commented
レビューお願いします。

2022-11-07 06:24 UTC, KisaragiEffective requested changes

2022-11-07 06:24 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.0__Add_gacha_type_colmns.sql
> +ALTER TABLE gachadata ADD event_name VARCHAR(7) DEFAULT NULL;
マイグレーションはできるだけ冪等にしてください
```suggestion
ALTER TABLE IF EXISTS gachadata ADD event_name IF NOT EXISTS VARCHAR(7) DEFAULT NULL;
```

2022-11-07 06:24 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.0__Add_gacha_type_colmns.sql
> +ALTER TABLE gachadata ADD event_name VARCHAR(7) DEFAULT NULL;
[`VARCHAR(N)`](https://mariadb.com/kb/en/varchar/)に関するドキュメントを読むと

> For example, utf8 characters can require up to three bytes per character, so a VARCHAR column that uses the utf8 character set can be declared to be a maximum of 21,844 characters.

と書いてありますが、本当にこれであっていますか？

2022-11-07 06:24 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.1__Create_gacha_eventsTable.sql
> +CREATE TABLE gacha_events(
```suggestion
CREATE TABLE IF NOT EXISTS gacha_events(
```

2022-11-07 06:24 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Migrate_minestack_gacha_object.sql
> +CREATE TABLE mine_stack_gacha_objects(
```suggestion
CREATE TABLE IF NOT EXISTS mine_stack_gacha_objects(
```

2022-11-07 06:24 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.13.2__Migrate_minestack_gacha_object.sql
> +DROP TABLE msgachadata;
```suggestion
DROP TABLE IF EXISTS msgachadata;
```

2022-11-07 08:17 UTC, rito528 commented on src/main/resources/db/migration/V1.13.0__Add_gacha_type_colmns.sql
> +ALTER TABLE gachadata ADD event_name VARCHAR(7) DEFAULT NULL;
間違っていそうですね。
修正します。

2022-11-07 09:36 UTC, rito528 commented
レビュー内容修正しました。
再レビューお願いします。

2022-11-07 10:45 UTC, rito528 commented on src/main/resources/db/migration/V1.13.0__Add_gacha_type_colmns.sql
> +ALTER TABLE gachadata ADD event_name VARCHAR(7) DEFAULT NULL;
いや、そんなことないですね。
> A variable-length string. M represents the maximum column length in characters.

と書いてあるので`VARCHAR(M)`の`M`は文字数で問題なさそうですね。

2022-11-27 08:40 UTC, KisaragiEffective requested changes

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +                case None                   => getType.toString
nit
```suggestion
                case None                   => if (hasDisplayName) getDisplayName else getType.toString
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/GachaDrawAPI.scala
> +   * @return ガチャを実行する作用
```suggestion
   * @return ガチャを引く作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>          "現在のメインハンドをガチャリストに追加。確率は1.0までで指定",
```suggestion
        "現在のメインハンドを指定されたイベントのガチャリストに追加。確率は1.0までで指定",
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +        "イベントを削除します。(間違ってイベントを作成した時以外に使わないでください。)",
nit
```suggestion
        "イベントを削除します。(間違ってイベントを作成した時以外は使わないでください。)",
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +            Option.when(args(1).toString != null)(GachaEventName(args(1).toString))
```suggestion
            Option(args(1).toString).map(GachaEventName)
```
https://www.scala-lang.org/api/2.13.3/scala/Option$.html#apply[A](x:A):Option[A] は`null`なら`None`を返します

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +                .whenA(!isExistsEvent)
nit:
```suggestion
                .unlessA(isExistsEvent)
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +              if (isExistsEvent) MessageEffect(s"${RED}指定されたイベント名のイベントが存在します。")
```suggestion
              if (isExistsEvent) MessageEffect(s"${RED}指定された名前のイベントがすでに存在します。")
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return 指定された名前のガチャイベントが存在するか確認する
```suggestion
   * @return 指定された名前のガチャイベントが存在するか確認する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return 現在作成されているガチャイベントの一覧を取得する
```suggestion
   * @return 現在作成されているガチャイベントの一覧を取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   *         ガチャイベントを作成すると、常時排出アイテムが自動コピーされます。
```suggestion
   * ガチャイベントを作成します。作成時、常時排出されるアイテムが自動的にコピーされます。
   * @return ガチャイベントを作成する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +  def allGachaPrizeList: F[Vector[GachaPrize[ItemStack]]]
@KisaragiEffective 「今の」とは、どの観点からの今なのか調べる

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * ガチャの景品リストを何らかの方法でロードする
```suggestion
   * ガチャの景品リストをロードする
```

この表現は冗長です

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * ガチャ景品リストにGachaPrizeを追加する
```suggestion
   * @return ガチャ景品リストにGachaPrizeを追加する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * ガチャ景品リストから指定された[[GachaPrizeId]]の[[GachaPrize]]を削除する
```suggestion
   * @return ガチャ景品リストから指定された[[GachaPrizeId]]の[[GachaPrize]]を削除する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * ガチャ景品リストを空にする
```suggestion
   * @return ガチャ景品リストを空にする作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * ガチャの景品リストを、与えたGachaPrizesListに置き換えを行う
```suggestion
   * @return ガチャの景品リストを、与えたGachaPrizesListに置き換えを行う作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * ガチャの景品リストを何らかの方法でロードする
```suggestion
   * @return ガチャの景品リストを何らかの方法でロードする作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/System.scala
> +                }
`fold`が使えます

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/domain/GachaPrizeListPersistence.scala
> +   * @return ガチャアイテムとして登録されているアイテムリストをGachaPrizeのVectorとして返す
```suggestion
   * @return ガチャアイテムとして登録されているアイテムの一覧
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/domain/GachaPrizeListPersistence.scala
> +   * @return ガチャリストを`gachaPrizesList`に設定する作用
```suggestion
   * @return ガチャリストを更新する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return `player`の`mineStackObject`を`amount`だけさせる作用
```suggestion
   * @return `player`の`mineStackObject`を`amount`だけ増加させる作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return `player`の`mineStackObject`を`amount`だけ減少させ、実際に減少させた量を返す
```suggestion
   * `player`の`mineStackObject`を`amount`だけ減少させます。
   * @return 実際に減少させた量を返す作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return `player`のMineStackUsageHistoryに`mineStackObject`を追加する
```suggestion
   * @return `player`のMineStackUsageHistoryに`mineStackObject`を追加する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[TryIntoMineStack]]を返す
もう少し具体的な説明を追加してください。現状のこのドキュメントはシグネチャから読み取れることしか記述されておらず、ほとんど価値がありません。

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return `player`が持っている`mineStackObject`の量を取得する
```suggestion
   * @return `player`が持っている`mineStackObject`の量を取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return `player`のMineStackUsageHistoryを取得する
```suggestion
   * @return `player`の使用履歴を取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return 現在のAutoMineStackのステータスを取得する
```suggestion
   * @return 現在、自動回収されるかどうかを返す作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/MineStackAPI.scala
> +   * @return [[MineStackObjectList]]を返す
`tryIntoMineStack`と同様、ほとんど中身がありません。

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +                  .map(isSucceed => if (itemStack != null && isSucceed) Some(index) else None)
Option.whenが使えます

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackSettings.scala
> +   * @return AutoMineStackをonに切り替えます
```suggestion
   * @return 自動収集を有効にする作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackSettings.scala
> +   * @return AutoMineStackをoffに切り替えます
```suggestion
   * @return 自動収集を無効にする作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackSettings.scala
> +   * @return 現在のステータスを取得します
```suggestion
   * 現在自動収集が有効になっているかを取得します
   * @return 有効になっていればtrue、なっていなければfalseを返す作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackSettings.scala
> +  def currentState: F[Boolean] = for {
```suggestion
  def isAutoCollectionTurnedOn: F[Boolean] = for {
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackSettings.scala
> +  def toggleAutoMineStackTurnOn: F[Unit] = for {
```suggestion
  def turnOnAutoCollect: F[Unit] = for {
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackSettings.scala
> +  def toggleAutoMineStackTurnOff: F[Unit] = for {
```suggestion
  def turnOffAutoCollect: F[Unit] = for {
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/MineStackUsageHistory.scala
> +   */
```suggestion
   * 指定されたアイテムを履歴に追加します。
   * ただし、履歴の数が保存できる最大エントリ数を超えていた場合、古い方から削除されます。
   * @return 履歴を更新する作用
   */
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/TryIntoMineStack.scala
> +   * @return 格納ができたかどうか
```suggestion
   * @return 格納ができたかどうかを表す作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/minestackobject/MineStackObjectList.scala
> +   * @return [[MineStackObject]]をすべて返します
```suggestion
   * @return [[MineStackObject]]をすべて返す作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/minestackobject/MineStackObjectList.scala
> +   * @return [[ItemStack]]から[[MineStackObject]]を取得します
```suggestion
   * @return [[ItemStack]]から[[MineStackObject]]を取得しようとする作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/minestackobject/MineStackObjectList.scala
> +   * `category`を指定してすべての[[MineStackObjectGroup]]を取得します。
```suggestion
   * @return `category`を指定してすべての[[MineStackObjectGroup]]を取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/domain/minestackobject/MineStackObjectList.scala
> +   * @return `name`から[[MineStackObject]]を取得します
```suggestion
   * @return `name`から[[MineStackObject]]を取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return [[ItemStack]]から[[GachaPrize]]を通常排出アイテム一覧から取得する
```suggestion
   * @return [[ItemStack]]から[[GachaPrize]]を通常排出アイテム一覧から取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * 指定された[[GachaPrizeId]]に対応する[[GachaPrize]]が存在するか確認する
```suggestion
   * 指定された[[GachaPrizeId]]に対応する[[GachaPrize]]が存在するか確認する
   * @return 存在するならtrue、存在しないならfalseを返す作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return すべてのガチャ景品を取得する
```suggestion
   * @return すべてのガチャ景品を取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return 今のガチャ景品リストを取得する
```suggestion
   * @return 今のガチャ景品リストを取得する作用
```

2022-11-27 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return 指定された[[GachaEventName]]のイベントが存在すれば返す。
```suggestion
   * 指定された[[GachaEventName]]のイベントが存在するか調べる
   * @return 存在すれば`true`、存在しないなら`false`
```

2022-12-26 18:31 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/generic/ListExtra.scala
> +   */
```suggestion
  /**
   * 与えられたListにおいて、述語に合致する要素を全て取り除いた上で先頭に追加します。
   * @param list 処理対象
   * @param predicate 述語
   * @param element 先頭に追加するために、述語で検索した結果を移す関数。`Option.get`は例外の原因となりえることに注意。
   * @return Listの中身で条件に一致するものがあれば一番最初に見つかった要素と同値のもの全てを取り除いてからその要素を先頭に追加したListを返し、
   * 一致するものがなければ`element(None)`を先頭に追加します
   */
```

2022-12-26 18:31 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
> +      BreakUtilから呼び出されている都合上publicやむを得ずになっている。*/
```suggestion
      BreakUtilから呼び出されている都合上やむを得ずpublicになっている。*/
```

2022-12-27 15:18 UTC, rito528 commented
再レビューお願いします。

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/generic/algebra/Cloneable.scala
> +package com.github.unchama.generic.algebra
代数ではなさそうなので`generic`直下に置くべきではないでしょうか？

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
> +      BreakUtilから呼び出されている都合上やむを得ずpublicになっている。*/
```suggestion
  /* TODO: mineStackSystemは本来privateであるべきだが、mineStackにアイテムを格納するAPIが現状の
      BreakUtilの実装から呼び出されている都合上やむを得ずpublicになっている。*/
```

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/VotingFairyListener.scala
> +      val gachaimoObject =
現在のガチャりんごが歴史的経緯によりDB上で`gachaimo`という文字列において特定されるだけなので、`gachaimo`にこだわる必要はありません
```suggestion
      val gachaRingo =
```

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/VotingFairyListener.scala
> +      val l = mineStackAPI
```suggestion
      val quantity = mineStackAPI
```

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +      case Left(mineStackObject: MineStackObject[ItemStack]) =>
```suggestion
      case Left(mineStackObject) =>
```

明示的な型注釈は不要かと思います。

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/minestack/MineStackButtons.scala
> +              }
`Option.fold`が使えます

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +  final def isExistsGachaEvent(gachaEventName: GachaEventName): F[Boolean] = for {
```suggestion
  final def existsGachaEvent(gachaEventName: GachaEventName): F[Boolean] = for {
```

cf. https://qiita.com/yskszk/items/5a7f99c974773f03a82a

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return `gachaPrizeId`に対応する[[GachaPrize]]作用
```suggestion
   * @return `gachaPrizeId`に対応する[[GachaPrize]]を返す作用
```

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/GachaPrizeAPI.scala
> +   * @return ガチャの景品リストを`gachaPrizesList`に置き換えを行う作用
nit:

```suggestion
   * @return ガチャの景品リストを`gachaPrizesList`に置き換える作用
```

2022-12-29 10:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +                  .map(isSucceed => Option.when(itemStack != null && isSucceed)(index))
@KisaragiEffective これどうにかなりそう

2022-12-29 13:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +                  .map(isSucceed => Option.when(itemStack != null && isSucceed)(index))
ガード節を使ってちょっとだけ単純にしてみました

2022-12-29 13:40 UTC, rito528 commented
再レビューお願いします。

2022-12-30 11:03 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +              isExistsEvent <- gachaPrizeAPI.existsGachaEvent(eventName)
```suggestion
              existsEvent <- gachaPrizeAPI.existsGachaEvent(eventName)
```

2022-12-30 15:48 UTC, KisaragiEffective approved these changes

2022-12-30 15:49 UTC, merged