ガチャ券まとめ引き機能の追加 #281
GiganticMinecraft/SeichiAssist pull request #1732
Opened 2022-11-09 17:50 UTC by haruyan-hopemucci

close #281 

- 棒メニュー2ページ目にまとめ引きボタンを配置（アイコンはPAPER）
- 左クリックでまとめ引き回数をトグル指定。1000回、5000回、10000回の3パターンをトグルする。
  - クリックする度に 1000->5000->10000->1000 ... と変化する
- 右クリックで実際に指定回数ガチャを回す

レビューをお願いします。

2022-11-09 22:18 UTC, rito528 requested changes

2022-11-09 22:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
これ、drawGacha関数の返り値をKleisli[, Player, Unit]にすることによってunsafeRunAsyncせずともDeferredEffect内に突っ込むことができます

2022-11-10 05:09 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
`drawGacha`関数の戻り値を`Kleisli[, Player, Unit]`にすることで`DeferredEffect`内で処理することができるようになりましたが、既存のガチャ券からガチャを引くことができなくなりました。
既存の処理側でも戻り値の変更にあうようにAPI実行時の処理方法を変更する必要があると思われますが、現状どのようにすればよいかが思いつきません。

2022-11-10 05:24 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/System.scala
> +                  .as(())
```suggestion
                  .void
```

2022-11-10 05:24 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/System.scala
> +                  .as(())
```suggestion
                  .void
```

2022-11-10 07:24 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
どのように実装しましたか？

2022-11-10 08:34 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +import cats.effect.implicits.toEffectOps
```suggestion
import cats.effect.implicits._
```

2022-11-10 08:38 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
完全に推測ですが、
```scala
DeferredEffect(IO {
    gachaPointAPI.consumeGachaPoint(
      GachaPoint.gachaPointBy(currentConsumeGachaTicketAmount.value)
    )
    gachaAPI
    .drawGacha(player, currentConsumeGachaTicketAmount.value)
}),
```
のように実装していませんか？
これだと最後の`drawGacha`のみが実行されます

なので、

```scala
DeferredEffect(IO {
    gachaPointAPI.consumeGachaPoint(
      GachaPoint.gachaPointBy(currentConsumeGachaTicketAmount.value)
    )
} >> IO(gachaAPI.drawGacha(player, currentConsumeGachaTicketAmount.value))),
```

のようにすると動くと思います

2022-11-10 08:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +          environment.gachaAPI.consumeGachaTicketAmount(player).map { amount =>
```suggestion
          gachaAPI.consumeGachaTicketAmount(player).map { amount =>
```

2022-11-10 08:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +          }
```suggestion
        _ <-if (isInventoryFull) {
            Sync[F].delay(InventoryOperations.addItem(player, newItemStack))
          } else {
            InventoryOperations.grantItemStacksEffect(newItemStack).apply(player)
          }
```

scalafix等でこうなったのであればこのままで構いませんが、`if`式の部分を上に書きませんか？

2022-11-10 08:43 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/ConsumeAmount.scala
> +abstract class ConsumeAmount(val value: Int)
どういうものを列挙したクラスなのか、ドキュメントがほしいです。

2022-11-10 08:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/ConsumeAmount.scala
> +}
```suggestion
object ConsumeAmount {

  case object oneThousand extends ConsumeAmount(1000)
  
  case object fiveThousands extends ConsumeAmount(5000)
  
  case object tenThousands extends ConsumeAmount(10000)
  
}
```

2022-11-10 08:45 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +  val consumeGachaTicketAmountReference: Ref[F, ConsumeAmount] =
```suggestion
  private val consumeGachaTicketAmountReference: Ref[F, ConsumeAmount] =
```

`consumeGachaTicketAmountReference`は`private`であって欲しいです。

2022-11-10 08:45 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +  }
```suggestion
  }
  
```

2022-11-10 08:45 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +  def toggleConsumeGachaTicketAmount(): F[Unit] = {
どのような作用をもたらすのかのドキュメントがほしいです。
`consumeGachaTicketAmount`も同様。

2022-11-10 08:46 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/GachaPointApi.scala
> +   * プレーヤーのガチャポイントを消費する作用。
```suggestion
   * @return プレーヤーのガチャポイントを消費する作用。
```

2022-11-10 08:49 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakcount/domain/level/SeichiExpAmount.scala
> +  def consume(a: SeichiExpAmount): SeichiExpAmount = mapAmount(_ - a.amount)
```suggestion
  def subtract(a: SeichiExpAmount): SeichiExpAmount = mapAmount(_ - a.amount)
```

`add`関数の逆のことをやる関数なので、`consume`ではなく`subtract`のほうが良さそうです

2022-11-10 08:50 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  def consume(point: GachaPoint): GachaPoint = GachaPoint(exp.consume(point.exp))
```suggestion
  def subtract(point: GachaPoint): GachaPoint = GachaPoint(exp.consume(point.exp))
```
`add`関数の逆のことをやる関数なので、`consume`ではなく`subtract`のほうが良さそうです

2022-11-10 10:01 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
APIの`drawGacha`関数は以下の様にKleisliで返し、
com/github/unchama/seichiassist/subsystems/gacha/System.scala
```scala
              override def drawGacha(draws: Int): Kleisli[F, Player, Unit] =
                Kleisli { player =>
                  new BukkitDrawGacha[F](gachaPrizesListReference).draw(player, draws)
                }
```
clickのeffectを実行する部分は、
com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
```scala
                  SequentialEffect(
                    // 無暗に連打させないよう、まとめ引き時にメニューを閉じる
                    closeInventoryEffect,
                    DeferredEffect(IO {
                      gachaPointAPI.consumeGachaPoint(
                        GachaPoint.gachaPointBy(currentConsumeGachaTicketAmount.value)
                      )
                    }),
                    DeferredEffect(IO {
                      gachaAPI.drawGacha(currentConsumeGachaTicketAmount.value)
                    })
                  )
```
とすることでまとめ引きの方は問題なく動作しました。
この変更で戻り値の型が変わったため、ガチャ券を消費してガチャを引く処理の方も合わせて変更しているのですが、そちらのほうのdrawが動作していない状態です。

変更箇所を別ブランチにあげましたので一度見ていただけたらと思います。
https://github.com/haruyan-hopemucci/SeichiAssist/commit/03cf3ddd22d334744bbe130fab8fad79f6175a1c

2022-11-10 10:17 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +          }
IDEコードスタイル設定の「保存時に整形」を有効にしていると上記の様に改行されるようです。scalafmt等では発生しません。
保存時に整形をオフにしたら改行されなくなりました。
個人的には自動整形オンのほうが良いのですが、見苦しいのであれば自動整形はオフにします。

2022-11-10 10:19 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +          }
であればそのままでも大丈夫です。

2022-11-10 10:32 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/ConsumeAmount.scala
> +abstract class ConsumeAmount(val value: Int)
ドキュメントを追加します。
また、`ConsumeAmount`という名称だと「何が」が足りないので`GachaTicketConsumeAmount`にクラス名を変更します。

2022-11-10 10:48 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +          }
scalafmtでも改行されることを確認しました。そのままで行きたいと思います。

2022-11-10 12:09 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
コメントをつけました。

2022-11-10 14:34 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
私も疑問点をあちらのリポジトリにコメントしましたので見ていただけると嬉しいです。

2022-11-10 14:55 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
返信しました

2022-11-10 15:19 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                        .unsafeRunAsyncAndForget()
7dbd523 で解決しました。

2022-11-10 15:23 UTC, haruyan-hopemucci commented
指摘事項は全て解決できたので再レビューをお願いします

2022-11-11 05:39 UTC, rito528 requested changes

2022-11-11 05:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/BukkitGrantLevelUpGift.scala
>    }
カッコを消していいと思います

2022-11-11 05:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/System.scala
> +            }
gachaPointRepositoryControls.repositoryを変数として持ったほうが良いと思います。

2022-11-11 05:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaTicketConsumeAmount.scala
> + * ガチャ券を消費する量を定義する。
どういうときにガチャ券を消費するかという情報が不足しているので、このドキュメントは曖昧だと思います。

2022-11-11 05:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +   * プレイヤー毎に保持している一括まとめ引きガチャ券の消費枚数を切り替える作用
```suggestion
   * @retuen プレイヤー毎に保持している一括まとめ引きガチャ券の消費枚数を切り替える作用
```

2022-11-11 05:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/GachaAPI.scala
> +  def consumeGachaTicketAmount(player: Player): F[GachaTicketConsumeAmount]
これらの関数はconsumeGachaTicketAPIとして切り出して良いと思います。

2022-11-11 05:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +        lazy val rightClickButtonEffect =
```suggestion
        val rightClickButtonEffect =
```

2022-11-11 07:28 UTC, rito528 requested changes

2022-11-11 07:28 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +                val gachaTicketLeft = currentGachaPoint.availableTickets
```suggestion
                val currentGachaTicketAmount = currentGachaPoint.availableTickets
```

2022-11-11 07:28 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +      val newItemStack = prize.materializeWithOwnerSignature(player.getName)
これは副作用が含まれるので、forの中に入れて処理をしたいです。

2022-11-11 07:28 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +    Map[GachaTicketConsumeAmount, GachaTicketConsumeAmount](
```suggestion
    Map(
```

これは型推論が使えます。

2022-11-11 09:10 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +    Map[GachaTicketConsumeAmount, GachaTicketConsumeAmount](
型推論させると`GachaTicketConsumeAmount with Product`に推論されてしまいました。`GachaTicketConsumeAmount`に`Product`をミックスインすると今度は`GachaTicketConsumeAmount with java.io.Serializable` に推論される…という感じで目的の型に推論されないので明示的に型を指定する方法に戻すことにします。

2022-11-11 11:23 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +    Map[GachaTicketConsumeAmount, GachaTicketConsumeAmount](
では
```scala
private val toggleConsumeGachaTicketAmountOrder: Map[GachaTicketConsumeAmount, GachaTicketConsumeAmount]
 = Map(...)
```
のようにするとどうでしょうか。

2022-11-11 11:45 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaDrawSettings.scala
> +    Map[GachaTicketConsumeAmount, GachaTicketConsumeAmount](
上記の方法でうまくいきました！

2022-11-11 12:24 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +      val newItemStack = prize.materializeWithOwnerSignature(player.getName)
副作用はなさそうに見えますが、とりあえずfor式の中に入れます。

2022-11-11 15:45 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/actions/BukkitGrantGachaPrize.scala
> +          }
`grantItemStacksEffect`はインベントリに入りきらなかったアイテムをドロップするようにできているので、インベントリがフルかどうか判定せずアイテムを入れてしまっても構わないはずなので、`addItem`への分岐は削除します。
インベントリがフルかどうかはコール元で使用しているのでそのまま残します。

2022-11-11 18:46 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/GachaAPI.scala
> +  def consumeGachaTicketAmount(player: Player): F[GachaTicketConsumeAmount]
gachaのsubsystemとして切り出しました。

2022-11-12 01:33 UTC, rito528 requested changes

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/System.scala
> +  ]: SyncEffect: ContextCoercion[*[_], F]](
```suggestion
  def wired[F[_]: OnMinecraftServerThread: NonServerThreadContextShift: ConcurrentEffect](
```

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/domain/GachaTicketConsumeAmount.scala
> +package com.github.unchama.seichiassist.subsystems.gacha.domain
`comsumerGachaTicketAmount`をgachaのsubsystemとして切り出すならば、consumeGachaTicketAmountのsystem内の`domain`に含まれるべきだと思います。

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/System.scala
> +            private val consumeGachaTicketSettingRepository =
```suggestion
            val consumeGachaTicketSettingRepository =
```

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/System.scala
> +  def wired[F[_]: OnMinecraftServerThread: NonServerThreadContextShift: ConcurrentEffect, G[
```suggestion
  def wired[F[_]: Sync, G[
```

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/domain/ConsumeGachaTicketSettings.scala
> +      )
```suggestion
      _ <- consumeGachaTicketAmountReference.update { oldValue =>
        toggleConsumeGachaTicketAmountOrder(oldValue)
      }
```

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/System.scala
> +      gachaPointRepositoryControlsRepository = gachaPointRepositoryControls.repository
これは`System`の構築時にローカル変数に入れて良いと思います。

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +    val gachaAPI: GachaAPI[IO, ItemStack, Player],
```suggestion
```

2022-11-12 01:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/TopLevelRouter.scala
> +    gachaAPI: GachaAPI[IO, ItemStack, Player],
```suggestion
```

2022-11-12 04:45 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/System.scala
> +            private val consumeGachaTicketSettingRepository =
privateを外し、型アノテーションを追加します。

2022-11-12 04:58 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/SecondPage.scala
> +    val gachaAPI: GachaAPI[IO, ItemStack, Player],
まとめ引きのeffect内で`gachaAPI.drawGacha`を呼んでいるのでこれは削除することができませんでした。

2022-11-12 04:59 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/menus/TopLevelRouter.scala
> +    gachaAPI: GachaAPI[IO, ItemStack, Player],
まとめ引きのeffect内でgachaAPI.drawGachaを呼んでいるのでこれは削除することができませんでした。

2022-11-12 05:25 UTC, rito528 requested changes
otherwise LGTM

2022-11-12 05:25 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/ConsumeGachaTicketAPI.scala
> +object ConsumeGachaTicketAPI {
```suggestion
object ConsumeGachaTicketAPI {

```

2022-11-12 05:25 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/System.scala
> +
```suggestion
```

2022-11-12 05:25 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/System.scala
> +      new System[F] {
```suggestion
      new System[F] {
      
```

2022-11-12 05:25 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/domain/ConsumeGachaTicketSettings.scala
> +   * @retuen プレイヤー毎に保持している一括まとめ引きガチャ券の消費枚数を切り替える作用
```suggestion
   * @return プレイヤー毎に保持している一括まとめ引きガチャ券の消費枚数を切り替える作用
```

2022-11-12 06:14 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/subsystems/consumeGachaTicket/domain/ConsumeGachaTicketSettings.scala
> +   * @retuen プレイヤー毎に保持している一括まとめ引きガチャ券の消費枚数を切り替える作用
https://dic.nicovideo.jp/a/typoglycemia
気づけよ自分...

2022-11-12 06:31 UTC, rito528 reviewed
scalafmtが通ればLGTMです

2022-11-12 06:42 UTC, haruyan-hopemucci commented
空行にスペースが入っているとscalafmtではじかれるわけですね...
(suggestがそのまま空行を入れてしまう)

2022-11-12 06:51 UTC, rito528 approved these changes
LGTM.
お疲れ様でした！

2022-11-12 06:51 UTC, merged