/gacha getコマンドで、記名する名前を指定できることになっているが、実際には指定できないバグの修正
GiganticMinecraft/SeichiAssist pull request #1737
Opened 2022-11-14 07:26 UTC by haruyan-hopemucci

close #1704

元々修正対象だったガチャコマンドの`grantGachaPrize(commandSender)`の引数`commandSender`はプレイヤー名取得以外の用途でも使われていたので、`grantGachaPrize`において記名用の引数とプレイヤーオブジェクトの引数を分離しました。
その影響で、通常ガチャをdrawする処理にも修正が入っています。

2022-11-14 08:20 UTC, KisaragiEffective requested changes

2022-11-14 08:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            }
53行目のヘルプメッセージを実装に合わせてください

2022-11-14 08:22 UTC, rito528 requested changes

2022-11-14 08:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            }
```suggestion
            else 
              context.args.yetToBeParsed.head
```

2022-11-14 08:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            }
これは、「入力がなければ記名をしない」ということもしたいです。

2022-11-14 08:41 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            }
53行目はgiveコマンドの説明になっていますが、giveコマンドの説明と実装が合っていないということでしょうか？

2022-11-14 08:45 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            }
コマンド実行者の名前での記名はしない、となるということでOKでしょうか？

2022-11-14 08:48 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            }
はい

2022-11-14 15:27 UTC, haruyan-hopemucci commented
きさらぎさんの指摘以外は解消しました。
再レビューをお願いします。

2022-11-14 22:06 UTC, rito528 requested changes

2022-11-14 22:06 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/application/actions/GrantGachaPrize.scala
> +    optionOwnerName: Option[String]
この変数名、型がOptionであることは明確なので単にownerNameで良いと思います。
ほかも同様

2022-11-15 04:16 UTC, rito528 requested changes

2022-11-15 04:16 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/application/actions/GrantGachaPrize.scala
> +    ownerName: Option[String]
MineStackというシステムは、プレイヤー名以外の記名があった場合には別アイテムとして扱われるため、この引数は不要になるべきであると考えています。

2022-11-15 04:16 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +            _ <- new BukkitGrantGachaPrize[F]().grantGachaPrize(gachaPrize.get, ownerName)(
ここでは運営コマンドにより実行されたものを付与するということなので、MineStackに入れずに直接プレイヤーに付与をした方が良いと思います。
(insertIntoInventoryOrDropが呼び出されるべき)

2022-11-15 09:19 UTC, rito528 approved these changes
LGTM.

2022-11-15 09:20 UTC, merged