feat: GT交換の個数を修正
GiganticMinecraft/SeichiAssist pull request #1758
Opened 2022-11-15 15:16 UTC by Lucky3028

2022-11-16 08:18 UTC, rito528 requested changes
otherwise LGTM.

2022-11-16 08:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/tradesystems/subsystems/gachatrade/bukkit/listeners/GachaTradeListener.scala
> +            .map(_.amount)}個認識しました。"
・`filter` + `map`は`collect`関数が使えます。
・`tradableItemStacks`は`Vector`で、`map`しても個々の値を持つ`Vector`なので最後に`sum`をしてください。
・個数を変数に切り出したほうが良さそうです

2022-11-16 08:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/tradesystems/subsystems/gachatrade/bukkit/traderules/BukkitTrade.scala
> +          (TradeSuccessResult(
```suggestion
          TradeSuccessResult(
```

2022-11-16 08:18 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/tradesystems/subsystems/gachatrade/bukkit/traderules/BukkitTrade.scala
> +          ))
```suggestion
          )
```

2022-11-17 07:29 UTC, KisaragiEffective approved these changes

2022-11-17 07:31 UTC, merged