/gacha getコマンドで、アイテムID=0を指定できない不具合の修正
GiganticMinecraft/SeichiAssist pull request #1764
Opened 2022-11-20 09:41 UTC by haruyan-hopemucci

close #1736

2022-11-21 01:37 UTC, rito528 requested changes

2022-11-21 01:37 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +        .argumentsParsers(List(getGachaPrizeIdExistsParser))
gachaPrizeIdExistsParserの許容範囲を0以上のIntとして、PrizeIdが0だったときにはガチャリンゴを返すとしたほうが良いと思います。

2022-11-21 02:58 UTC, rito528 requested changes

2022-11-21 02:58 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/GachaAPI.scala
> +    else prizes.find(_.id == gachaPrizeId)
```suggestion
  } yield {
    if (gachaPrizeId.id == 0)
      Some(
        GachaPrize(
          staticGachaPrizeFactory.gachaRingo,
          GachaProbability(1.0),
          signOwner = false,
          GachaPrizeId(0)
        )
      )
    else prizes.find(_.id == gachaPrizeId)
   }
```

2022-11-21 03:06 UTC, haruyan-hopemucci commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +        .argumentsParsers(List(getGachaPrizeIdExistsParser))
`gachaPrizeIdExistsParser`は`get`の他にも`remove`,`setProbability`,`setAmount`で使用されていますが、こちらのId下限も0にしてしまって問題ないのでしょうか？

2022-11-21 05:05 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/command/GachaCommand.scala
> +        .argumentsParsers(List(getGachaPrizeIdExistsParser))
あ～～
それならダメそうですね...
このレビューは見なかったことにしてください。

2022-11-23 05:30 UTC, rito528 approved these changes
LGTM.

2022-11-23 05:30 UTC, merged