デバッグ環境でitzgさんのDockerイメージを使う
GiganticMinecraft/SeichiAssist pull request #1787
Opened 2022-12-30 14:01 UTC by rito528

closes #1668,#1673

2022-12-30 14:03 UTC, Lucky3028 approved these changes

2022-12-30 14:23 UTC, Lucky3028 approved these changes

2022-12-30 14:40 UTC, KisaragiEffective requested changes
otherwise LGTM

2022-12-30 14:40 UTC, KisaragiEffective commented on docker-compose.yml
> +      - EULA=TRUE
`README.md`から`eula.txt`に関連する部分を消してください

2022-12-30 14:40 UTC, KisaragiEffective commented on docker-compose.yml
> +      - spigot_b:/data
```suggestion
      - spigot_b:/data
      - ./localDependencies:/plugins
```

2022-12-30 14:40 UTC, KisaragiEffective commented on docker-compose.yml
> +      - ./localDependencies:/plugins
SeichiAssistを明示的にコピーする処理が必要です

2022-12-30 15:05 UTC, rito528 commented
修正しました。
再レビューお願いします。

2022-12-30 16:15 UTC, rito528 commented
いや更新されてないな

2022-12-30 18:05 UTC, rito528 commented
これ実際に動作確認して動いていたんですが、実際には残っていたキャッシュで動いていたようで、現状のままだと全然動かないですね。
もう少し試行錯誤してみます

2023-01-02 12:44 UTC, rito528 commented
修正しました。
レビューお願いします。

SQLのミスでガチャデータのロードに失敗してSeichiAssistが起動しない状態だったので、やむを得ずそこも直してあります。

2023-01-02 12:56 UTC, Lucky3028 requested changes

2023-01-02 12:56 UTC, Lucky3028 commented on docker/spigot/update-seichiassist.sh
> +/start
謎に`/start`を実行するようにみえるので、itzg/minecraft-serverのものという旨を明記したほうがよさそうです

2023-01-02 12:56 UTC, Lucky3028 commented on docker/spigot/Dockerfile
> +FROM ghcr.io/giganticminecraft/chunk-search-rs:sha-598517c as chunk-search-provider
```suggestion
# syntax=docker/dockerfile:1.4
FROM ghcr.io/giganticminecraft/chunk-search-rs:sha-598517c as chunk-search-provider
```
とした上で、各`COPY`に`--link`をつけたほうがよさそうです
See: https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md#copy---link

2023-01-02 13:12 UTC, rito528 commented
修正しました。
再レビューお願いします。

2023-01-02 13:17 UTC, Lucky3028 approved these changes

2023-01-02 13:17 UTC, Lucky3028 commented on docker/spigot/update-seichiassist.sh
> +  .RedisBungee.redis-port = \"$REDIS_PORT\""
RedisBungeeは使わなくなったのでこの設定はいらなさそうです
（config.ymlも書き換える必要がありそう？）

2023-01-02 14:00 UTC, rito528 commented on docker/spigot/update-seichiassist.sh
> +  .RedisBungee.redis-port = \"$REDIS_PORT\""
デバッグ環境では使ってませんが、本番環境ではRedisBungeeを使っている?ので書き換えるのはまずくないですか？

2023-01-02 14:02 UTC, Lucky3028 commented on docker/spigot/update-seichiassist.sh
> +  .RedisBungee.redis-port = \"$REDIS_PORT\""
はい、括弧内はメモ程度に書きました

2023-01-02 14:08 UTC, rito528 commented on docker/spigot/update-seichiassist.sh
> +  .RedisBungee.redis-port = \"$REDIS_PORT\""
デバッグだけ消してみましたが、消すと実行時に接続できないと怒られるのでこのままが良さそうですね

2023-01-02 14:08 UTC, Lucky3028 commented on docker/spigot/update-seichiassist.sh
> +  .RedisBungee.redis-port = \"$REDIS_PORT\""
なるほど、じゃあOKです

2023-01-02 14:22 UTC, merged