docs: コーディングガイドラインの作成
GiganticMinecraft/SeichiAssist pull request #1908
Opened 2023-02-21 01:43 UTC by KisaragiEffective

# THIS PR IS WIP!!

2023-04-08 12:45 UTC, KisaragiEffective reviewed
docs: improve

2023-04-08 12:45 UTC, KisaragiEffective commented on CODING_GUIDELINE.md
> +(TODO)
```suggestion
```

時が経つにつれて陳腐化するので要らない

2023-04-08 12:45 UTC, KisaragiEffective commented on CODING_GUIDELINE.md
> +
```suggestion

各サブシステムはそれぞれ他のサブシステムで使うことを想定したAPIを `trait` として持ち、各サブシステムはその抽象に対してのみ依存することができます。サブシステムの実装はAPIに具象的な実装を与える必要があります。

関心事同士の依存 (例: 整地スキルによってマナを減少させるためにマナを操作する) は 抽象の型を `implicit` パラメーターとして渡すことにより表現されます。

抽象同士の循環参照は推奨されません。

新しくサブシステムを作った場合、`SeichiAssist.scala` 内で初期化することを忘れないでください。初期化を忘れると正しく機能しません。
```

2023-07-25 11:49 UTC, KisaragiEffective commented
ready for review

2023-07-25 12:16 UTC, KisaragiEffective commented on CODING_GUIDELINE.md
> +抽象同士の循環参照は推奨されません。
```scala
class A(implicit val b: B) {}
class B(implicit val a: A) {}
```

という例 ([scastie](https://scastie.scala-lang.org/DvSCahrIRJO3xZthIX8peg)) を考えるならコンパイル**自体**は通りますが、uselessであることに変わりはない (`A`と`B`のどちらを先にインスタンス化しようとしても、`implicit`が必要ないインスタンスの作成方法がない。よって、もう片方を先に作らなければならないが、それはコンパイルに失敗する) ので削除します

2023-07-25 12:20 UTC, KisaragiEffective commented
そこまでメンテナ間の合意形成にこだわる意味ははっきり言って私には理解できませんが、アイデア会議でドキュメントを作成するというチケットが承認された状態である以上、この文章を置いておくことはドキュメント自体のメンテナンスの問題と天秤にかけた時に一つの局所解であると考えます。
これに納得がいかないのであればこのPRを閉じてください。

2023-07-25 12:21 UTC, inductor commented
@KisaragiEffective なぜこのPRが作られたかという経緯がPR descriptionにないため、レビュアーの認知負荷が高くなるという話をしています。
関連チケットがあればそのリンクは貼るべきです。

2023-07-25 12:23 UTC, KisaragiEffective commented
(最初からそう言ってもらえればちゃんと対応しました)

2023-07-25 12:24 UTC, inductor commented
(そのような文章を書いたつもりでした)

2023-07-25 12:24 UTC, inductor commented
Fix typoなどであれば別に空descriptionに異論はないですが、明らかにガイドライン策定は複数人を巻き込んでやるものなので、関連資料やIssue番号などを貼るのは当然という認識です

2023-07-25 12:25 UTC, KisaragiEffective commented
それはあなたの暗黙の認識なので、最初に共有されて然るべきだと私は考えます。

2023-07-25 12:27 UTC, inductor commented
(コレを作ってるのってきさらぎさん自身では・・・ https://github.com/GiganticMinecraft/SeichiAssist/pull/2144/files#diff-1a20932f7082c95d067266994d998321567f447d29a9bd8e01159af374e03a09 )

2023-07-25 12:32 UTC, KisaragiEffective commented
いいえ:

1. PR descriptionのテンプレートは @m1sk9 が作ったものです (敬称略)。
2. Issueのテンプレートはマージされていない以上指摘には当たらないと考えます。

2023-08-07 18:28 UTC, m1sk9 requested changes

2023-08-07 18:28 UTC, m1sk9 commented on CODING_GUIDELINE.md
> +新しくサブシステムを作った場合、`SeichiAssist.scala` 内で初期化することを忘れないでください。初期化を忘れると正しく機能しません。
```suggestion
各サブシステムはそれぞれ他のサブシステムなどで使うことを想定したAPIを`trait`として持ち、各サブシステムはその抽象に対してのみ依存することができます。サブシステムの実装はAPIに具象的な実装を与える必要があります。APIの名前はおおよそ`Api`か`API`で終わります。

関心事同士の依存 (例: 整地スキルによってマナを減少させるためにマナを操作する) は 抽象の型を`implicit`パラメーターとして渡すことにより表現されます。

新しくサブシステムを作った場合、`SeichiAssist.scala`内で初期化することを忘れないでください。初期化を忘れると正しく機能しません。
```

ここだけスペースがあるのが気になる
(意図的な変更なら resolve してください)

2023-08-09 09:22 UTC, m1sk9 approved these changes

2023-08-09 10:20 UTC, merged