feat: 他のメビウスの素材の選択肢を追加
GiganticMinecraft/SeichiAssist pull request #1930
Opened 2023-03-20 16:38 UTC by lis2a

close #1435

2023-03-20 17:30 UTC, rito528 requested changes

2023-03-20 17:30 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/domain/property/MebiusForcedMaterial.scala
>      override def next: MebiusForcedMaterial = None
```suggestion
    override def next: MebiusForcedMaterial = Gold
```

2023-03-20 17:30 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/domain/property/MebiusForcedMaterial.scala
> +    override def next: MebiusForcedMaterial = Chain
```suggestion
    override def next: MebiusForcedMaterial = None
```

2023-03-20 17:30 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/domain/property/MebiusForcedMaterial.scala
6行目付近のコメントの
`「30レベル以上でのみ革に戻すことができる」という機能`
とは変わってしまっているので、ドキュメントの更新が必要だと思います。

2023-03-20 18:33 UTC, lis2a commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/domain/property/MebiusForcedMaterial.scala
fixed in 25ab3e2

2023-03-21 03:40 UTC, rito528 requested changes
Otherwise LGTM.

2023-03-21 03:40 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/domain/property/MebiusForcedMaterial.scala
> +
nit: 下のようにするか、LeatherとNoneも`allowedAt`と`next`関数の間に空行を入れるといいと思います。

```suggestion
    override def next: MebiusForcedMaterial = Iron
  }

  // 鉄
  case object Iron extends MebiusForcedMaterial {
    override def allowedAt(level: MebiusLevel): Boolean = level >= MebiusLevel(30)
    override def next: MebiusForcedMaterial = Chain
  }

  // チェーン
  case object Chain extends MebiusForcedMaterial {
    override def allowedAt(level: MebiusLevel): Boolean = level >= MebiusLevel(30)
```

2023-03-21 03:40 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/domain/property/MebiusForcedMaterial.scala
> + * 『30レベル以上で革や鉄、金、チェーンなどの素材に変更できる』機能。
```suggestion
 * 『30レベル以上で革や鉄、金、チェーンなどの素材に変更できる』機能のため。
```

2023-03-21 05:02 UTC, rito528 commented
(解決したら、Resolve conversationを押していっていいですよ)

2023-03-21 05:02 UTC, rito528 approved these changes
LGTM👍👍

2023-03-21 05:02 UTC, merged