refactor: `/rmp removeAll` の削除
GiganticMinecraft/SeichiAssist pull request #1934
Opened 2023-03-24 16:27 UTC by lis2a

close #1765 

他の人にアサインがかかっていましたが、 そこまで複雑なものではなさそうだったのでやりました

2023-03-24 16:39 UTC, lis2a commented
https://github.com/GiganticMinecraft/SeichiAssist/pull/1934/commits/0ec6a14919e6a5ac2f44b0a7ec2ad08f086db3e4, コミットメッセージミスりました、GPG鍵でコミット署名をしているからか、 reword commit が出来ないので最悪 squash でも大丈夫です

2023-03-24 17:03 UTC, rito528 requested changes

2023-03-24 23:48 UTC, Lucky3028 requested changes
りとさんのご指摘に加えてこれもお願いします。

2023-03-24 23:48 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala
> +      case None | Some(false) => MessageEffect(s"第一整地以外の保護をかけて整地する整地ワールドでのみ使用出来ます")
```suggestion
      case None | Some(false) => MessageEffect(s"第1整地以外の保護をかけて整地する整地ワールドでのみ使用出来ます")
```

2023-03-24 23:56 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala
> +      case None | Some(false) => MessageEffect(s"第一整地以外の保護をかけて整地する整地ワールドでのみ使用出来ます")
パターンのほうがわかりやすいのでは

2023-03-25 02:57 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala
> +      case None | Some(false) => MessageEffect(s"第一整地以外の保護をかけて整地する整地ワールドでのみ使用出来ます")
言われてみればそうかも...

2023-03-25 14:02 UTC, Lucky3028 approved these changes

2023-03-25 17:05 UTC, rito528 approved these changes
LGTM

2023-03-25 17:05 UTC, merged