docs: CONTRIBUING.md に整地ワールドに関する情報を追加
GiganticMinecraft/SeichiAssist pull request #1944
Opened 2023-04-11 15:54 UTC by lis2a

`world_SW` を作成しないと整地Lv.が上昇しないので、その趣旨を書いとく。

2023-04-11 17:24 UTC, KisaragiEffective requested changes

2023-04-11 17:24 UTC, KisaragiEffective commented on CONTRIBUTING.md
> +整地ワールドを作成する場合、OP権限を付与したプレイヤーかアタッチしたシェルから `mvcreate world_SW normal` を実行します。
コンソール

2023-04-11 17:24 UTC, KisaragiEffective commented on CONTRIBUTING.md
> +`spigota` または `spigotb` へのコンテナにアタッチする必要があります。
への→の

2023-04-11 17:24 UTC, KisaragiEffective commented on CONTRIBUTING.md
> +整地ワールドを作成する場合、OP権限を付与したプレイヤーかアタッチしたシェルから `mvcreate world_SW normal` を実行します。
初期生成ワールドは当然ゲートがないのでmvtp world_SWで飛べることも書いておくべき

2023-04-14 16:46 UTC, lis2a commented
OK

2023-04-14 16:46 UTC, lis2a commented
OK

2023-04-15 14:34 UTC, KisaragiEffective reviewed
otherwise LGTM

2023-04-15 14:34 UTC, KisaragiEffective commented on CONTRIBUTING.md
> +コンテナを指定する際に使用するIDは `docker ps` を実行すると `seichiassist_spigotb_1` のような形式で表示されます。
```suggestion
コンテナを指定する際に使用するIDはコマンドプロンプトで `docker ps` を実行すると `seichiassist_spigotb_1` のような形式で表示されます。
```

2023-04-15 14:34 UTC, KisaragiEffective commented on CONTRIBUTING.md
> +整地ワールドを作成する場合、OP権限を付与したプレイヤーかアタッチしたコンソールから `mvcreate world_SW normal` を実行します。
```suggestion
整地ワールドを作成する場合、OP権限を付与したプレイヤーかアタッチしたコンソールからコマンドで `mvcreate world_SW normal` を実行します。
```

2023-04-15 21:17 UTC, KisaragiEffective approved these changes

2023-04-16 06:19 UTC, rito528 approved these changes

2023-04-16 06:22 UTC, merged