refactor: 棒の重複した作成処理をリファクタリング
GiganticMinecraft/SeichiAssist pull request #1957
Opened 2023-04-21 16:31 UTC by lis2a

以下のコードが `StickCommand.scala` と `PlayerJoinListener.scala` で重複していたコードを一つにまとめる

#### 該当コード

https://github.com/GiganticMinecraft/SeichiAssist/blob/7886dc2f53eda3399ea797a7a19a8961f2161e9b/src/main/scala/com/github/unchama/seichiassist/listener/PlayerJoinListener.scala#L124-L129

https://github.com/GiganticMinecraft/SeichiAssist/blob/7886dc2f53eda3399ea797a7a19a8961f2161e9b/src/main/scala/com/github/unchama/seichiassist/commands/StickCommand.scala#L17-L22

2023-04-21 16:34 UTC, rito528 requested changes

2023-04-21 16:34 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/StickItemData.scala
menuではなくないですか...?

2023-04-21 16:35 UTC, lis2a commented on src/main/scala/com/github/unchama/seichiassist/menus/StickItemData.scala
そうかもしれない

2023-04-22 03:46 UTC, KisaragiEffective requested changes
* Menuにはメニューのビュー定義のみを入れるべきであり、それ以外は入れるべきではない
* シングルトンの命名が緩すぎる。GachaPrizeFactoryなどを参考にされたい。
* Bukkitのアイテムスタックはミュータブルであるため、valとして持つとすべて共有され不都合なことが起こる可能性がある。

2023-05-21 12:38 UTC, closed without merging