RefDictのwriteでエラーが発生した場合に書き込めるまでretryするようにする
GiganticMinecraft/SeichiAssist pull request #1960
Opened 2023-04-22 15:38 UTC by rito528

2023-04-22 16:05 UTC, kory33 requested changes

2023-04-22 16:05 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/concurrent/Retry.scala
> +package com.github.unchama.generic.effect.concurrent
```suggestion
package com.github.unchama.generic.effect
```

下に `MonadThrowExtra` って名前で作ったほうが良さそうです（`: MonadThrow` 制約は、例えば `SyncIO` の様な concurrent でない effect にも通用するので）

2023-04-22 17:46 UTC, kory33 requested changes

2023-04-22 17:46 UTC, kory33 commented on src/main/scala/com/github/unchama/bungeesemaphoreresponder/bukkit/listeners/BungeeSemaphoreCooperator.scala
> +      fiber <- retryUntilSucceeds(finalizer.onQuitOf(player)).start
この実装だと二つ問題があります。

1. `finalizer` が本当にバグっているときなど、処理を再実行してもエラーの解消が見込めない場合において `retryUntilSucceeds` をすると、終了処理がタイムアウトまでずっと走り続けます。そのようなことが起こった場合、 CPU や IO リソースを食いつぶす可能性があります。
2. この `BungeeSemaphoreCooperator` のコンストラクタがどのような場面で呼び出されているかを辿るとわかりますが、この `finalizer` は 「SeichiAssist 内のすべての終了処理を一斉に並列に実行する」ようなものが渡されます。すると、終了処理に一つでも失敗した場合、すべての終了処理がもう一度再実行されることになります。これは各終了処理が独立に実行できるという仮定をした場合、リソースの無駄です。

2023-04-25 14:50 UTC, rito528 commented
@kory33 
再レビューお願いします！

2023-04-25 15:29 UTC, kory33 requested changes

2023-04-25 15:29 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
> +      .foreach(_ => ())
結果を結局無視しているので `.traverse { player => ... }.unsafeRunSync()` で十分なように思えます

2023-04-25 15:29 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/MonadThrowExtra.scala
> +  def retryUntilSucceeds[F[_]: MonadThrow, A](fa: F[A])(limit: Int, now: Int = 0): F[A] = {
`now` は外部から指定できないべきです。

```Scala
def retryUntilSucceeds[F[_]: MonadThrow, A](fa: F[A])(limit: Int): F[A] = {
  def go(currentIterationCount: Int): F[A] =
    // 今の実装の retryUntilSucceeds の中身

  go(0)
}
```
のような形にするとよいです

2023-04-25 15:29 UTC, kory33 commented on src/main/scala/com/github/unchama/bungeesemaphoreresponder/domain/PlayerDataFinalizer.scala
> +  }
この実装は `finalizer` に何も変更を加えていません。つまり、 `concurrently(finalizers)` と `finalizers` は区別不可能です。よって、この関数を呼び出している箇所で呼び出しを省略して良いです。

まず、
```Scala
for {
  fiber <- action.start
  result <- fiber.join
} yield expr(result)
```
は
```Scala
for {
  result <- action
} yield expr(result)
```
と等価なプログラムです。

ですから、
```Scala
for {
  fiber <- finalizer.onQuitOf(player).attempt.start
  result <- fiber.join
  _ <- result match {
    case Left(error) =>
      ApplicativeError[F, Throwable].raiseError(error)
    case Right(_) =>
      Applicative[F].unit
  }
} yield ()
```
は
```Scala
for {
  result <- finalizer.onQuitOf(player).attempt
  _ <- result match {
    case Left(error) =>
      ApplicativeError[F, Throwable].raiseError(error)
    case Right(_) =>
      Applicative[F].unit
  }
} yield ()
```
と同等です。

最後のプログラムは、 `attempt` の結果が `Left` ならそれをそのまま raise、 `Right(())` なら `Applicative[F].unit` になっているので、
```Scala
finalizer.onQuitOf(player)
```
と同等です。

結局、この関数の実装は
```Scala
finalizers.map { finalizer =>
  PlayerDataFinalizer { player => finalizer.onQuitOf(player) }
}
```
と同じで、これは各 `finalizer` に何も動作上の変更を加えていません。

2023-04-27 06:27 UTC, rito528 commented
とりあえず https://github.com/GiganticMinecraft/SeichiAssist/pull/1960#discussion_r1176685599 以外の内容に関しては修正しました。

https://github.com/GiganticMinecraft/SeichiAssist/pull/1960#discussion_r1176685599 は考えてみましたが、これから講義なので時間がなくて考えられなかったです。
できるかはわかりませんが、帰ってきてからもう少し考えてみます。(とはいえ、何もわからないのでアドバイスを頂けるのであればとても助かります。)

2023-04-29 16:01 UTC, rito528 commented
@kory33 
これで https://github.com/GiganticMinecraft/SeichiAssist/pull/1960#discussion_r1176685599 の要件を満たせているかはわかりませんが、見よう見まねで実装してみました。
再レビューお願いします！

2023-04-30 00:51 UTC, kory33 requested changes
ありがとうございます！とりあえず `retryUntilSucceeds` の改善ポイントを二つ…

2023-04-30 00:51 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/MonadThrowExtra.scala
> +  def retryUntilSucceeds[F[_]: MonadThrow, A](fa: F[A])(limit: Int): F[A] = {
`limit >= 1` を要求した方が良さそう

```suggestion
  def retryUntilSucceeds[F[_]: MonadThrow, A](fa: F[A])(limit: Int): F[A] = {
    require(limit >= 1)
```

2023-04-30 00:51 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/MonadThrowExtra.scala
> +            }
失敗時に `.map` 内で `printStackTrace` するよりも、成功時に今まで起こった例外を全部ログに出しておくの方が直接的に思えます

2023-04-30 02:14 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/ConcurrentExtra.scala
> +      _ <- Concurrent[F].start(fibers.map(_.cancel).sequence)
これですと、 `.start` した `.fiber` を即時に `.cancel` することになっているので、処理が一つも実行されず終了する可能性があります（もしくは、すべて実行し終えてから `.cancel` しようとする可能性もあります）。また、 https://github.com/GiganticMinecraft/SeichiAssist/pull/1960#discussion_r1176685599 で要求したキャンセルに関する制約は満たせていません (例えば `fibers` を得た直後に全体がキャンセルされる可能性があります)。

まずは次のような関数を実装してみてください (cats-effect 2 では、`Bracket` として知られる型クラスの `.bracketCase` と呼ばれる関数でこれが実装できることを確認しています)。

```Scala
/**
 * 与えられた複数の入力プログラムをすべて並列に実行するようなプログラムを構築します。
 * 構築されたプログラムは次のような挙動をします：
 *  - 構築されたプログラムの実行 fiber がキャンセルされた時、
 *    その時点で並列で走っている入力プログラムの実行 fiber がすべてキャンセルされます
 *  - 入力プログラムの実行 fiber がエラー等で早期終了しても、他の実行 fiber への影響はありません
 *    （一つの fiber が異常終了しても、他の fiber のキャンセルなどは行われません）
 *  - 結果の `List[Either[Throwable, A]]` は入力プログラムの終了結果を
 *    (入力プログラムが与えられた順と同じ順で) 保持しています。
 *    
 *    各値は
 *    - `Right[A]` だった場合、入力プログラムが `A` を結果として正常終了したこと
 *    - `Left[Throwable]` だった場合、入力プログラムが例外を送出して異常終了したこと
 *    をそれぞれ表します。
 */
def attemptInParallel[F[_]: ConcurrentEffect, A](programs: List[F[A]]): F[List[Either[Throwable, A]]]
```

この関数を用いて、 `BungeeSemaphoreCooperator#onQuit` 内で望ましい挙動を実現できるかを検討してみてください。

2023-04-30 13:38 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/MonadThrowExtra.scala
> +            }
nits:
```suggestion
            Sync[F]
              .delay(occurredExceptions.foreach(_.printStackTrace()))
              .as(a)
```

2023-05-07 06:16 UTC, rito528 commented
@kory33 
再レビューお願いします！

2023-05-07 06:51 UTC, kory33 requested changes

2023-05-07 06:51 UTC, kory33 commented on src/main/scala/com/github/unchama/generic/effect/MonadThrowExtra.scala
> +    def go(currentIterationCount: Int, occurredExceptions: List[Throwable]): F[A] = {
```suggestion
    def go(currentIterationCount: Int, occurredExceptions: Option[Throwable]): F[A] = {
```

`Option` で良さそうです (`empty` / `.last` も `None` / `.get` に置き換えられる)

2023-05-07 06:51 UTC, kory33 commented on src/main/scala/com/github/unchama/bungeesemaphoreresponder/bukkit/listeners/BungeeSemaphoreCooperator.scala
> +        case Right(List(Left(e))) =>
`Right` の中に入っているのは「例外か成功値の `Either` が複数入った `List`」なので、 `List(Left(e))` だと「例外が一つだけ入っていてそれ以外何も入っていない (timeout していない) 結果 」にマッチします。これは `finalizers` が複数のファイナライザを含んでいることを鑑みるとマッチすることはありません。例外が投げられているときも `Right(_)` のケースに引っ掛かり、これは想定していない挙動です。

2023-05-07 07:27 UTC, rito528 commented
@kory33 
修正しました。
レビューお願いします！

2023-05-07 07:44 UTC, kory33 requested changes

2023-05-07 07:44 UTC, kory33 commented on src/main/scala/com/github/unchama/bungeesemaphoreresponder/bukkit/listeners/BungeeSemaphoreCooperator.scala
> +          }
これですと、成功した結果があればある分だけ貪欲に `confirmSaveCompletionOf(name)` をし、最初に発生したエラーのみを `raiseError` していますが、これは望ましい挙動ではないです (一つでも失敗していればすべての例外をログに出して `notifySaveFailureOf(name)` をし、すべて成功していれば `confirmSaveCompletionOf(name)` を一度だけする、というのが望ましいです)。

2023-05-07 13:33 UTC, rito528 commented
@kory33 
修正しました。
これでどうでしょうか...?

2023-05-07 15:44 UTC, kory33 approved these changes

2023-05-07 15:46 UTC, merged