refactor: 時刻を取得する操作を作用に切り出す
GiganticMinecraft/SeichiAssist pull request #2008
Opened 2023-05-14 08:46 UTC by KisaragiEffective

2023-05-14 11:30 UTC, rito528 requested changes

2023-05-14 11:30 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +    JavaTime[F].getLocalDateTime(ZoneId.systemDefault())
これ結局全部`.toIO`してるので、最初から`IO[LocalDateTime]`で返していいんじゃないかなと思いました。

2023-05-15 10:56 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +    JavaTime[F].getLocalDateTime(ZoneId.systemDefault())
IOは非純粋性を暗示し、その関数で真にやりたいことについて不必要な前提が入る (いわゆる神のモナド) ので、toIOは取り除きたくないです

2023-05-15 12:39 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +    JavaTime[F].getLocalDateTime(ZoneId.systemDefault())
なるほど？
であれば良さそうです

2023-05-15 12:39 UTC, rito528 approved these changes

2023-05-15 12:39 UTC, merged