MineStackのメニューをminestackコマンドから開けるように変更
GiganticMinecraft/SeichiAssist pull request #2046
Opened 2023-05-21 13:07 UTC by Yuki-1118

Minestackのメインメニューを`minestack open 0 0` `ms open 0 0`で開けるように変更しました

2023-05-21 13:12 UTC, rito528 requested changes
開発ありがとうございます！

以下、レビューになります。

2023-05-21 13:12 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +              .closedRangeInt(0, Int.MaxValue, MessageEffect("カテゴリは正の値を指定してください。"))
```suggestion
              .closedRangeInt(0, Int.MaxValue, MessageEffect("カテゴリは0以上の値を指定してください。"))
```

2023-05-21 13:12 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
>                .andThen(_.flatMap { categoryValue =>
```suggestion
              .andThen(_.flatMap { _categoryValue =>
```

2023-05-21 13:12 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +                val categoryKey = categoryValue.asInstanceOf[Int]
```suggestion
                val categoryValue = categoryValue.asInstanceOf[Int]
```

2023-05-21 13:12 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +            Parsers.closedRangeInt(0, Int.MaxValue, MessageEffect("ページ数は正の値を指定してください。"))
```suggestion
            Parsers.closedRangeInt(0, Int.MaxValue, MessageEffect("ページ数は0以上の値を指定してください。"))
```

2023-05-21 13:12 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +          IO.pure(if (context.args.parsed(1).toString.toInt == 0) {
```suggestion
          IO.pure {
              if (context.args.parsed(1).toString.toInt == 0) {
```

2023-05-21 13:12 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +          })
```suggestion
          }
      }
```

2023-05-21 20:24 UTC, Yuki-1118 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +          IO.pure(if (context.args.parsed(1).toString.toInt == 0) {
この部分Scalafmtで上に修正されるのでこのままでもいいでしょうか

2023-05-21 20:28 UTC, Yuki-1118 commented
修正したので確認をお願いします。

2023-05-21 20:38 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
> +          IO.pure(if (context.args.parsed(1).toString.toInt == 0) {
可能です！

2023-05-22 05:33 UTC, rito528 requested changes
Otherwise LGTM.

2023-05-22 05:33 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/minestack/bukkit/MineStackCommand.scala
>              )
```suggestion
         val categoryValue = context.args.parsed(1).toString.toInt

          IO.pure(if (categoryValue == 0) {
            ioCanOpenMinestackMainMenu.open(MineStackMainMenu)
          } else {
            ioCanOpenCategorizedMenu.open(
              new CategorizedMineStackMenu(
                context.args.parsed.head.asInstanceOf[MineStackObjectCategory],
                categoryValue - 1
              )
            )
```

2023-05-22 08:47 UTC, rito528 approved these changes
LGTM.
開発ありがとうございます！！

2023-05-22 08:47 UTC, merged