refactor: 副作用を実行部分に移動
GiganticMinecraft/SeichiAssist pull request #2047
Opened 2023-05-21 14:12 UTC by lis2a

close #2044 

ブランチ名、ミスりました
許してください

2023-05-21 14:15 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +
ここにParserを書いてもパーサーとして機能しません。
`argumentsParsers`の中に記載してください。

ほか全て同様。

2023-05-21 14:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +                  failWith("指定されたIDのアイテムは存在しません！")
このissueの目的としては、ここの`gachaPrizeAPI.existsGachaPrize(GachaPrizeId(intId)).toIO.unsafeRunSync()`を`Parser`の中で呼び出したくないので、ここの条件分岐を`execution`内で処理したいということでした。

2023-05-21 15:29 UTC, rito528 requested changes

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +          _ <- gachaPrizeAPI.removeByGachaPrizeId(gachaId)
```suggestion
          _ <- gachaPrizeAPI.removeByGachaPrizeId(gachaId).whenA(existsGachaPrize)
```

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>              _ <- gachaPrizeAPI.removeByGachaPrizeId(targetId)
```suggestion
            _ <- gachaPrizeAPI.removeByGachaPrizeId(targetId).whenA(existsGachaPrize)
```

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>              itemStack = existingGachaPrize.get.itemStack
```suggestion
            itemStack = existingGachaPrize.map(_.itemStack)
```

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>              )
```suggestion
            ).whenA(existsGachaPrize)
```

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>            _ <- gachaPrizeAPI.removeByGachaPrizeId(targetId)
```suggestion
          _ <- gachaPrizeAPI.removeByGachaPrizeId(targetId).whenA(existsGachaPrize)
```

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>            )
```suggestion
          ).whenA(existsGachaPrize)
```

2023-05-21 15:29 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
>            itemStack = existingGachaPrize.get.itemStack
```suggestion
          itemStack = existingGachaPrize.map(_.itemStack)
```

2023-05-21 16:04 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gacha/bukkit/GachaCommand.scala
> +            MessageEffect(List("ガチャアイテムを削除しました", "ガチャアイテム削除を永続化するためには/gacha saveを実行してください。"))
```suggestion
            MessageEffect(List("ガチャアイテムを削除しました", "ガチャアイテム削除を保存するためには/gacha saveを実行してください。"))
```

2023-05-22 14:47 UTC, rito528 approved these changes

2023-05-22 14:48 UTC, merged