chore: プルリクエストテンプレートの追加
GiganticMinecraft/SeichiAssist pull request #2065
Opened 2023-05-28 15:06 UTC by lis2a

https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

2023-05-28 15:24 UTC, Lucky3028 commented
CIは永遠に走らないので、AutoMergeを解除

2023-05-28 15:51 UTC, inductor requested changes

2023-05-28 15:51 UTC, inductor commented on .github/pull_request_template.md
> +    何らかのIssueに取り組んだプルリクエストの場合は該当のIssueを紐づける必要があります。
全体的に直訳すぎるので変かも。例えばこういう観点で、日本ととして変じゃないかをみてください
「何かのIssueに」<-- 何かではないIssueは普通ないので変

2023-05-28 16:02 UTC, Lucky3028 commented on .github/pull_request_template.md
> +    何らかのIssueに取り組んだプルリクエストの場合は該当のIssueを紐づける必要があります。
issue化されていないPRもありうるので、そういう意味で使われてそうです

2023-05-28 16:03 UTC, Lucky3028 commented on .github/pull_request_template.md
> +    何らかのIssueに取り組んだプルリクエストの場合は該当のIssueを紐づける必要があります。
だとしても、少し書き換えても良さそうというのは同意します。
「既に作成されているissueを解決するPRの場合は」

2023-05-28 16:19 UTC, lis2a commented on .github/pull_request_template.md
> +    何らかのIssueに取り組んだプルリクエストの場合は該当のIssueを紐づける必要があります。
そうですね、書き換えます

2023-05-28 16:44 UTC, KisaragiEffective requested changes
全体的にこのままではマージできない

2023-05-28 16:44 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +**関連Issue:**
```suggestion
**関連issue:**
```

nitpick: "issue"は固有名詞ではないので常に大文字にするのは変

2023-05-28 16:44 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +    ここにあなたが行った変更を簡潔に説明していきましょう。詳しすぎる必要はありません。
```suggestion
    ここにあなたが行った変更を簡潔に説明してください。自明な場合は省略しても良いですが、なるべく書くようにしてください。
    情報量が多い場合は<details>タグで折りたたんでください。例:
    <details>
    	<summary>ここに要約</summary>
    	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </details>
    [例示ここまで]
```

2023-05-28 16:44 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +    複数のIssueを紐付ける場合はそれに続いて "close: #1, close: #2" と指定してください。
```suggestion
    issueを紐付ける場合は以下に "close: #<該当のissue番号>" と指定してください。
    複数のissueを紐付ける場合はそれに続いて "close: #1, close: #2" と指定してください。
```

2023-05-28 16:44 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +-->
```suggestion
    issueに紐付かないプルリクエストの場合は、「close: #」を消してください。
-->
```

2023-05-28 16:44 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +close: #
```suggestion
close #
```

nitpick: 慣例的に`close: `と書かれることはなかったので揃えたい

2023-05-28 16:49 UTC, lis2a commented on .github/pull_request_template.md
> +close: #
普通にミスってた

2023-05-28 16:59 UTC, inductor commented on .github/pull_request_template.md
> +    プルリクエストの作成ありがとうございます！
issueは英語なのにプルリクはカタカナ？

2023-05-28 17:00 UTC, inductor commented on .github/pull_request_template.md
> +    	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nis
このダミーテキストって英語圏では一般的ですけど、日本語だと例としてはわかりにくくないですか

2023-05-28 17:01 UTC, inductor commented
https://gist.github.com/katyhuff/845e06656f18784210190e4f46a4aa95
こういうチェックリストもあるんだけど、導入は検討した？

2023-05-28 17:02 UTC, lis2a commented
> https://gist.github.com/katyhuff/845e06656f18784210190e4f46a4aa95 こういうチェックリストもあるんだけど、導入は検討した？

してないです

2023-05-28 17:03 UTC, inductor commented
@lis2a 「してないです」だと会話が終わっちゃってレビューが進まないので、「してないです、検討したほうがいいですかね」とか「してないですが⚪︎⚪︎なので不要だと思います」とか何か付け加えた方がいいかも

2023-05-28 17:06 UTC, inductor commented
あとなんかそもそもなんでこのテンプレートを導入するという経緯があったかみたいな話はPRのメッセージにいれたほうがいいのでは（まさにそういう意図でPRテンプレートを作ってるわけだと思うので、Discordなりなんなりどこかで議論した経緯があるならそこのリンクとか貼った方がよさそう）

2023-05-28 17:07 UTC, inductor commented on .github/pull_request_template.md
> +    Pull Requestの作成ありがとうございます！
大文字小文字の表記揺れ（14行目ではPRが小文字だけになっている）

2023-05-28 17:11 UTC, inductor commented on .github/pull_request_template.md
> +    既に作成されているissueを解決するpull requestの場合は該当のIssueを紐づける必要があります。
なんか日本語が変で、「Issueに紐づくようなPRはこういう作法にしなければならない」って別にGitHubの規約に書かれているわけでもなくて、単にIssueとPRのステータスが同期されて便利だから使おうね、ってだけの話だよね？

だとするとこの条件において「必要があります」ってなんとなく変（そうしないといけないように聞こえる）っぽくて、ついでにそれを示す根拠として https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue くらいは載せた方が親切じゃないかしらね

2023-05-28 17:12 UTC, lis2a commented
> あとなんかそもそもなんでこのテンプレートを導入するという経緯があったかみたいな話はPRのメッセージにいれたほうがいいのでは（まさにそういう意図でPRテンプレートを作ってるわけだと思うので、Discordなりなんなりどこかで議論した経緯があるならそこのリンクとか貼った方がよさそう）
> 
> 今後すべてのPRに基本的には適用されることになるテンプレートなわけだし、それを考えるとこのPRの影響範囲は意外と大きいよ

元は `close` や `fix` などの Issue とプルリクエストを紐付けるキーワードについて [`CONTRIBUTING.md` に書くのであればテンプレートで用意したほうがいいよね](https://github.com/GiganticMinecraft/SeichiAssist/pull/2064#discussion_r1208566464)という話が出たのでこのプルリクエストを発行したのでそういう意図でのテンプレート追加ではないです
(プルリクエストの説明欄に残しておくべきという話についてはまさにそのとおりです。残しておきます.)

2023-05-28 17:14 UTC, lis2a commented on .github/pull_request_template.md
> +    既に作成されているissueを解決するpull requestの場合は該当のIssueを紐づける必要があります。
プルリクエスト作成者が `close`, `fix` などで紐付けなくても結局 GiganticMinecraft のメンバーが手動で紐付ればいいだけの話なのでこの文章自体が不要なのではと思い始めた

2023-05-28 17:17 UTC, inductor commented on .github/pull_request_template.md
> +    既に作成されているissueを解決するpull requestの場合は該当のIssueを紐づける必要があります。
その運用は微妙なのでは

2023-05-28 17:19 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +    既に作成されているissueを解決するpull requestの場合は該当のIssueを紐づける必要があります。
それだと微妙で、結局昨日の棚卸しみたいなのを定期的にやる必要がある。我々は有限の時間しかないので、そういった自動化できるのに非本質的なことに時間を割いている暇はない

2023-05-28 17:20 UTC, inductor commented on .github/pull_request_template.md
> +**関連issue:**
issue全部小文字？

2023-05-28 17:21 UTC, KisaragiEffective commented on .github/pull_request_template.md
> +    </details>
```suggestion
    <details>
        <summary>ここに要約</summary>
        ここに詳細
    </details>
```

先のsuggでTABを挿入してしまったがspaceに揃えたい

2023-05-28 17:30 UTC, lis2a commented
プルリクエストテンプレートにその[チェック項目](https://gist.github.com/katyhuff/845e06656f18784210190e4f46a4aa95)は追加しますか？(そこまでガッチリやるとは考えていないので #2065 を発行する時点で頭にすらなかった)

2023-05-28 17:36 UTC, inductor commented
> そこまでガッチリやるとは考えていないので https://github.com/GiganticMinecraft/SeichiAssist/pull/2065 を発行する時点で頭にすらなかった

そのリンクで議論があったという記述が作成当初のPR文章に含まれていなかったのでPRのスコープがわからず、そういう確認を入れています。

2023-05-28 17:37 UTC, inductor commented on .github/pull_request_template.md
> +    issueを紐付ける場合は以下に "close #<該当のIssue番号>" と指定してください。
```suggestion
    issueを紐付ける場合は以下に "close #<該当のissue番号>" と指定してください。
```

2023-05-28 17:38 UTC, inductor commented on .github/pull_request_template.md
> +    Pull Requestの作成ありがとうございます！
ここ大文字ならIssueも大文字でいいのでは

2023-05-29 02:24 UTC, lis2a commented
一度ドラフトに変換

2023-05-29 13:19 UTC, lis2a commented
正直大前提、何をしたのか・なぜこのプルリクエストを発行したのか などをプルリクエストにまとめれば最低限レビューも楽になると考えたため、チェック項目程ではないが入力欄を用意する

2023-05-31 12:57 UTC, merged