破壊設定システムの再実装
GiganticMinecraft/SeichiAssist pull request #2072
Opened 2023-05-31 15:45 UTC by rito528

ブロックを破壊するかを指定するシステムを再実装しました。

#2069 でやろうとしていたissueで、現状の実装だと設定を永続化できないようだったので、
それを解決するために再実装しました。

2023-05-31 17:21 UTC, KisaragiEffective submitted a review, later dismissed

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakflags/domain/BreakFlagName.scala
> +  case object NetherQuartz extends BreakFlagName
```suggestion
  case object MadeFromNetherQuartz extends BreakFlagName
```
上記のことを命名にも反映したほうが良さそう

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakflags/domain/BreakFlagName.scala
> + * 定義されたブロックを破壊するかしないかを表すためのフラグの名前を集めたEnum
```suggestion
 * 予め決められたブロックの集合を表現する。これらの値は整地スキルでブロックを破壊する際にプレイヤーの設定に応じて一部のブロックを除外する際に使われる。
```

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +      chestFlag <- breakFlagAPI.breakFlag(player, BreakFlagName.Chest)
```suggestion
      breakChest <- breakFlagAPI.breakFlag(player, BreakFlagName.Chest)
```

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +    flag_name VARCHAR(20) NOT NULL,
```suggestion
    flag_name VARCHAR(20) NOT NULL,
```

事故を防ぐためにこのカラムは[`ENUM`](https://mariadb.com/kb/en/enum/)であるべきです。

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +    can_break BOOL NOT NULL DEFAULT TRUE
```suggestion
    include BOOL NOT NULL DEFAULT TRUE
```

nit: プレイヤーが直接可能かどうかを決定するわけではないのでcanは変かもしれない

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +CREATE TABLE break_flags(
```suggestion
CREATE TABLE player_break_preference(
```

これはクラス名やパッケージ名にも適用される話ですが、break flagsは情報量が意図せず少なくなっているのでこの命名のほうがベターかと思いました

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +);
playerdataテーブルに対して外部キー成約があってもいいかもしれない

2023-05-31 17:21 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +);
既存のチェスト破壊設定の値をマイグレーションで新しいテーブルにコピーしたあとでplayerdataテーブルのカラムをドロップするマイグレーションを入れたほうがいいと思います

2023-05-31 17:26 UTC, KisaragiEffective commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +);
補足: パフォーマンス的にどうかはともかく、整合性を破壊しないために主キー制約をuuidとflag\_nameにつけたほうが良さそう

2023-05-31 18:56 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakflags/domain/BreakFlagName.scala
> +sealed trait BreakFlagName extends EnumEntry
`BreakSkillTargetConfig` みたいな subsystem 名にしてこの `enum` は `BreakSkillTargetConfigKey` とするのが適当だと思います

2023-05-31 18:59 UTC, kory33 commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +);
主キー制約を `uuid` と `flag_name` に付けたうえで `uuid` に index を張りましょう

2023-06-01 05:03 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakflags/persistence/JdbcBreakFlagPersistence.scala
> +          .map { rs =>
ここでの`.map`関数はscalikejdbcによるもので、`flatMap`を使うことはできないという認識なんですが、どうでしょうか...?

2023-06-01 05:35 UTC, rito528 commented on src/main/resources/db/migration/V1.17.0__Create_break_flag_table.sql
> +);
@KisaragiEffective 
今までは、`playerdata`テーブルにデータを保存するカラムが存在しない認識なんですが、実際にはあったりしますか？
ある場合はどのカラムか教えていただきたいです。

2023-06-01 06:19 UTC, rito528 commented
再レビューお願いします。
resolveしていないところにはコメントを残してあるので、それについても書いていただけると助かります。

2023-06-03 16:35 UTC, kory33 reviewed
Otherwise LGTM

2023-06-03 16:35 UTC, kory33 commented on src/main/resources/db/migration/V1.17.0__Create_break_preference_table.sql
> +    FOREIGN KEY (uuid) REFERENCES playerdata(uuid),
ところで、これは不要なサブシステムとメインシステム間の依存を生やしてしまうので、無い方がいいと思います

2023-06-03 16:35 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +            ),
```suggestion
            breakSkillTargetConfigAPI
              .toggleBreakSkillTargetConfig(BreakSkillTargetConfigKey.Chest),
```

2023-06-03 16:35 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +            ),
```suggestion
            breakSkillTargetConfigAPI
              .toggleBreakSkillTargetConfig(BreakSkillTargetConfigKey.MadeFromNetherQuartz),
```

2023-06-03 16:35 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakskilltargetconfig/System.scala
> +              }
エントリポイントにドメインロジックが書かれており、望ましくないです（ちょっと今時間が取れないので詳細な説明が書けないのですが…）

2023-06-03 16:35 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakskilltargetconfig/System.scala
> +              } yield flags.find(_.configKey == breakFlagName).fold(true)(_.includes))
エントリポイントにドメインロジックが書かれており、望ましくないです（ちょっと今時間が取れないので詳細な説明が書けないのですが…）

2023-06-09 05:46 UTC, rito528 commented
@kory33 
レビューしていただいた内容直しました！
再レビューお願いします。

2023-06-11 18:05 UTC, kory33 requested changes

2023-06-11 18:05 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakskilltargetconfig/domain/BreakSkillTargetConfigRepository.scala
> +   * この関数は永続化層で利用されることを想定しています。
nits: これは書かない方が良いかも（ふつう、`domain` 層は永続化層のことを何も想定しません。`domain` にコードを書く際は、永続化層のことは基本的に「忘れたふりをする」必要があります）

2023-06-14 01:08 UTC, rito528 commented
@kory33 
レビューしていただいた内容を直しましたが、 https://github.com/GiganticMinecraft/SeichiAssist/pull/2072#discussion_r1225875962 の
> BreakSkillTargetConfig に Set[BreakSkillTargetConfigKey] を持たせて、必要なメソッドを提供し

という部分が`Set`だと、ConfigのKeyとValueを管理することができないので`Map`型としました。
これより良いやり方があれば、教えていただけると助かります。

2023-06-29 14:34 UTC, kory33 submitted a review, later dismissed
3つだけ　それ以外は良さそうです 👍

2023-06-29 14:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakskilltargetconfig/domain/BreakSkillTargetConfig.scala
> +   * @return `configKey`の破壊フラグをトグルする作用
値を作用ではなくて値に送る関数です

```suggestion
   * @return `configKey`の破壊フラグをトグルする
```

2023-06-29 14:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/breakskilltargetconfig/domain/BreakSkillTargetConfig.scala
> +   * @return 現在の破壊フラグを取得する作用
値を作用ではなくて値に送る関数です

```suggestion
   * @return 現在の破壊フラグを取得する
```

2023-06-30 07:04 UTC, rito528 commented
@kory33 
レビューしていただいた内容を修正しました！

2023-06-30 07:30 UTC, kory33 requested changes
いくつか修正してほしい点がありました 👀

2023-06-30 07:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +              if (breakQuartz) {
ここも上の方と同様の理由でバグってます

2023-06-30 07:57 UTC, rito528 commented
@kory33 
修正しました！
再レビューお願いします

2023-06-30 09:09 UTC, kory33 commented on src/main/resources/db/migration/V1.17.0__Create_break_preference_table.sql
> +    break_category ENUM('Chest', 'MadeFromNetherQuartz') NOT NULL,
もしかして
```suggestion
    block_category ENUM('Chest', 'MadeFromNetherQuartz') NOT NULL,
```

2023-06-30 11:13 UTC, rito528 commented
@kory33 直しました！

2023-06-30 11:33 UTC, kory33 approved these changes
LGTM 👍 
ありがとうございます！

2023-07-02 22:19 UTC, merged