Fix/2098
GiganticMinecraft/SeichiAssist pull request #2100
Opened 2023-06-11 04:22 UTC by Lucky3028

close #2098 

----

### このPRの変更点と理由:

### 補足情報:

2023-06-11 04:30 UTC, kory33 commented
#2072 と変更範囲が被ってそうです。 #2072 がマージできた後に、再実装後のシステムに対して変更を加えていただけますか？

2023-06-11 04:40 UTC, Lucky3028 commented
OKです

2023-08-24 12:22 UTC, rito528 requested changes

2023-08-24 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +      false
`if`の条件を変数に切り出して、その条件を最終的に返すといいかなと思いました。

2023-08-24 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類」に鉱石は含まれない。
`ここでいう「ネザー水晶類」に鉱石は含まれない。`とありますが、処理の内容をみると

- ネザークオーツ鉱石
- クオーツの階段
- クオーツハーフブロック

が含まれているのでドキュメントと実際の処理の間に相違があるように感じます。

2023-08-24 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * @param player プレイヤー
単に`プレイヤー`とするとドキュメントが提供している情報がないに等しいので、あくまで一例ですが
```suggestion
   * @param player ネザー水晶類破壊設定を取得するプレイヤー
```

のようになっていると良いと思いました。

2023-08-24 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * @return ブロックがネザー水晶類破壊フラグの保護対象かどうか
```suggestion
   * @return `checkTarget`が保護対象のネザー水晶類ブロックかどうか
```

`フラグ`とはどこでも呼んでいないので、ちょっと意味が違うと思いました。

2023-08-24 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  private def isProtectedNetherQuartzBlock(player: Player, checkTarget: Block): Boolean = {
```suggestion
  private def isProtectedNetherQuartzBlock(player: Player, targetBlock: Block): Boolean = {
```

2023-08-24 12:22 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  private def isProtectedNetherQuartzBlock(player: Player, checkTarget: Block): Boolean = {
関数名について、処理の中身としては破壊対象のブロックかどうかを確認しているだけなので、メソッド名で`isProtectedNetherQuartzBlock`というのはどうなんだという気がしています

2023-08-24 12:24 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類」に鉱石は含まれない。
`Material.QUARTZ_BLOCK`はネザー水晶ブロックで、ネザー鉱石ではありませんから、相違はありません

2023-08-24 12:36 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  private def isProtectedNetherQuartzBlock(player: Player, checkTarget: Block): Boolean = {
そうですか？
「trueが返る=破壊対象ではない=保護されている」
という発想では？

2023-08-24 12:41 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類」に鉱石は含まれない。
なるほど。

であれば、ドキュメントだけを読むと、ネザー水晶類ブロックを破壊するのか保護するのかわかりにくいので、そこを直したほうがいいと思います。

2023-08-24 13:19 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  private def isProtectedNetherQuartzBlock(player: Player, checkTarget: Block): Boolean = {
それなら、単に関数名を`canBreakNetherQuartzBlock`みたいにして、`true`なら破壊できる、`false`なら破壊できないといったほうが直接的でわかりやすいと考えていますがどうですか？

`BreakSkillTargetConfigKey`という名前の通り、破壊するかどうかを見ているだけなので保護ではないのかなと思います。

2023-08-24 13:29 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +  private def isProtectedNetherQuartzBlock(player: Player, checkTarget: Block): Boolean = {
あー、よさそうです

2023-08-24 13:52 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
@Lucky3028 
「ネザー水晶類ブロック」がなんのブロックを表しているのかをざっくりでいいので書き出していただけますか？
鉱石が含まれるのであれば、すべてのネザー水晶系ブロックを表すのかと思ってしまいます。

2023-08-24 14:02 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
ネザー水晶鉱石しかないかも

2023-08-24 14:09 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
そうすると、ネザー水晶鉱石かどうかで素直に書けますね、そうします？

2023-08-24 14:19 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
そのほうがシンプルでいいと思います👌

2023-08-24 14:35 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
直しましたが、本当にこれで等価なのか自信が全くないです...

2023-08-24 14:37 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
これ、ネザー水晶鉱石だけ破壊できるようになっていませんか...？

2023-08-24 14:41 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
一度なにをしたいのかを整理したほうが良さそう

2023-08-24 14:45 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +   * ここでいう「ネザー水晶類ブロック」に鉱石は含まれる。
目標としては、「ネザー水晶鉱石以外のネザー水晶でクラフトできるブロック（ネザー水晶ブロック、ネザー水晶の階段ブロック、ネザー水晶のハーフブロック）をスキルで破壊できないように」するフラグ設定を追加すること。
フラグがON
→ネザー水晶鉱石以外のネザー水晶でクラフトできるブロックが破壊できない
フラグがOFF
→すべて破壊できる

2023-08-24 16:14 UTC, rito528 approved these changes

2023-08-24 16:14 UTC, merged