fix: ガチャイベントの開催日時に初日が含まれていなかった不具合を修正
GiganticMinecraft/SeichiAssist pull request #2143
Opened 2023-06-30 05:52 UTC by rito528

ガチャイベントの開催日初日として登録した日が、イベント日として認識されていなかった

2023-06-30 06:23 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/domain/gachaevent/GachaEvent.scala
> +    now.isAfter(startDate.minusDays(1)) && now.isBefore(endDate)
```suggestion
    val isAfterStartDate = now.equals(startDate) || now.isAfter…
    val isBeforeEndDate = now.equals(endDate) || now.isBefore…

    isAfterStartDate && isBeforeEndDate
```
このほうが明確では？

2023-06-30 06:34 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/domain/gachaevent/GachaEvent.scala
> +    val isAfterStartDate = now.equals(startDate) || now.isAfter(startDate)
命名にequalみたいな文言も入れたほうがいいんですかね？どうでしょうか？

2023-06-30 06:37 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachaprize/domain/gachaevent/GachaEvent.scala
> +    val isAfterStartDate = now.equals(startDate) || now.isAfter(startDate)
Afterはその日を含まないようなので、直したほうがいいかも、直します

2023-06-30 06:52 UTC, Lucky3028 requested changes
lastとendで表記が揺れているので、どちらかで統一してください

2023-07-02 03:14 UTC, Lucky3028 approved these changes

2023-07-02 03:14 UTC, merged