chore: docker-compose.ymlからcompose.ymlにリネームする
GiganticMinecraft/SeichiAssist pull request #2188
Opened 2023-07-31 08:50 UTC by rito528

2023-07-31 09:54 UTC, m1sk9 requested changes
https://github.com/GiganticMinecraft/SeichiAssist/blob/3c7396b2d7cb7e759828a0021dcf64208e2866ad/compose.yml#L1

Compose v2 から `version` プロパティは後方互換性のために定義されているものなので実際には不要かも。削除してもいいかなと思います。

https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md

2023-08-01 02:54 UTC, rito528 commented
> https://github.com/GiganticMinecraft/SeichiAssist/blob/3c7396b2d7cb7e759828a0021dcf64208e2866ad/compose.yml#L1
> 
> Compose v2 から `version` プロパティは後方互換性のために定義されているものなので実際には不要かも。削除してもいいかなと思います。
> 
> https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md

よさそう。消します。

2023-08-01 04:22 UTC, outductor approved these changes

2023-08-01 04:36 UTC, m1sk9 approved these changes

2023-08-01 04:36 UTC, merged