feat: マナが無くなったら掘れなくするパッシブスキルを追加
GiganticMinecraft/SeichiAssist pull request #2370
Opened 2024-08-31 12:54 UTC by kuroma6666

close #1964 

----

### このPRの変更点と理由:

#### 主な変更点
- パッシブスキルに対して、スキルをONにしている際にマナを消費しきった際に整地スキルによってブロック破壊しない設定を追加

### 補足情報:
- デフォルト設定値はOFF設定とする（初心者プレイヤー詰み防止）

#### メモ
- パッシブスキル設定は永続化すべきかどうか？
→`player_break_preference`テーブル->`block_category`カラムのENUM型リストの更新が必要？

2024-09-14 17:38 UTC, kuroma6666 commented
@rito528 
ご確認よろしくお願いします。

2024-09-15 05:23 UTC, rito528 requested changes
`develop` ブランチの変更を取り込んでしまっているようなので、 `git rebase --rebase-merges 1_18` などを実行して `develop` ブランチの変更をコミット履歴から消していただけると助かります🙇‍♂️🙇‍♂️

2024-09-15 05:27 UTC, kuroma6666 commented
了解です。

2024-09-15 06:49 UTC, kuroma6666 commented
@rito528 
`develop`ブランチの変更を取り込んでしまっていた内容については削除しました。

2024-09-15 08:31 UTC, rito528 requested changes
一旦2つ変更をお願いします

2024-09-15 08:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +              }
現在のコードは、破壊対象の各ブロックを破壊する処理内で実行していますが、このスキルは整地スキルによって破壊される各ブロックに対して破壊処理を行うか否かを判定するのではなく、スキルによるブロック破壊が起こったときに、スキルを発動するか否かを判定するべきだと思うので、この「スキル発動分のマナがなかったら採掘処理を行わない」という処理はマナの消費部分での処理ではなく、もう少し上の行で書くと良いかもしれません。
具体的には、102行目あたりのクールダウン中の処理の下辺りが良いと思います。

2024-09-15 08:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/util/BreakUtil.scala
> +
この処理は `breakskilltriggerconfig` subsystem 内に書きたいです。

2024-09-21 07:48 UTC, kuroma6666 commented
> 一旦2つ変更をお願いします
@rito528 
一旦変更かけました

2024-09-21 15:42 UTC, rito528 requested changes

2024-09-21 15:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mana/domain/ManaManipulation.scala
> +
`amount` だけマナを消費することができるかを確認したいとのことなので、この関数は
```scala
/**
 * `amount` だけマナを消費することができれば `true`、消費できなければ `false` を返す作用
 */
def canAcquire(amount: ManaAmount): F[Boolean]
```
のような構造を持つ関数に変更すると良いと思います。

2024-09-21 15:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +              }
```suggestion
            case None if BreakSkillTriggerSettings.isBreakBlockManaFullyConsumed(player) => 
                event.setCancelled(true)
            case _ =>
```

2024-09-21 15:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +    }
この下のファイルのコードのコピペミスだとおもいます

2024-09-22 13:19 UTC, kuroma6666 commented
@rito528 
レビュー内容について対応実施しました、再確認お願いします。

2024-09-22 16:38 UTC, rito528 requested changes
テーブル構成が変わることで今と実装がかなり変わりそうなので、一度以下の内容の変更をお願いします！

2024-09-22 16:38 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +  }
```suggestion
  def isBreakBlockManaFullyConsumed(player: Player): IO[Boolean] = {
    for {
      isBreakBlockManaFullyConsumed <- SeichiAssist
        .instance
        .breakSkillTriggerConfigSystem
        .api
        .breakSkillTriggerConfig(player, BreakSkillTriggerConfigKey.ManaFullyConsumed)
      _ <- ActionBarMessageEffect(s"${RED}マナ切れでブロック破壊を止めるスキルは有効化されています")
        .run(player)
        .whenA(isBreakBlockManaFullyConsumed)
      } yield isBreakBlockManaFullyConsumed 
  }
```

2024-09-22 16:38 UTC, rito528 commented on src/main/resources/db/migration/V1.19.0__Create_break_trigger_preference_table.sql
> +);
このテーブルで扱うデータは「マナがないときにスキルの発動を抑制するかどうか」ということだけなので、`trigger_category` カラムが `ENUM` で複数の値を持つことができる必要がないと思います(あくまで設定が有効か無効かの2値のみを扱うので)
なので、以下のようなテーブルにすると良いと思います。

```suggestion
CREATE TABLE player_break_suppression_preference(
    uuid CHAR(36) NOT NULL,
    do_break_suppression_due_to_mana BOOL NOT NULL DEFAULT FALSE,
    FOREIGN KEY fk_player_break_suppression_preference_uuid REFERENCES playerdata(uuid)
);
```

2024-10-12 07:57 UTC, kuroma6666 commented
> テーブル構成が変わることで今と実装がかなり変わりそうなので、一度以下の内容の変更をお願いします！

@rito528 
一旦変更をかけたので、確認お願いします。

2024-10-12 09:10 UTC, rito528 requested changes

2024-10-12 09:10 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mana/domain/LevelCappedManaAmount.scala
> +
`ManaAmount.scala` の `tryConsume` 関数に対して書いたレビューと同様なので理由は省略しますが、`tryConsume` 関数は必要ないと思います。

2024-12-14 13:38 UTC, kuroma6666 commented
@rito528 
ご指摘の内容を反映しました。
再度レビューよろしくお願いします。

2024-12-15 04:49 UTC, rito528 requested changes
Otherwise LGTM.

再レビュー申請前に `sbt scalafixAll; scalafmtAll;` を実行してもらえると助かります！

2024-12-15 04:49 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +              }
以下のように書いたほうが、より読みやすくなると思います

```suggestion
              if (originalBreakStopConfig) {
              SequentialEffect(
                  MessageEffect(s"${RED}マナが切れたらブロック破壊を止めるスキルを無効化しました。"),
                  FocusedSoundEffect(Sound.BLOCK_STONE_BUTTON_CLICK_ON, 1f, 0.5f)
                )
              } else {
                 SequentialEffect(
                  MessageEffect(s"${GREEN}マナが切れたらブロック破壊を止めるスキルを有効化しました。"),
                  FocusedSoundEffect(Sound.BLOCK_STONE_BUTTON_CLICK_ON, 1f, 1f)
                )
              }
```

2024-12-15 04:49 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +  def isBreakBlockManaFullyConsumed(player: Player): IO[Boolean] = {
見た限り `PlayerBlockBreakListener` 内の定義でしか使われていないようなので `private` にして良いと思います！(私の見落としだったらそのままで大丈夫です！)

```suggestion
  private def isBreakBlockManaFullyConsumed(player: Player): IO[Boolean] = {
```

2024-12-21 05:45 UTC, kuroma6666 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerBlockBreakListener.scala
> +  def isBreakBlockManaFullyConsumed(player: Player): IO[Boolean] = {
見た限り`PlayerBlockBreakListener`でしか使ってないなかったのでprivateつけます

2024-12-21 06:19 UTC, kuroma6666 commented
@rito528 
レビューいただいた内容について修正・変更をかけたので、再度ご確認よろしくお願いします。

2024-12-21 06:35 UTC, rito528 requested changes
最後に1点だけ変更お願いします！

2024-12-21 06:35 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +              if (!isBreakSuppressionEnabled) {
```suggestion
              if (isBreakSuppressionEnabled) {
```

2024-12-21 06:37 UTC, kuroma6666 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +              if (!isBreakSuppressionEnabled) {
目が滑って変更漏れしていました🙃

2024-12-21 06:41 UTC, rito528 approved these changes
LGTM.👍👍👍

お疲れ様でした！

2024-12-21 06:41 UTC, merged