update: 整地報酬ガチャ券受取ボタンに右クリックして1スタックだけ引き出せるようにする機能を追加
GiganticMinecraft/SeichiAssist pull request #2371
Opened 2024-09-01 06:50 UTC by kuroma6666

close #2152

----

### このPRの変更点と理由:
- 「整地報酬ガチャ券を受け取る」ボタンを右クリックすると1stずつ受け取れるように機能更新
- ボタンのloreに左クリックと右クリックでまとめて受け取れるガチャ券枚数について記載追加
※loreの表示イメージ：
![image](https://github.com/user-attachments/assets/bbf18698-f75e-49ca-a514-74c5ad8ae325)

2024-09-01 06:55 UTC, m1sk9 commented
タイトルを修正しました

2024-09-01 07:42 UTC, rito528 requested changes

2024-09-01 07:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/System.scala
> +              .as(())
```suggestion
              .traverse(_.semaphore.tryRightClickBatchTransaction)
              .void
```

2024-09-01 07:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/BatchUsageSemaphore.scala
> +        gachaPointRef.modify { point => point.useInRightClickBatch.asTuple }
```suggestion
        gachaPointRef.modify(_.useInRightClickBatch.asTuple)
```

2024-09-01 07:42 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  lazy val useInRightClickBatch: GachaPoint.Usage = {
ドメイン知識として `RightClick` という言葉を用いるべきではないと思います。
あくまで「右クリックをすると持っている `GachaPoint` の中から最大64個のガチャ券を取り出すことができる」という操作はドメインとしての知識ではなく、UI 上の知識として扱われるべきだと考えています。

ではどのように変更するべきかというと、`GachaPoint` のドキュメント(`GachaPoint.scala` の5 ~ 9行目)で「プレーヤーは576個(= 64 * 9スタック)のバッチにてガチャポイントをガチャ券に交換できる。」とあるので、「プレーヤーは576個(= 64 * 9スタック)または64個(1スタック)のバッチにてガチャポイントをガチャ券に交換できる。」とした上で、`useInRightClickBatch` と `useInBatch` という変数の名前を576個のバッチなのか、64個のバッチとして扱うかを判別できる名前にするといいと思います。

2024-09-01 16:44 UTC, rito528 requested changes

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/GachaPointApi.scala
> +
64個のバッチもしくは512個のバッチが存在するので、`receiveBatch`、`receiveOneStackBatch` がどちらを表しているのかを変数名、ドキュメント共に明らかにするとよいと思います。

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/System.scala
> +              .as(())
```suggestion
              .void
```

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
>    lazy val useInBatch: GachaPoint.Usage = {
`useInBatch` が576個のバッチを扱うことを変数名としても明確にしたいです。

```suggestion
  lazy val useInLargeBatch: GachaPoint.Usage = {
```

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
>    final val batchSize = 9 * 64
```suggestion
  final val largeBatchSize = 9 * 64
```

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  final val batchSizeOneStack = 64
```suggestion
  final val smallBatchSize = 64
```

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  lazy val useInOneStackBatch: GachaPoint.Usage = {
```suggestion
  lazy val useInSmallBatch: GachaPoint.Usage = {
```

2024-09-01 16:44 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/BatchUsageSemaphore.scala
> +  def tryOneStackBatchTransaction: F[Unit] =
github の仕様で suggestion が書けなかったのですが、`tryBatchTransaction` 関数は `tryLargeBatchTransaction` とするとよいと思います。

```suggestion
  def trySmallBatchTransaction: F[Unit] =
```

2024-09-01 16:45 UTC, rito528 requested changes

2024-09-01 16:45 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/GachaPointApi.scala
>    val receiveBatch: Kleisli[F, Player, Unit]
```suggestion
  val receiveLargeBatch: Kleisli[F, Player, Unit]
```

2024-09-01 16:45 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/GachaPointApi.scala
> +  val receiveOneStackBatch: Kleisli[F, Player, Unit]
```suggestion
  val receiveSmallBatch: Kleisli[F, Player, Unit]
```

2024-09-03 15:31 UTC, rito528 requested changes

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
>     * ガチャ券へのポイント交換にて一度に得られるガチャ券の上限
```suggestion
   * ガチャ券を576個(= 64 * 9スタック)のバッチでガチャポイントに変換する際のバッチサイズ
```

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +    require(gachaTicketCount <= GachaPoint.largeBatchSize, "usage must not exceed batch size")
```suggestion
    require(gachaTicketCount <= GachaPoint.maxBatchSize.value, "usage must not exceed max batch size")
```

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  final val largeBatchSize = 9 * 64
BatchSize についてを扱う以下のような `case class` を追加した後、`largeBatchSize` を `BatchSize` 型としたほうが良いかもしれません。

```scala
case class BatchSize(value: Int) {
  require(value > 0, "batch size must be positive")
}
```

```suggestion
  final val largeBatchSize = BatchSize(9 * 64)
```

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  final val smallBatchSize = 64
`largeBatchSize` の定義に対して書いたレビューの内容を行った後、以下のように変更すると良いと思います。

```suggestion
  /**
   * ガチャ券を64個(= 64 * 1スタック)のバッチでガチャポイントに変換する際のバッチサイズ
   */
  final val smallBatchSize = BatchSize(64)
  
   /**
    * ガチャ券へのポイント交換にて一度に得られるガチャ券の上限
    */
  final val maxBatchSize = largeBatchSize
```

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/gachapoint/GachaPoint.scala
> +  lazy val useInSmallBatch: GachaPoint.Usage = {
```scala
  private def useInBatch(batchSize: BatchSize): GachaPoint.Usage = {
    val ticketCount = availableTickets.min(batchSize.value).toInt

    val expToUse = GachaPoint.perGachaTicket.exp.amount * ticketCount
    val remaining = GachaPoint.ofNonNegative(exp.amount - expToUse)

    GachaPoint.Usage(remaining, ticketCount)
  }
```

のような関数を定義した後、`useInLargeBatch` と `useInSmallBatch`を
```scala
  /**
   * ガチャポイントを576個(= 64 * 9スタック)のバッチでガチャ券に変換した際のポイントの変化を計算する。
   */
  lazy val useInLargeBatch: GachaPoint.Usage = useInBatch(GachaPoint.largeBatchSize)

  /**
   * ガチャポイントを64個(= 64 * 1スタック)のバッチでガチャ券に変換した際のポイントの変化を計算する。
   */
  lazy val useInSmallBatch: GachaPoint.Usage = useInBatch(GachaPoint.smallBatchSize)
```

のように書き換えると良いと思います。

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/BatchUsageSemaphore.scala
>     * バッチでのガチャポイント変換を行い、 [[BatchUsageSemaphore.usageInterval]]の間使用不可にする作用。
```suggestion
   * 512個(= 64 * 9スタック)のバッチでのガチャポイント変換を行い、 [[BatchUsageSemaphore.usageInterval]]の間使用不可にする作用。
```

2024-09-03 15:31 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/BatchUsageSemaphore.scala
> +  def trySmallBatchTransaction: F[Unit] =
```suggestion
  /**
   * 64個(= 64 * 1スタック)のバッチでのガチャポイント変換を行い、[[BatchUsageSemaphore.usageInterval]]の間使用不可にする作用。
   */
  def trySmallBatchTransaction: F[Unit] =
```

2024-09-03 15:57 UTC, kuroma6666 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/gachapoint/domain/BatchUsageSemaphore.scala
>     * バッチでのガチャポイント変換を行い、 [[BatchUsageSemaphore.usageInterval]]の間使用不可にする作用。
64* 9stは512個でなく→576個が正なのでそのように読み替えることにします。

2024-09-03 16:59 UTC, rito528 requested changes
otherwise LGTM.

2024-09-03 16:59 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
>        val effect: FilteredButtonEffect = LeftClickButtonEffect(
```suggestion
      val leftClickEffect: FilteredButtonEffect = LeftClickButtonEffect(
```

2024-09-03 16:59 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
> +      val rightEffect: FilteredButtonEffect = RightClickButtonEffect(
```suggestion
      val rightClickEffect: FilteredButtonEffect = RightClickButtonEffect(
```

2024-09-03 16:59 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/menus/stickmenu/FirstPage.scala
> +        Button(itemStack, effect, rightEffect)
```suggestion
        Button(itemStack, leftClickEffect, rightClickEffect)
```

2024-09-03 17:05 UTC, rito528 approved these changes
LGTM.
ありがとうございます👌

2024-09-03 17:05 UTC, merged