feat: GBの表示内容にモブ討伐総数欄を追加
GiganticMinecraft/SeichiAssist pull request #2379
Opened 2024-09-15 06:59 UTC by kuroma6666

close #2326

----

### このPRの変更点と理由:
- GBのLoreにモブ討伐総数を表示する機能を追加

### 補足情報:
- 表示イメージ：
![image](https://github.com/user-attachments/assets/3592fa05-c2f4-46b4-9c83-aeac34f5d65a)

2024-09-21 16:14 UTC, kuroma6666 commented
@rito528 
お手すきの際にご確認お願いします

2024-09-25 16:20 UTC, rito528 requested changes
Otherwise LGTM.

2024-09-25 16:20 UTC, rito528 commented on src/main/scala/com/github/unchama/seichiassist/data/player/GiganticBerserk.scala
> +  }
```suggestion
  /**
   * @return 今までに倒した敵の総数
   */
  def totalNumberOfKilledEnemies: Int = {
    val currentStage = stage * 10
    val previousLevel = level - 1
    val previousStageLevel = currentStage + previousLevel
    
    LevelThresholds.giganticBerserkLevelList.take(previousStageLevel).sum + exp
  }
```

2024-09-25 16:46 UTC, kuroma6666 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/PassiveSkillMenu.scala
> +                s"$GRAY${openerData.giganticBerserk.exp}/${openerData.giganticBerserk.requiredExpToNextLevel()}",
指摘の内容の通りで、同じ項目が2つ生えてますね。。

2024-10-12 07:28 UTC, rito528 approved these changes
LGTM👍👍
ありがとうございます！

2024-10-12 07:28 UTC, merged