Feature/545
GiganticMinecraft/SeichiAssist pull request #547
Opened 2020-06-18 09:29 UTC by KisaragiEffective

this closes #545

2020-12-12 15:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/PresentCommand.java
> +        ONE,;
SOMEONEの方が適当？

2020-12-12 15:47 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/PresentCommand.java
> +package com.github.unchama.seichiassist.commands.legacy;
scala+コマンドビルダーに置き換えておく

2020-12-13 06:02 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/PresentCommand.java
> +        }
```suggestion
```

2020-12-26 08:03 UTC, KisaragiEffective commented on src/main/resources/db/migration/Vx.x.x__Create_present_tables.sql
> +CREATE TABLE presents(
保険として `if not exists` を敷いておく

2020-12-26 08:03 UTC, KisaragiEffective commented on src/main/resources/db/migration/Vx.x.x__Create_present_tables.sql
> +CREATE TABLE present_state(
同上

2020-12-26 08:03 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/SeichiAssist.scala
>  package com.github.unchama.seichiassist
TODO: `develop` ブランチのマージ

2020-12-26 08:03 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/PresentCommand.scala
> +
ファイル分割？

2020-12-26 08:03 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/PresentCommand.scala
> +}
`BukkitCodec`当たりに移譲しても良さそう

2020-12-26 13:07 UTC, KisaragiEffective commented
ready for review.

2020-12-28 16:49 UTC, KisaragiEffective commented on src/main/resources/db/migration/Vx.x.x__Create_present_tables.sql
> +use seichiassist;
@KisaragiEffective このファイルの名前を変えろ

2020-12-30 05:26 UTC, kory33 reviewed
とりあえず

2020-12-30 05:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +        MessageEffect(id2state.map { i2s =>
```Scala
{ case (id, claimingState) =>
```

でdestructureできます

2020-12-30 06:07 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +                showType.toIO
```suggestion
                val eff = for {
                  _ <- repo.claimPresent(player, presentId)
                  items <- repo.getAllPresent
                } yield {
                  SequentialEffect(
                    Util.grantItemStacksEffect(items(presentId)),
                    MessageEffect(s"ID: ${presentId}のプレゼントを付与しました。")
                  )
                }
                eff.toIO
```

2021-03-18 08:38 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/JdbcBackedPresentRepository.scala
> +class JdbcBackedPresentRepository[F[_] : Sync] {
fixed in 859f5c0

2021-03-18 08:38 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +        MessageEffect(id2state.map { i2s =>
fixed in 859f5c0

2021-03-18 08:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +   * </ul>
use markdown.

2021-03-22 16:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/JdbcBackedPresentRepository.scala
> +          .apply()
resolved in 7bb0a8c

2021-03-22 16:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +            .map(Bukkit.getOfflinePlayer)
resolved

2021-03-26 16:30 UTC, KisaragiEffective commented
ready-for-review

2021-03-27 14:40 UTC, KisaragiEffective commented
ページネーションは`JdbcBackedPresentPersistence`で行っても良いですか…？

2021-03-28 05:55 UTC, kory33 reviewed
とりあえず

2021-03-28 05:55 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/GlobalPlayerAccessor.scala
> +private[present] object GlobalPlayerAccessor {
これSeichiAssistの各箇所で多分有用なので `com.github.unchama.seichiassist.domain` に `UuidToLastSeenName` みたいな `trait` を切って `present` システムに(implicit)引数で渡すなどした方が良さそう

2021-03-28 05:55 UTC, kory33 commented
> ページネーションは`JdbcBackedPresentPersistence`で行っても良いですか…？

良いと思います

2021-03-28 10:54 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/JdbcBackedPresentPersistence.scala
> +  private final val definitionTable = "presents"
```suggestion
  private final val definitionTable = "present"
```

2021-03-28 10:56 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/PresentPersistence.scala
> +   * 指定したPresentIDに対応するプレゼントを物理消去する。
TODO: PresentPersistenceに適用して、JdbcBackedPresentPersistenceに物理消去する旨を書く

2021-03-28 21:58 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/GlobalPlayerAccessor.scala
> +private[present] object GlobalPlayerAccessor {
fixed in bd4e566

2021-03-28 21:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/PresentPersistence.scala
> +  def define(itemstack: ItemStack): F[Option[PresentID]]
fixed in 6753fa7

2021-03-28 21:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/PresentPersistence.scala
> +   * 指定したPresentIDに対応するプレゼントを物理消去する。
fixed in c284566

2021-03-28 22:09 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/PresentPersistence.scala
> +   * プレイヤーが有効なプレゼントを受け取ることができるかどうか列挙する。
> - Mapの値域は `PresentClaimingState.Unavailable` を含みますか？

含むことを想定しています。

> - もしそうならば、 `mapping` とキーの集合は一致しますか？

利便性のために一致することを想定していますが、現在の状況では`withDefault`を使っているためfetchStateの方がキーを(暗黙に)たくさん持ちます。ただ、これは共通制約と一貫性がないため、コミットではキーが一致する実装に差し替えます。

2021-03-29 15:54 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/PresentPersistence.scala
> +   * プレイヤーが有効なプレゼントを受け取ることができるかどうか列挙する。
fixed in f1c2814

2021-03-29 15:55 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/infrastructure/JdbcBackedPresentRepository.scala
> +class JdbcBackedPresentRepository[F[_] : Sync] {
fixed in a703fc8

2021-03-29 18:34 UTC, kory33 reviewed
二点だけ、他良さそうです！

2021-03-29 18:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/domain/actions/UuidToLastSeenName.scala
> +  def entries: F[Map[UUID, String]]
どの程度大きな `Map` か不明瞭なので、整地鯖に参加したことがありプレーヤーデータが保存されているプレーヤーのUUIDから、我々が(mojangに問い合わせずとも)知る限り最新の名前を取ってくる、というのを書いて良さそう

2021-03-29 18:34 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +      .execution { context =>
パーミッションチェック無いとマズそう？

2021-03-30 06:55 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +      .execution { context =>
まずいです、要修正

2021-03-30 07:06 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +      .execution { context =>
fixed in 2fda216

2021-03-30 07:06 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/domain/actions/UuidToLastSeenName.scala
> +  def entries: F[Map[UUID, String]]
fixed in e90a45d

2021-03-30 07:21 UTC, kory33 requested changes

2021-03-30 07:21 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/present/bukkit/command/PresentCommand.scala
> +          IO.pure(MessageEffect(s"IDが${presentId}のプレゼントの消去は正常に行われました。"))
実行されない作用です

```suggestion
          for {
            _ <- NonServerThreadContextShift[F].shift
            _ <- persistence.delete(presentId)
          } yield MessageEffect(s"IDが${presentId}のプレゼントの消去は正常に行われました。")
```

2021-03-30 08:15 UTC, kory33 approved these changes
LGTM、ありがとうございます！

2021-03-30 08:16 UTC, merged