第1回 Java -> Scala
GiganticMinecraft/SeichiAssist pull request #673
Opened 2020-09-13 03:07 UTC by stouma915

すみません何回かに分けます

2020-09-13 05:30 UTC, KisaragiEffective requested changes

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  private def getIntFailSafe(path: String): Integer = Integer.parseInt(config.getString(path))
```suggestion
  private def getIntFailSafe(path: String): Int = Integer.parseInt(config.getString(path))
```
avoid boxing

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getGachaPresentInterval: Integer = getIntFailSafe("presentinterval")
```suggestion
  def getGachaPresentInterval: Int = getIntFailSafe("presentinterval")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getDualBreaklevel: Integer = getIntFailSafe("dualbreaklevel")
```suggestion
  def getDualBreaklevel: Int = getIntFailSafe("dualbreaklevel")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getMultipleIDBlockBreaklevel: Integer = getIntFailSafe("multipleidblockbreaklevel")
```suggestion
  def getMultipleIDBlockBreaklevel: Int = getIntFailSafe("multipleidblockbreaklevel")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getPassivePortalInventorylevel: Integer = getIntFailSafe("passiveportalinventorylevel")
```suggestion
  def getPassivePortalInventorylevel: Int = getIntFailSafe("passiveportalinventorylevel")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getDokodemoEnderlevel: Integer = getIntFailSafe("dokodemoenderlevel")
```suggestion
  def getDokodemoEnderlevel: Int = getIntFailSafe("dokodemoenderlevel")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getMineStacklevel(i: Integer): Integer = getIntFailSafe("minestacklevel" + i)
```suggestion
  def getMineStacklevel(i: Int): Int = getIntFailSafe("minestacklevel" + i)
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getLvMessage(i: Integer): String = config.getString("lv" + i + "message", "")
```suggestion
  def getLvMessage(i: Int): String = config.getString("lv" + i + "message", "")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getServerNum: Integer = getIntFailSafe("servernum")
```suggestion
  def getServerNum: Int = getIntFailSafe("servernum")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getSubHomeMax: Integer = getIntFailSafe("subhomemax")
```suggestion
  def getSubHomeMax: Int = getIntFailSafe("subhomemax")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getDebugMode: Integer = getIntFailSafe("debugmode")
```suggestion
  def getDebugMode: Int = getIntFailSafe("debugmode")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getMebiusDebug: Integer = getIntFailSafe("mebiusdebug")
```suggestion
  def getMebiusDebug: Int = getIntFailSafe("mebiusdebug")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def rateGiganticToRingo(): Integer = getIntFailSafe("rategigantictoringo")
```suggestion
  def rateGiganticToRingo(): Int = getIntFailSafe("rategigantictoringo")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getRoadY: Integer = getIntFailSafe("road_Y")
```suggestion
  def getRoadY: Int = getIntFailSafe("road_Y")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getTemplateKeepAmount: Integer = getIntFailSafe("GridTemplateKeepAmount")
```suggestion
  def getTemplateKeepAmount: Int = getIntFailSafe("GridTemplateKeepAmount")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getGridLimitPerWorld(world: String): Integer = Integer.parseInt(config.getString("GridLimitPerWorld." + world, config.getString("GridLimitDefault")))
```suggestion
  def getGridLimitPerWorld(world: String): Int = 
    Integer.parseInt(config.getString("GridLimitPerWorld." + world, 
    config.getString("GridLimitDefault")))
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getRoadLength: Integer = getIntFailSafe("road_length")
```suggestion
  def getRoadLength: Int = getIntFailSafe("road_length")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getSpaceHeight: Integer = getIntFailSafe("space_height")
```suggestion
  def getSpaceHeight: Int = getIntFailSafe("space_height")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getRoadBlockID: Integer = getIntFailSafe("road_blockid")
```suggestion
  def getRoadBlockID: Int = getIntFailSafe("road_blockid")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getRoadBlockDamage: Integer = getIntFailSafe("road_blockdamage")
```suggestion
  def getRoadBlockDamage: Int = getIntFailSafe("road_blockdamage")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getContributeAddedMana: Integer = getIntFailSafe("contribute_added_mana")
```suggestion
  def getContributeAddedMana: Int = getIntFailSafe("contribute_added_mana")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getLimitedLoginEventItem(i: Integer): Integer = config.getInt("LimitedLoginEvent.DAY" + i + "_Item")
```suggestion
  // TODO: anti typesafe: getIntのnull値を0にする仕様を使っている
  def getLimitedLoginEventItem(i: Int): Int = config.getInt("LimitedLoginEvent.DAY" + i + "_Item")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getLimitedLoginEventAmount(i: Integer): Integer = config.getInt("LimitedLoginEvent.DAY" + i + "_Amount")
```suggestion
  def getLimitedLoginEventAmount(i: Int): Int = config.getInt("LimitedLoginEvent.DAY" + i + "_Amount")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getNewYearDropProbability: Integer = getIntFailSafe("NewYearEvent.NewYearBagDropProbability")
```suggestion
  def getNewYearDropProbability: Int = 
    getIntFailSafe("NewYearEvent.NewYearBagDropProbability")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getWorldSize: Integer = getIntFailSafe("world_size")
```suggestion
  def getWorldSize: Int = getIntFailSafe("world_size")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getGiganticFeverMinutes: Integer = getIntFailSafe("gigantic_fever_minutes")
```suggestion
  def getGiganticFeverMinutes: Int = getIntFailSafe("gigantic_fever_minutes")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/Config.scala
> +  def getGiganticBerserkLimit: Integer = getIntFailSafe("GBLimit")
```suggestion
  def getGiganticBerserkLimit: Int = getIntFailSafe("GBLimit")
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/GachaCommand.scala
> +      if (id >= 0) present = SeichiAssist.gachadatalist.apply(id).copy
```suggestion
      if (id >= 0) present = SeichiAssist.gachadatalist(id).copy
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/GachaCommand.scala
> +  @Override def onCommand(sender: CommandSender, cmd: Command, label: String, args: Array[String]): Boolean = {
```suggestion
  @Override
  def onCommand(sender: CommandSender, cmd: Command, label: String, args: Array[String]): Boolean = {
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/GachaCommand.scala
> +                   */ if (!sender.isInstanceOf[Player]) {
```suggestion
      /*
       * コンソールからのコマンドは処理しない - ここから
       */
    if (!sender.isInstanceOf[Player]) {
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/legacy/GachaCommand.scala
> +                   */ if (args.length == 2) {
```suggestion
      /*
      * ここまで
      */
    if (args.length == 2) {
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/GridTemplate.scala
> +class GridTemplate(var aheadAmount: Int, var behindAmount: Int, var rightAmount: Int, var leftAmount: Int) //コンストラクタ
```suggestion
class GridTemplate(val aheadAmount: Int, val behindAmount: Int, val rightAmount: Int, val leftAmount: Int)
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/Mana.scala
> +class Mana @deprecated() //引数なしのコンストラクタ
indent

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/subhome/SubHome.scala
> +class SubHome(val location: Location, val name: String) {
```suggestion
case class SubHome(val location: Location, val name: String) {
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/subhome/SubHome.scala
> +// TODO Scalaize and make this case class
```suggestion
```

2020-09-13 05:30 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/Mana.scala
> +		if(SeichiAssist.DEBUG){
TAB

2020-09-13 05:40 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/data/GridTemplate.scala
> +class GridTemplate(val aheadAmount: Int, val behindAmount: Int, val rightAmount: Int, val leftAmount: Int)
```suggestion
class GridTemplate(var aheadAmount: Int, var behindAmount: Int, var rightAmount: Int, var leftAmount: Int)
```

2020-12-04 11:30 UTC, stouma915 commented
https://github.com/GiganticMinecraft/SeichiAssist/pull/778
↑放置状態になってしまったのでこちらに

2020-12-04 11:30 UTC, closed without merging