エリトラで飛行した状態のまま下へ落ちていくだけになる状態への対応
GiganticMinecraft/SeichiAssist pull request #698
Opened 2020-10-10 09:30 UTC by Lucky3028

This closes #670.

2020-10-10 09:42 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerMoveListener.scala
> +  def onPlayerMoveToVoid(event: PlayerMoveEvent): Unit = {
```suggestion
  def onPlayerfallenToVoid(event: PlayerMoveEvent): Unit = {
```

2020-10-10 09:45 UTC, Lucky3028 commented
ありがとうございますー！直しました。

2020-10-10 09:46 UTC, KisaragiEffective approved these changes

2020-10-11 11:01 UTC, kory33 requested changes
この辺独立したサブシステムとして動かしたい([こんな感じ](https://github.com/GiganticMinecraft/SeichiAssist/tree/4fd30ee432d270c06a59143dc53fcf64422b3d21/src/main/scala/com/github/unchama/seichiassist/subsystems))感があるのでそっちに移せたりしますでしょうか 🙇

2020-10-11 11:02 UTC, Lucky3028 commented
ま、まじ？うーん...やってみます...

2020-10-11 14:22 UTC, Lucky3028 commented
すみません、しばらく粘ってみたんですが、さっぱりわからんとです,,,

2020-10-12 04:15 UTC, karayuumac commented
@Lucky3028 
サブシステム化の部分、自分が引き継いでも大丈夫ですか？

2020-10-12 04:28 UTC, Lucky3028 commented
@karayuumac 大丈夫です！助かりますー！

2020-10-12 04:31 UTC, karayuumac commented
とりあえず、GiganticMinecaft:freature/#670に取り込みます。

2020-10-12 04:31 UTC, merged