実績予約システムの追加
GiganticMinecraft/SeichiAssist pull request #733
Opened 2020-10-27 11:04 UTC by karayuumac

プレイヤーがオフラインの際にデータベースに保存する部分までは完成し動いていますが、プレイヤーがログインした際に実績が正常に与えられていないようなのです。
つきましては、その理由とコードレビューの方をお願い致します。

2020-10-27 11:33 UTC, kory33 commented on src/main/resources/db/migration/V1.5.0__Add_booked_achievement_table.sql
> +    is_received    boolean not null
- `is_received` -> `has_been_received` ?
  - この boolean を記憶するのならそもそも列消すでも良さそう
  - event sourcing的な作りにするなら `is_received` をそもそも記録しないで良さそうです(readする側、つまりPlayer join時の処理で `Set` に落として `filter` すればよい)

2020-10-27 11:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/commands/AchievementCommand.scala
> +              val manipulator = SeichiAssist.databaseGateway.bookedAchievementManipulator
ここは少し古い設計を引きずってそうです
理想的にはDBを操作するリポジトリ(リポジトリパターンと呼ばれるもので、永続化層への操作を抽象化してDBの都合をすべて隠したinterfaceへの実装のことです)を `implicit` 等で受け取って、それに対する操作にとどめるべきです

[シグネチャがちょっと複雑な例](https://github.com/GiganticMinecraft/SeichiAssist/blob/77ce45d9c248d3e2e29e8a7aa62220ffb384253a/src/main/scala/com/github/unchama/seichiassist/subsystems/managedfly/bukkit/controllers/BukkitFlyCommand.scala#L47)

[この例](https://github.com/GiganticMinecraft/SeichiAssist/blob/0d83b6192170254bc79c3af58f88dd23cf62a03d/src/main/scala/com/github/unchama/itemmigration/service/ItemMigrationService.scala#L6)ではServiceと呼ばれるアプリケーションロジックをかき集めた箇所がリポジトリに依存するようにしています。コマンドやリスナ等の「コントローラ」と呼ばれるエントリポイントのような箇所は、リポジトリの実装をサービスのコンストラクタに渡してサービスを利用することができます。

2020-10-27 11:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/commands/AchievementCommand.scala
> +              } yield successEffect
```suggestion
              } yield MessageEffect {
                s"$playerName は現在サーバーにログインしていません。\n予約システムに書き込みます。"
              }
```

これで等価だったりしそう？

2020-10-27 11:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +        )
エフェクトを実行できてないです

`cats.implicits._` を import した上で、

```suggestion
        _ <- EitherT.right[TargetedEffect[CommandSender]](
          bookedAchievementIds
            .traverse(playerData.tryForcefullyUnlockAchievement)
        )
```

で通ったりしませんか？

2020-10-27 12:49 UTC, karayuumac commented
予約を削除できるようなコマンドも追加したほうが良いと思うので、予約実績のデータベースを作るよりも直接PlayerDataデータベースに書き込む方が良いかなぁと思ったのですがどうでしょうか？

2020-10-27 12:51 UTC, KisaragiEffective commented
PlayerDataテーブルはDBで大きすぎるのでカラムを追加 (?) するのは避けたほうが良いです、というか避けてください (個人的意見)

2020-10-27 12:53 UTC, karayuumac commented
あー申し訳ない。
カラムの追加ではなく、実績データは`TitleFlags`で管理されてると思うのでそれを書き換えるということです。

2020-10-27 12:55 UTC, KisaragiEffective commented
TitleFlagsは1ビットにつき1つの実績を取得しているか表すカラムだったような？

2020-10-28 07:18 UTC, karayuumac commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +        )
`.traverse` のところで `No implicit arguments of type: Applicative[TargetedEffect]` になってしまいます。

2020-10-28 10:38 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +        )
そうか、 `Kleisli[F, *, Unit]` は確かにApplicativeではないですね…

```Scala
        _ <- EitherT.right[TargetedEffect[CommandSender]](
          SequentialEffect(
            bookedAchievementIds.map(playerData.tryForcefullyUnlockAchievement)
          )
        )
```

で良さそう？

2020-10-29 03:43 UTC, karayuumac commented
いろいろ参考にしていい感じにできたと思います！

2020-10-31 06:38 UTC, kory33 commented
@karayuumac 予約を削除する機能を付けたいなら `booked_achievement` を `booked_achievement_status_change` にして、付与するか奪取するかの `boolean` をレコードに持たせ、予約削除は(予約があれば)奪取するレコードを追加することで実現できそうです(必然的に付与した時刻を入れる必要が出ます)

2020-10-31 06:46 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/commands/AchievementCommand.scala
> +                    s"$playerName は現在サーバーにログインしていません。\n予約システムに書き込みます。"
```suggestion
                    s"$playerName は現在サーバーにログインしていません。\n予約システムに書き込みました。"
```

2020-10-31 06:46 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/infrastructure/JdbcBookedAchievementPersistenceRepository.scala
> +class JdbcBookedAchievementPersistenceRepository[SyncContext[_] : Sync](implicit SyncContext: Sync[SyncContext])
context boundはSync[SyncContext]をすでにimplicitで取っているので不要です

```suggestion
class JdbcBookedAchievementPersistenceRepository[SyncContext[_]](implicit SyncContext: Sync[SyncContext])
```

2020-11-15 04:58 UTC, karayuumac commented
剥奪処理もできました～

2020-11-15 08:31 UTC, kory33 requested changes
otherwise LGTM.

2020-11-15 08:31 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +        )
```suggestion
        val effects =
          for {
            (action, id) <- ids
          } yield action match {
            case AchievementOperation.GIVE => playerData.tryForcefullyUnlockAchievement(id)
            case AchievementOperation.DEPRIVE => playerData.forcefullyDepriveAchievement(id)
          }
        SequentialEffect(effects)
```

`.toMap` すると `Map[AchievementOperation, Int]` が返ってくるので不適です

2020-11-15 08:31 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +      .unsafeRunSync() match {
これをすると同期スレッドでDBアクセスが走ることになります

`SyncEffect` ではなく `ConcurrentEffect` を要求すれば
`Context.start(...)` で並列実行するプログラムを得ることができるようになります。
(その場合もはや `SyncContext` ではなくなるので型変数の名前も変えるべきっぽい)

なので `.start` 等をするプログラムを `runEffectAsync` に入れてやると良さそうです

2020-11-23 04:53 UTC, karayuumac commented
コメントしていただいた部分すべて直しました。

2020-11-23 05:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/service/AchievementBookingService.scala
> +  AsyncContext[_] : ConcurrentEffect
[nits] `attempt` と `EitherT` の `flatMap` くらいしか使っておらず、

 - `EitherT[F, A, B]` の `flatMap` は `F` で `flatMap` が使えることを前提としている
 - `attempt` は `ApplicativeError` で定義されている

ことから、 `flatMap` と `attempt` が入っている [`MonadThrow[F[_]] = MonadError[F, Throwable]`](https://github.com/typelevel/cats-effect/blob/608f01366e54632ffc9fb6f8226373e78557854c/core/shared/src/main/scala/cats/effect/package.scala#L43) 程度の要求で大丈夫そう

2020-11-23 05:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/domain/BookedAchievementPersistenceRepository.scala
> +trait BookedAchievementPersistenceRepository[AsyncContext[_], Key] {
実態は `SyncContext` なので `SyncContext[_]` とするか名前を消して `F[_]` として良さそう

2020-11-23 05:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/System.scala
> +    AsyncContext[_] : ConcurrentEffect : NonServerThreadContextShift
`NonServerThreadContextShift` はメインスレッド以外のスレッドプールに制御を移すためのものですが、特に使用してないので要求を外して良さそう？

2020-11-23 05:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/service/AchievementBookingService.scala
> +  }
[nits] この辺、例外を握りつぶしてますがロギングとか考えるとそのまま実行していいんじゃないかなーとも思います　どうでしょう？

2020-11-23 05:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/command/AchievementCommand.scala
> +                )
```suggestion
                SequentialEffect(
                  Kleisli.liftF(
                    service.writeAchivementId(playerName, achievementNumber, operation).start
                  ),
                  MessageEffect(
                    List(
                      s"$playerName の No.$achievementNumber の実績を${
                        operation match {
                          case AchievementOperation.GIVE => "付与"
                          case AchievementOperation.DEPRIVE => "剥奪"
                        }
                      }します。",
                      s"$playerName は現在サーバーにログインしていません。\n予約システムに書き込みました。"
                    )
                  )
                )
```
とすると `effectEnvironment` への言及が消えそう

2020-11-23 05:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +    )
`playerData.tryForcefullyUnlockAchievement` は[運営チームなどのメンバーがトリガーすることを想定した `TargetedEffect[CommandSender]` なので](https://github.com/GiganticMinecraft/SeichiAssist/blob/3ec3f5d4cce53a7ebc32ae5af8605e41ef946dd1/src/main/scala/com/github/unchama/seichiassist/data/player/PlayerData.scala#L804)、 `.run` する時は `.run(Bukkit.getConsoleSender)` とすると良さそうです。

また、Effectの計算のために副作用を発生させてしまっているため、

```suggestion
    val effectRunner = Bukkit.getConsoleSender
    val program = {
      for {
        ids <- EitherT(service.loadBookedAchievementsIds(player.getUniqueId))
        _ <- EitherT.right(
          ids.map {
            case (AchievementOperation.GIVE, id) =>
              playerData.tryForcefullyUnlockAchievement(id).run(effectRunner)
            case (AchievementOperation.DEPRIVE, id) =>
              playerData.forcefullyDepriveAchievement(id).run(effectRunner)
          }.sequence
        )
      } yield ()
    }.value

    effectEnvironment.runEffectAsync("未受け取りの予約実績を読み込み付与する", program.start)
```

みたいにすると尚良さそう？

2020-11-23 13:21 UTC, karayuumac commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/service/AchievementBookingService.scala
> +  }
確かに。例外潰さないほうがよさそうですね。変更します。

2020-11-24 05:17 UTC, karayuumac commented
なおしました！

2020-11-24 07:29 UTC, kory33 requested changes
非同期処理にするとこだけお願いします！他良さそうです！

(Listener/Command層で `.start` してしまうか、Service層で `F[_]: Concurrent` を要求して `.start` してあげるかのどちらかで良さそうです)

2020-11-24 07:29 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/command/AchievementCommand.scala
> +                    service.writeAchivementId(playerName, achievementNumber, operation).toIO
```suggestion
                    service.writeAchivementId(playerName, achievementNumber, operation).toIO.start.as(())
```

2020-11-24 07:29 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +      ids <- service.loadBookedAchievementsIds(player.getUniqueId).toIO
```suggestion
      ids <- service.loadBookedAchievementsIds(player.getUniqueId).toIO.start.as(())
```

2020-11-24 07:53 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +      ids <- service.loadBookedAchievementsIds(player.getUniqueId).toIO
あーこれだとダメですね(idsの結果を待つ必要があった)

`F[_] : NonServerThreadContextShift` を要求したうえで、

```Scala
      _ <- NonServerThreadContextShift[F].shift
      ids <- service.loadBookedAchievementsIds(player.getUniqueId)
      _ <- ids.map {
        case (AchievementOperation.GIVE, id) =>
          playerData.tryForcefullyUnlockAchievement(id).run(effectRunner)
        case (AchievementOperation.DEPRIVE, id) =>
          playerData.forcefullyDepriveAchievement(id).run(effectRunner)
      }.sequence.liftIO
```

みたいにして良さそうです

2020-11-24 08:02 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +      ids <- service.loadBookedAchievementsIds(player.getUniqueId).toIO
補足: 実はplayerdataに対する非同期書き込みは基本危なくて、何故なら `.shift` してから書き込みを行うわずかな時間の間にプレーヤーが退出して終了処理が行われる可能性が(理論上)存在するんですね。しかしjoin時に同期的にDBアクセスを行うというロジックが蓄積するのもかなりマズいという認識があり、 `.shift` を行う実装は安全性を妥協してパフォーマンスを取っていると言えます。

根本的な対策としてはプレーヤーデータに対するトランザクションのような仕組みを導入するしかないと思っているのですが、その実装コストは激重とまではいかないですが少し時間が掛かると思います。

この事情はコメントに書いてもいいかもしれないです。

2020-11-24 08:59 UTC, karayuumac commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/command/AchievementCommand.scala
> +                    service.writeAchivementId(playerName, achievementNumber, operation).toIO
単純な疑問点なのですが、この`.as(())`はどのような意味を持つのでしょうか？もし`.start`だけだとどうなりますか？

2020-11-24 09:04 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/command/AchievementCommand.scala
> +                    service.writeAchivementId(playerName, achievementNumber, operation).toIO
`Functor[F]` がある `F[_]`、 `fa: F[A]` と `b: B` について、 `fa.as(b)` は `fa.map(_ => b)` と同じであると[定義されています](https://github.com/typelevel/cats/blob/857cceb91861c5c818abb6b9a5d52811b63fa322/core/src/main/scala/cats/Functor.scala#L131)(シグネチャが違うのは、 `simulacrum.typeclass` アノテーションで生成した版を使っているからです)。

`.start` だけだと戻り値型が `Fiber[IO, Unit]` になってしまうので、戻ってくる `Fiber` (非同期で開始されたタスクへのハンドラ) を捨てて、計算結果を `()` にするというのが `.as(())` です。

2020-11-24 09:13 UTC, karayuumac commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +      ids <- service.loadBookedAchievementsIds(player.getUniqueId).toIO
頂いた例だと、`value liftIO is not a member of cats.effect.IO[List[Unit]]`というエラーが出てしまいます。
```scala
      _ <- NonServerThreadContextShift[F].shift
      ids <- service.loadBookedAchievementsIds(player.getUniqueId)
      _ <- LiftIO[F].liftIO(ids.map {
        case (AchievementOperation.GIVE, id) =>
          playerData.tryForcefullyUnlockAchievement(id).run(effectRunner)
        case (AchievementOperation.DEPRIVE, id) =>
          playerData.forcefullyDepriveAchievement(id).run(effectRunner)
      }.sequence)

```
こんな感じでどうでしょうか？

2020-11-24 09:14 UTC, karayuumac commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/command/AchievementCommand.scala
> +                    service.writeAchivementId(playerName, achievementNumber, operation).toIO
なるほど！ありがとうございます。

2020-11-24 09:28 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/bookedachivement/bukkit/listener/GrantBookedAchievementListener.scala
> +      ids <- service.loadBookedAchievementsIds(player.getUniqueId).toIO
(エーなんで `LiftIO` は `@typeclass` 宣言されていないんだ…)

それで良いと思います！ 👍

2020-11-25 01:29 UTC, karayuumac commented
なおしました～

2020-11-25 01:38 UTC, kory33 approved these changes
良さそうです！
ありがとうございます～！

2020-11-25 01:39 UTC, merged