Projectileをspawnという単語が保護名に含まれるときに発射させないように
GiganticMinecraft/SeichiAssist pull request #766
Opened 2020-11-14 13:16 UTC by Lucky3028

This closes #746

ついでにShift+右クリックでできてしまうのも修正

2020-11-15 02:04 UTC, KisaragiEffective requested changes

2020-11-15 02:04 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/listener/SpawnRegionProjectileInterceptor.scala
> +        val isInSpawnRegion = getRegions(player.getLocation).asScala.exists(_.getId == "spawn")
`spawn`をプレイヤー名に含んでいるプレイヤーが自動保護を作成すると飛翔体が発射できなくなるので、飛翔体の発射を禁止する保護の`Set`を定めておいたほうが良さそう

2020-11-15 07:22 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/SpawnRegionProjectileInterceptor.scala
> +        val isInSpawnRegion = getRegions(player.getLocation).asScala.exists(_.getId == "spawn")
(そもそも `.exists` だと完全一致ですけがそのような意図ですか？)

2020-11-15 07:58 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/listener/SpawnRegionProjectileInterceptor.scala
> +        val isInSpawnRegion = getRegions(player.getLocation).asScala.exists(_.getId == "spawn")
（あっほんとですね...うとうとしながらやってたので気づかなかった...）

2020-11-16 06:42 UTC, Lucky3028 commented
直しましたー
（Setを書くのは、もしかしてListenerじゃないほうよかったりします？）

2020-11-22 11:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/SpawnRegionProjectileInterceptor.scala
> +        getRegions(player.getLocation).forEach(rg => if (spawnRegions.contains(rg.getId)) event.setCancelled(true))
```suggestion
        if (getRegions(player.getLocation).map(_.getId).exists(spawnRegions.contains)) {
          event.setCancelled(true)
        }
```

2020-11-22 11:47 UTC, Lucky3028 commented
レビューありがとうございます、直しましたー

2020-11-22 12:48 UTC, kory33 approved these changes
👍

2020-11-22 12:49 UTC, merged