Discord上にも全体通知のメッセージを表示する
GiganticMinecraft/SeichiAssist pull request #777
Opened 2020-11-29 11:25 UTC by stouma915

close #678 
~~Windowsまじ許さん~~

2020-11-29 12:04 UTC, KisaragiEffective requested changes

2020-11-29 12:04 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                                  s"""curl -X POST -H "Content-Type: application/json" --data "{\\"content\\":\\"${Util.stringToUnicode(s"${player.getName}が全てのスキルを習得し、アサルトアーマーを解除しました！")}\\"}" $webhoo
ネイティブコマンドを発行するのはお行儀が悪くプラットフォーム可搬でないのでHttpConnectionなどを活用するべき

2020-11-29 12:04 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                        String curlCommand = Util.isWindows() ? "curl -X POST -H \"Content-Type: application/json\" --data \"{\\\"content\\\":\\\"" + Util.stringToUnicode(playerdata.lowercaseName() +
同上

2020-11-29 12:04 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/util/Util.scala
> +  def stringToUnicode(string: String): String = {
use higher-order function, not for loop

2020-11-29 13:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                                httpURLConnection.addRequestProperty("Content-Type", "application/JSON; charset=utf-8")
```suggestion
                                httpURLConnection.addRequestProperty("Content-Type", "application/json; charset=utf-8")
```

2020-11-29 13:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                                httpURLConnection.setRequestProperty("Content-Length", json.length.toString)
use `scala.util.chaining.tap`

2020-11-29 13:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                        String json = "{\"content\":\"" + playerdata.lowercaseName() + "がパッシブスキル:GiganticBerserkを完成させました！" + "\"}";
use raw string

2020-11-29 13:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                            httpURLConnection.setRequestProperty("Content-Length", String.valueOf(json.length()));
tap

2020-11-29 13:33 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                            httpURLConnection.addRequestProperty("Content-Type", "application/JSON; charset=utf-8");
```suggestion
                            httpURLConnection.addRequestProperty("Content-Type", "application/json; charset=utf-8");
```

2020-11-29 13:50 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                            httpURLConnection.setRequestProperty("Content-Length", String.valueOf(json.length()));
invalid

2020-11-29 14:02 UTC, stouma915 commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                        String json = "{\"content\":\"" + playerdata.lowercaseName() + "がパッシブスキル:GiganticBerserkを完成させました！" + "\"}";
JDKのバージョンが1.8なのでraw string使えないみたいです

2020-11-29 14:08 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.java
> +                        String json = "{\"content\":\"" + playerdata.lowercaseName() + "がパッシブスキル:GiganticBerserkを完成させました！" + "\"}";
`.java`だった、invalid

2020-11-29 14:09 UTC, KisaragiEffective submitted a review, later dismissed

2020-12-01 15:13 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                              Bukkit.getLogger.info("WebhookのURLが空のため、Discordへの通知を行いません。")
全く同じロジックが `GiganticBerserkTask.java` にも記載されています。
[rescueplayerパッケージ](https://github.com/GiganticMinecraft/SeichiAssist/tree/44e6a5bb9dfd601b5e4a7f4fd4759a6db0fca3e3/src/main/scala/com/github/unchama/seichiassist/subsystems/rescueplayer) のserviceオブジェクト等の切り方を参考にしてリポジトリパターンに切り出せないかを検討できないでしょうか？

2020-12-02 09:18 UTC, stouma915 commented
JavaのFutureがわけわかめだったのでGiganticBerserkTaskが.scalaになりました ~~(ついでにエラーも出ました)~~

2020-12-02 09:19 UTC, stouma915 commented
間違えてcloseしましたすみません

2020-12-05 03:23 UTC, kory33 commented
@stouma915 
subsystemをUtilシングルトンのように使うのはテスト可能性を下げると思っていて、
subsystemとして切り出すなら例えば以下のようにすべきかなと思います：

 - `...seichiassist.subsystems.discordmessage.api.DiscordMessageAPI` みたいな `trait` を用意する
   ```Scala
   trait DiscordMessageAPI {
     def send[F[_]: Concurrent](message: String): F[Unit]
   }
   ```
 - `DiscordMessageAPI` の Discord Webhook 用実装を作成する
   - 例えば `...subsystems.discordmessage.infrastructure.DiscordWebhookConfiguration` にwebhook urlを持たせ、
     ```Scala
     class DiscordWebhookMessageAPI(implicit configuration: discord.WebhookConfiguration)
       extends DiscordMessageAPI {
       override def broadcast[...](...): F[Unit] = { ... }
     }
     ```
 - `...subsystems.extbroadcast.System` に `webhookApi: DiscordMessageAPI` を露出させる
 - webhook APIを触りたいという箇所には `DiscordMessageAPI` を渡す

このようにすることでDiscordへメッセージを送るという関心だけ使用側に見えるようになり、
webhook url等のハンドリングを使用側がしないで良くなります。

2020-12-08 08:19 UTC, stouma915 commented
すみません、理解力皆無なのでもう少し詳しく教えていただけますか？

2020-12-09 08:19 UTC, KisaragiEffective requested changes

2020-12-09 08:19 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                              new WebhookService().sendMessage(webhookURL, s"${player.getName}が全てのスキルを習得し、アサルトアーマーを解除しました！").onComplete {
メソッドが呼ばれる度にインスタンスが生成され、そのコストを回避するためにより広いスコープへ移すべき

2020-12-09 08:19 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.scala
> +            new WebhookService().sendMessage(webhookURL, s"${playerdata.lowercaseName}がパッシブスキル:GiganticBerserkを完成させました！").onComplete {
同上

2020-12-09 08:28 UTC, KisaragiEffective commented
```scala
class SomeSender(implicit val discord: DiscordMessageAPI) {
  // stuff
}

implicit val dapi = subsystems.broadcast.webhookApi
// new SomeSender(dapi)と等価 - "implicit parameter"
val sender = new SomeSender
// SomeSenderを使った処理...
```

:thinking:

2020-12-10 12:26 UTC, stouma915 commented
> subsystems.extbroadcast.System に webhookApi: DiscordMessageAPI を露出させる

![image](https://user-images.githubusercontent.com/62248740/101772128-4cebfa80-3b2e-11eb-8766-5d6cb0e2fe3d.png)
こーゆーことですか？

2020-12-10 19:44 UTC, kory33 commented
> こーゆーことですか？
イメージとしてはそんな感じです！

> subsystemとして切り出すなら例えば以下のようにすべきかなと思います

と言ってしまっていましたが、APIオブジェクトを露出するよりも
```Scala
@typeclass trait CanMessageEveryoneThroughDiscord[F[_]] {
  def send(message: String): F[Unit]
}
```
のような型クラスを作り、
 - サブシステムは`CanMessageEveryoneThroughDiscord[F]`を`val`として露出
 - 利用側では `CanMessageEveryoneThroughDiscord[F]` を `implicit` 等で要求
をやるのが理想的だと思っています。

2020-12-11 13:56 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/webhook/service/WebhookService.scala
> +      .tap(_.addRequestProperty("User-Agent", "DiscordBot"))
`DiscordBot`とは少し違うような…？

2020-12-11 13:57 UTC, stouma915 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/webhook/service/WebhookService.scala
> +      .tap(_.addRequestProperty("User-Agent", "DiscordBot"))
User-AgentとしてDiscordBotを指定しないと403が返ってきます

2020-12-11 13:58 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/webhook/service/WebhookService.scala
> +      .tap(_.addRequestProperty("User-Agent", "DiscordBot"))
なるほど :thinking:

2020-12-11 13:59 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/webhook/service/WebhookService.scala
> +      .tap(_.addRequestProperty("User-Agent", "DiscordBot"))
```suggestion
      // User-AgentがDiscordBotでないばあい403が返却されるため
      .tap(_.addRequestProperty("User-Agent", "DiscordBot"))
```

2020-12-30 05:29 UTC, kory33 commented
@stouma915 すみません、こちらrebaseお願いできますか！

2020-12-30 05:44 UTC, stouma915 commented
rebaseしようとしてるんですが、conflictがやばすぎるのでいったんcloseでいいですか？

2020-12-30 05:49 UTC, kory33 commented
(conflict、`build.sbt` + `Config.java` + `SeichiAssist.scala` のみではないんです？)

2020-12-30 05:50 UTC, stouma915 commented
この3つを解消したらなぜか20個おまけされました:thinking:

2020-12-30 05:53 UTC, kory33 commented
rebaseだとデカいconflictになるのか　mergeでお願いします…

2020-12-30 06:11 UTC, stouma915 commented
びっくりするぐらい強引な方法で解消した
できました

2021-01-07 19:49 UTC, kory33 requested changes
I/F変えたほうが良さそうです…！

2021-01-07 19:49 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/webhook/service/WebhookService.scala
> +  def sendMessage(webhookURL: String, message: String): Future[Int] = Future {
- `webhookURL` はサービスが元より保持しているべき
 - ステータスコードを呼び出し側に返さずにこの層でハンドリングを完結させてしまうべき
 - サービスの使用箇所までサービスを渡すべき

2021-03-30 10:18 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                              new WebhookService().sendMessage(webhookURL, s"${player.getName}が全てのスキルを習得し、アサルトアーマーを解除しました！").onComplete {
つまり、implicit引数でインスタンスを召喚するべき

2021-03-30 10:18 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.scala
> +
DRY違反

2021-03-31 13:35 UTC, KisaragiEffective commented
なんでまたコンフリクトしてるんだ？

2021-04-02 22:15 UTC, kory33 commented on src/main/resources/config.yml
> +    GiganticBerserk: ""
これらって分ける必要があるでしょうか、全体通知するメッセージはすべて同じ個所に通知するものだったりしませんか？

2021-04-02 22:15 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                          } yield ()
実行されない作用です

2021-04-02 22:15 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/menus/skill/ActiveSkillMenu.scala
> +                              BroadcastMessageEffect(s"$GOLD$BOLD$notificationMessage")
Webhookを個別の概念として明示的に分ける必要ってあるでしょうか？
Message API的なものを生やし、全体通知とwebhook通知を同時に行うのをデフォルトとし、 `BroadcastMessageEffect` を使っている箇所をすべてそれで置き換えて良いような気がしますが、どうでしょう？

2021-04-02 22:15 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/task/GiganticBerserkTask.scala
> +        } yield ()
実行されない作用です

2021-04-03 11:24 UTC, KisaragiEffective commented
due to GH Actions workflow restriction

2021-04-03 11:25 UTC, merged