整地レベルアップ時のメッセージをconfig.ymlからコード上へ
GiganticMinecraft/SeichiAssist pull request #818
Opened 2020-12-13 09:43 UTC by Lucky3028

This closes #294

2020-12-14 16:26 UTC, kory33 requested changes
例外飛ばすと使用側でのハンドリングが必要になります…！

2020-12-14 16:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/data/SeichiLvUpMessages.scala
> +  def get(level: Int): String = messages.getOrElse(level, throw new IllegalArgumentException("指定された整地レベルに対応するメッセージが定義されていません。"))
```suggestion
  def get(level: Int): Option[String] = messages.get(level)
```

2020-12-14 16:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/data/player/PlayerData.scala
> +      player.sendMessage(s"$AQUA$lvMessage")
```suggestion
      SeichiLvUpMessages.get(l + 1).foreach { levelUpMessage =>
        player.sendMessage(s"$AQUA$levelUpMessage")
      }
```

2020-12-14 16:26 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/listener/PlayerJoinListener.scala
> +      player.sendMessage(SeichiLvUpMessages.get(1))
```suggestion
      SeichiLvUpMessages.get(1).foreach(player.sendMessage(_))
```

2020-12-15 02:54 UTC, Lucky3028 commented
レビューありがとうございます、直しました！

2020-12-15 16:51 UTC, kory33 approved these changes
👍

2020-12-15 16:51 UTC, merged