LimitedLoginEventを「複数景品」「複数期間」に対応させる
GiganticMinecraft/SeichiAssist pull request #820
Opened 2020-12-13 12:28 UTC by Lucky3028

This closes #365

2020-12-30 05:58 UTC, kory33 commented
`LimitedLoginEvent` が「複数期間」に対応するときってどういうのを想定していますか？期間が分かれる場合そもそも別の景品リストを参照すべきな感じがあります

2020-12-30 06:08 UTC, Lucky3028 commented
うーん、あらかじめこの時とこの時は絶対にこれを配る！って決定したからもうコードに入れておこうみたいな時ですかねー

2020-12-30 06:11 UTC, kory33 commented
同一のイベントを複数期間に発生させるということでしょうか？

2020-12-30 06:12 UTC, Lucky3028 commented
そうですね

2020-12-30 06:13 UTC, Lucky3028 commented
(でも言われてみれば、別々の景品リストであった方が後々楽そうな気がしてきました)

2020-12-30 07:06 UTC, kory33 commented
はい、その場合そこそこ大きな変更になると思います

2020-12-30 07:11 UTC, Lucky3028 commented
やってみます

2021-01-02 10:54 UTC, Lucky3028 commented
一応できましたが、こんな感じでどうでしょう...？

2021-01-08 09:14 UTC, Lucky3028 commented
レビューありがとうございます！直しました

2021-01-08 17:45 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/limitedlogin/LoginBonusItemList.scala
> +    case Everyday => dailyItem.flatMap(bonus => Some(Set(bonus)))
```suggestion
    case Everyday => dailyItem.map(bonus => Set(bonus))
```

2021-01-08 17:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/limitedlogin/LimitedLoginBonusGifter.scala
> +  private def giveLoginBonus(index: LoginBonusIndex)(implicit player: Player, event: LimitedLoginEvent): Unit = {
[nits] 「プレーヤーとイベント」の組が「文脈から明らか」な箇所って割と小さいので `player` と `event` は明示的に渡してしまってもいいかも…？

2021-01-08 17:50 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/limitedlogin/LimitedLoginBonusGifter.scala
> +      // TODO この処理javaの頃はなかったが、なくても大丈夫なのか？
> `TODO`

これはあったほうが良さそう

2021-01-08 17:53 UTC, kory33 requested changes
ほぼ良さそう、ここだけお願いします…！

2021-01-08 17:53 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/limitedlogin/LimitedLoginBonusGifter.scala
> +        else playerData.LimitedLoginCount + 1
`lastCheckedDate` がその日ではない、というのを「本日初ログイン」の判定に使うまでは良いんですが、「どのイベント中に何度日付をまたいでログインした」というデータがplayerDataに無いと「別のイベントが開始されると前開催されていたイベントでのカウントがリセットされる」という挙動になります

2021-01-11 05:38 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/limitedlogin/LimitedLoginBonusGifter.scala
> +        else playerData.LimitedLoginCount + 1
なるほど
そうすると、`lastCheckedDate`をイベントごとに用意しなくてはいけなくなるんですかね...うーん...

2021-04-06 14:46 UTC, Lucky3028 commented
やっている暇が割となくなってしまいそうなので、とりあえず一旦クローズします。

2021-04-06 14:46 UTC, closed without merging