/rmpで対象保護を全削除でぉるようにする
GiganticMinecraft/SeichiAssist pull request #823
Opened 2020-12-14 12:11 UTC by Lucky3028

2020-12-14 12:11 UTC, Lucky3028 commented
This closes #667

2020-12-14 12:19 UTC, KisaragiEffective requested changes

2020-12-14 12:19 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala
> +      case None | Some(false) => return MessageEffect(s"${commandName}コマンドは保護をかけて整地する整地ワールドでのみ使用出来ます")
:stop_sign: **エラー**:
```
[error] /home/circleci/repo/src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala:90:34: method removeRegions has return statement; needs result type
[error]       case None | Some(false) => return MessageEffect(s"${commandName}コマンドは保護をかけて整地する整地ワールドでのみ使用出来ます")
```

2020-12-14 12:23 UTC, Lucky3028 commented
ありがとうございます！直しました。（自分でbuildしてみるの忘れてた）

2020-12-14 16:21 UTC, kory33 requested changes
`removeRegions` は最後の作用を計算する過程で副作用を起こしている(`removalTargets.foreach { ... }`)のでIOで包まれているべきですね

2020-12-14 16:21 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala
> +      IO(removeRegions(world, days))
```suggestion
      removeRegions(world, days)
```

2020-12-14 16:21 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/commands/RmpCommand.scala
> +      IO(removeRegions(world, days))
```suggestion
      removeRegions(world, days)
```

2020-12-15 02:46 UTC, Lucky3028 commented
> `removeRegions` は...IOで包まれているべき...
呼び出し側で「IOで囲まれている」のではないんです...？requested changesの内容と矛盾していません...？

2020-12-15 02:48 UTC, kory33 commented
@Lucky3028 

> removeRegions は...IOで包まれているべき...

言い方が悪かったかもしれない、「 `removeRegions` は `IO` であるべき」が正しそう

2020-12-15 02:52 UTC, Lucky3028 commented
なんとなく理解できました

2020-12-15 02:57 UTC, kory33 approved these changes
👍

2020-12-15 02:57 UTC, merged

2020-12-15 03:20 UTC, Lucky3028 commented
えっこっちはまだ何も変えてないですよ？？？ @kory33

2020-12-15 03:21 UTC, kory33 commented
すみません、脳みそが眠ってた！！！develop側で変えます！！

2020-12-15 03:22 UTC, Lucky3028 commented
お体ご自愛していただいて...