SeasonalEventsのアイテム付与処理をフラグを要らない形にする
GiganticMinecraft/SeichiAssist pull request #846
Opened 2020-12-20 09:28 UTC by Lucky3028

ここまで（83a0ee6）はできたんですが、`bookedachievement`でいう`GrantBookedAchievementListener`のあたりがいまいちわからん...

2020-12-23 08:14 UTC, Lucky3028 commented
7862ea5 で見様見真似でやってみはしましたがさっぱりわからん...IOなに？？？

2020-12-23 14:22 UTC, Lucky3028 commented
とりあえずn周年記念の方だけできました！

2020-12-23 14:25 UTC, Lucky3028 commented
（sqlのdatetime型をjavaのLocalDateTimeに変換できるのかどうかは疑問）

2020-12-23 14:44 UTC, Lucky3028 commented
n周年記念は付与されるタイミングが死んだときだったので、lastQuitは利用できないことに気づきました

2020-12-24 10:00 UTC, Lucky3028 commented
できましたー

2020-12-28 16:33 UTC, kory33 requested changes

2020-12-28 16:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/infrastructure/JdbcLastQuitPersistenceRepository.scala
> +        sql"select lastquit from ${DatabaseConstants.PLAYERDATA_TABLENAME} where name = '$key'"
プレーヤー名はlowerCaseになっているものとそうでないものが混じってる可能性がありあんまり信頼すべきでは無さそう　UUIDの方を使うのが安全です

2020-12-28 16:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/newyear/NewYearListener.scala
> +        effects.foreach(_.run(player))
`effects` を `List` にして `effects.traverse(_.run(player))` (`_.run(player)` は副作用を一切起こしません)

2020-12-28 16:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/service/LastQuitInquiringService.scala
> +class LastQuitInquiringService[
この `Service` オブジェクトは要らなさそうです(何もしていないので)

2020-12-28 16:33 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seasonalevents/valentine/ValentineListener.scala
> +        effects.foreach(_.run(player))
同上

2020-12-29 05:36 UTC, Lucky3028 commented
レビューありがとうございます！直しましたー

2020-12-29 05:53 UTC, kory33 approved these changes
LGTM. ありがとうございます！

2020-12-29 05:54 UTC, merged