独自アイテムの不適切なアイテムドロップを回避する
GiganticMinecraft/SeichiAssist pull request #847
Opened 2020-12-20 10:30 UTC by Lucky3028

This closes #844.

2020-12-20 13:57 UTC, KisaragiEffective requested changes

2020-12-20 13:57 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/bukkit/listeners/MebiusDropTrialListener.scala
> +    if (!ManagedWorld.WorldOps(player.getWorld).isSeichi) return
`ManagedWorld.WorldOps`は`implicit class`
```suggestion
    if (!player.getWorld.isSeichi) return
```

2020-12-20 13:57 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/subsystems/mebius/bukkit/listeners/MebiusLevelUpTrialListener.scala
> +    if (!ManagedWorld.WorldOps(player.getWorld).isSeichi) return
```suggestion
    if (!player.getWorld.isSeichi) return
```

2020-12-20 14:16 UTC, Lucky3028 commented
レビューありがとうございます！なおしました

2020-12-20 14:38 UTC, KisaragiEffective approved these changes

2020-12-21 09:28 UTC, Lucky3028 commented
なんか忘れていると思ったら、MebiusのListenerの部分のimplicitを変更するのを忘れていました！

2020-12-21 12:41 UTC, kory33 approved these changes

2020-12-21 12:42 UTC, merged

2020-12-21 12:58 UTC, Lucky3028 commented
あっ...