毎年日付が変わる祝日の実績の日付が実際の日付とずれるのを修正
GiganticMinecraft/SeichiAssist pull request #854
Opened 2020-12-25 04:51 UTC by Lucky3028

This closes #174

春分の日だけだった。

2020-12-26 06:00 UTC, KisaragiEffective approved these changes

2020-12-30 06:30 UTC, kory33 requested changes

2020-12-30 06:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +        now.getMonth == month && now.getDayOfMonth == dayOfMonth
- ケース分けのビジネスロジックをここに書くべきではなさそう(SpringEquinoxDay側で計算すべき)
 -  `LocalDate` を取る `playedOn` を(既存のものを流用して)定義してよさそう
 - 計算式の出所が不明なので参考になるURLとかをコメントで書いていただけると助かります…！

2020-12-30 06:30 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/achievement/NeedToBeCalculatedOfWhen.scala
> +sealed trait NeedToBeCalculatedOfWhen
`NamedHoliday` / `PublicHoliday` みたいな名前がよさそう

2020-12-30 06:49 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +        now.getMonth == month && now.getDayOfMonth == dayOfMonth
> `LocalDate` を取る `playedOn` を(既存のものを流用して)定義してよさそう

というのは...？

2021-04-27 23:19 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +        now.getMonth == month && now.getDayOfMonth == dayOfMonth
`playedOn(ld: LocalDate, name: String)` ?

2021-04-27 23:20 UTC, KisaragiEffective commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +        now.getMonth == month && now.getDayOfMonth == dayOfMonth
`playedOn(ld: LocalDate, name: String)` ?

2021-04-29 11:44 UTC, Lucky3028 commented on src/main/scala/com/github/unchama/seichiassist/achievement/AchievementConditions.scala
> +        now.getMonth == month && now.getDayOfMonth == dayOfMonth
なるほど？（それ何の意味があるんでしょう...？）

2021-07-20 19:54 UTC, kory33 approved these changes

2021-07-20 19:54 UTC, merged