[update] fix #918; レベルアップ記念のガチャ券を通常のガチャ券に変更する
GiganticMinecraft/SeichiAssist pull request #940
Opened 2021-03-13 09:16 UTC by KisaragiEffective

2021-03-13 09:18 UTC, KisaragiEffective commented
TODO: ガチャポイントの加算

2021-03-14 01:08 UTC, kory33 requested changes

2021-03-14 01:08 UTC, kory33 commented on src/main/scala/com/github/unchama/seichiassist/subsystems/seichilevelupgift/bukkit/GiftItemInterpreter.scala
> +      case Item.GachaTicket => GachaSkullData.gachaSkull
これですとガチャポイントが追加される上にガチャ券が配布されます。
関数全体を

```Scala
item match { ... }
```
の形にしてしまって良さそう？

2021-04-27 01:16 UTC, kory33 submitted a review, later dismissed

2021-04-27 01:17 UTC, kory33 commented
@KisaragiEffective conflict解消だけお願いします

2021-04-27 01:20 UTC, kory33 submitted a review, later dismissed

2021-04-27 01:21 UTC, kory33 commented
型注釈入れないといけなさそう

2021-04-27 03:50 UTC, KisaragiEffective commented
fixed

2021-04-28 14:16 UTC, kory33 approved these changes
👍

2021-04-28 14:17 UTC, merged